refactor: 방문 기록 생성/삭제 도메인 변경으로 인한 수정 #122
woowacourse-teams/2024-staccato pull request #129
Opened 2024-08-03 15:05 UTC by devhoya97

## ⭐️ Issue Number
- #122 
## 🚩 Summary

- 방문 기록 생성 시 `request DTO`와 `List<MultipartFile>`을 한 번에 받을 수 있도록 컨트롤러 코드 수정
- 방문 기록 생성 시 `VisitImagesUrl`이 존재하지 않는 경우 NPE가 발생하던 문제 해결
- 여행 기간에 포함되지 않는 방문 기록도 생성할 수 있던 문제 해결
- 위에 대한 테스트 코드들 작성
- 방문 기록 삭제 API 간단한 리팩토링(컨벤션, long) 및 테스트 코드 간단 수정

## 🛠️ Technical Concerns

## 🙂 To Reviwer
- **방문 기록 생성 시 `VisitImagesUrl`이 존재하지 않는 경우 NPE가 발생하던 문제**
API 명세서에 기재된 예시는 아래와 같은데요
```
{
    "travelId": 12,
    "placeName": "우테코 선릉캠",
    "latitude": "37.505523",
    "longitude": "127.050876",
    "address" : "서울특별시 강남구 삼성동 142-38"
    "visitImagesUrl": ["https://example.com/images/namsan_tower.jpg", "https://example.com/images/namsan_tower2.jpg"],
    "visitedAt": "2021-11-08T11:58:20",
}
```
`visitImagesUrl` 이 없을 때는 DTO단에서 null로 받게 될 것 같은데 맞나요? 현재 visitImagesUrl에 대한 null 체크 과정이 없어서 DTO 단에 null이 들어오면 NPE가 터지네요. null이 들어온다고 생각하고, null 체크 과정을 추가했는데 null이 들어오는게 맞는지 잘 모르겠습니다.

## 📋 To Do
- **API 명세와 변수명 통일**
API 명세에 `visitImagesUrl`, `visitImagesFile`이란 용어를 사용했는데 이를 코드에서 사용하는 변수명과 맞추려다 보니 s가 중간에 있어서 `List`인지 구분할 때 헷갈리더라구요. 월요일에 페어(빙티, 호티)와 함께 다시 얘기해서 s를 뒤쪽으로 빼야할 것 같습니다.

2024-08-04 12:59 UTC, linirini requested changes
multipart까지 함께 구현하시느라 정말 수고 많으셨어요!!
커밋을 따라가며 리뷰를 하다보니, 앞에서 남긴 커밋에 대해 뒤에서 이미 수정하신 부분들도 좀 있더라고요😂
그런 부분들은 가볍게 곁눈질(?) 이모지를 남겨주시고 넘어가셔도 될 것 같습니다.
리뷰 반영 후 재요청 부탁드립니다!

2024-08-04 12:59 UTC, linirini commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +        when(visitService.createVisit(any(VisitRequest.class))).thenReturn(1L);
꼭 `any(VisitRequest.class)`가 아니더라도 테스트 데이터인 `visitRequest`로 특정 지어도 될 것 같은데, 위와 같은 선택을 한 이유가 있나요? 혹은 기준이 있나요?
저도 WebMvcTest를 제대로 사용한건 이번이 처음이라 저는 테스트 데이터가 인자로 들어왔을 때로 구현했는데, 카고는 위와 같은 선택을 한 이유가 있는지 궁금해서 물어봅니다!

2024-08-04 12:59 UTC, linirini commented on backend/src/main/java/com/staccato/visit/service/VisitService.java
> +    public VisitIdResponse createVisit(VisitRequest visitRequest) {
long이 아니라 dto로 한번더 감싸셨네요!
리팩토링 사항은 아니고요, 이와 같은 선택을 한 카고의 의견이 궁금합니다!

2024-08-04 12:59 UTC, linirini commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +                        getVisitRequest(null),
getVisitRequest를 사용하는 곳이 한 곳 뿐이네요?
메서드 추출이 의도와 다르게 되어있는 것 같아서 리뷰 남깁니다!

2024-08-04 12:59 UTC, linirini commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +                .andExpect(jsonPath("$.status").value("400 BAD_REQUEST"))
`HttpStatus.BAD_REQUEST.toString()`을 활용할 수 있을 것 같아요!

2024-08-04 12:59 UTC, linirini commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +        List<MockMultipartFile> imageFiles = List.of(
경계값 테스트 👍👍
제안: 그런 의미에서 성공 테스트에서도 5장 등록은 문제없음을 테스트하는 것도 괜찮을 것 같아요!

2024-08-04 12:59 UTC, linirini commented on backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
> +                () -> assertThat(visitImageRepository.findAllByVisitId(visitId)).hasSize(2)
테스트를 위해서 프로덕션에 메서드가 추가되었네요?
테스트 코드가 프로덕션 코드에 영향을 주는 것은 지양하는게 좋을 것 같은데요, 만약 `findAllByVisitId`를 사용하는 곳이 이곳 뿐이라면 다른 방법으로 검증하는 것을 고려해보면 어떨까요?

2024-08-04 12:59 UTC, linirini commented on backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
> +    private Travel saveTravel() {
커밋 따라 리뷰하면서 언급할까 했는데, 이미 수정하셨군요👍👍

2024-08-04 12:59 UTC, linirini commented on backend/src/main/java/com/staccato/visit/service/VisitService.java
> +        if (visitImagesUrl == null) {
빈 리스트가 오는 것이 아닌건가요?
그렇다면 안드로이드와 얘기를 나눠봐야할 부분인 것 같네요!

> 그리고 이미 visitRequest.toVisit()을 했다면, visit 내부에도 visitImageUrl관련 값을 들고 있을 것 같은데, `visitImagesUrl == null`이 노출되어 있기보다는 **visit 객체에게 메세지를** 던지면 어떨까요?

확인해보니, toVisit에서 이미지 관련해서는 받지 않고 있네요? 이 부분은 제 JPA 지식이 짧은 것 같아서, 다같이 모여있을 때 얘기해보면 좋을 것 같네요😂

2024-08-04 12:59 UTC, linirini commented on backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
> +                () -> assertThat(visitImageRepository.findFirstByVisitId(visitId)).isNotEmpty()
이미 제거 하셨네요? 👍👍
커밋을 따라 리뷰하다보니, 앞서 남긴 리뷰는 무시하셔도 될 것 같아요😅

2024-08-04 12:59 UTC, linirini commented on backend/src/test/java/com/staccato/visit/domain/VisitTest.java
> +    @ValueSource(longs = {-1, 2})
👍

2024-08-04 12:59 UTC, linirini commented on backend/src/main/java/com/staccato/visit/controller/docs/VisitControllerDocs.java
> +            @ApiResponse(description = "방문 기록 생성 성공", responseCode = "201"),
content가 누락된 것 같네요?

2024-08-04 12:59 UTC, linirini commented on backend/src/main/java/com/staccato/visit/service/dto/request/VisitRequest.java
>  public record VisitRequest(
상단에 schema가 누락된 것 같아요!

2024-08-04 12:59 UTC, linirini commented on backend/src/main/java/com/staccato/visit/controller/docs/VisitControllerDocs.java
> +            @ApiResponse(description = "방문 기록 삭제에 성공했거나 해당 방문 기록이 존재하지 않는 경우", responseCode = "200"),
여기에서도 각각 ApiResponse에 대해서 content가 누락된 것 같네요!

2024-08-05 08:10 UTC, devhoya97 commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +        when(visitService.createVisit(any(VisitRequest.class))).thenReturn(1L);
저도 사실 WebMvcTest를 처음 써봐서 책에서 본 예제코드대로 사용했어요! 지금 와서 생각해보니 이 테스트 코드 범위 내에서 어떤 request를 보내느냐에 따라 return 값에 변화가 필요하지 않다면 `VisitRequest.class`를 사용하는게 명확한 것 같아요!

2024-08-05 08:17 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/service/VisitService.java
> +    public VisitIdResponse createVisit(VisitRequest visitRequest) {
```
{
    "visitId" : 1
}
```

리턴 값을 위와 같이 주려다보니 dto로 감싸야 했습니다!

2024-08-05 08:23 UTC, devhoya97 commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +                        getVisitRequest(null),
getVisitRequest를 한 번만 쓴 커밋이 있나보네용. 최종커밋본으로 보면 세 곳에서 사용중입니다!

2024-08-05 08:25 UTC, devhoya97 commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +                .andExpect(jsonPath("$.status").value("400 BAD_REQUEST"))
```java
BAD_REQUEST(400, HttpStatus.Series.CLIENT_ERROR, "Bad Request"),
```
toString으로 "400 BAD_REQUEST"라는 문자열을 만들 수 있나요?!

2024-08-05 08:36 UTC, devhoya97 commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +        List<MockMultipartFile> imageFiles = List.of(
굿아이디어~ 반영했습니다!

2024-08-05 08:48 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/service/VisitService.java
> +        if (visitImagesUrl == null) {
넵 빈 리스트가 온다고 하면 문제가 없는 사항인 것 같아요! 안드에게 물어보고 반영하겠습니다 :)

2024-08-05 09:01 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/controller/docs/VisitControllerDocs.java
> +            @ApiResponse(description = "방문 기록 생성 성공", responseCode = "201"),
content가 어떤 역할인지 몰라서 리니의 코드를 보고 왔는데요.
```java
@ApiResponse(description = "등록 및 로그인 성공", responseCode = "200", content = @Content(schema = @Schema(implementation = LoginResponse.class)))
```
아마 여기서 사용한 것처럼 응답 dto.class를 기입해달라는 이야기겠죠?!
근데 아래와 같이 content 속성 없이도 VisitIdResponse.class의 내용이 나오는데 없어도 되는게 아닌지 궁금합니다!
<img width="432" alt="image" src="https://github.com/user-attachments/assets/b7eb8357-f358-4c66-97e3-3a5239a27821">

2024-08-05 09:14 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/service/dto/request/VisitRequest.java
>  public record VisitRequest(
VisitRequest와 VisitIdResponse에 schema 추가했습니다!

2024-08-05 09:25 UTC, linirini commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +                .andExpect(jsonPath("$.status").value("400 BAD_REQUEST"))
넵, 가능합니다:)

2024-08-05 09:27 UTC, linirini commented on backend/src/main/java/com/staccato/visit/controller/docs/VisitControllerDocs.java
> +            @ApiResponse(description = "방문 기록 생성 성공", responseCode = "201"),
응답 예시는 나오지만, 설정한 visitId example로 나오지는 않는 것 같아요!

2024-08-05 09:32 UTC, Ho-Tea requested changes
고생하셨습니다 카고!
비즈니스 로직 상에서 크게 피드백 드릴 부분은 없는 것 같아요 👍
코멘트로 논의해볼 사항에 대해 남겨드렸으니, 확인 부탁드립니다 🙇‍♂️

2024-08-05 09:32 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/visit/service/VisitService.java
> +        visitImageRepository.saveAll(visitImages);
부모 엔티티(`Visit`)에서 자식의 생명주기를 관리하는 방향으로 구성하는 것은 어떨까요!
우선 생각나는 것은 `Cascade PERSIST` 속성으로 전이시키는 것인데 이 부분은 한번 얘기해보시죠!

2024-08-05 09:32 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/visit/service/VisitService.java
> +        if (visitImagesUrl == null) {
빈리스트가 오는 것으로 알고있습니다!

2024-08-05 09:32 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/visit/service/dto/request/VisitRequest.java
> +        @Schema(example = "[\"http://example.com/image1.jpg\"]")
이렇게도 할 수 있더라구요!
``` java
@ArraySchema(
                arraySchema = @Schema(example = "[\"https://example.com/images/namsan_tower.jpg\", \"https://example.com/images/namsan_tower2.jpg\"]"))
```

2024-08-05 09:32 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/visit/service/dto/request/VisitRequest.java
> +        Long travelId
`@NotNull(message = "여행 상세를 선택해주세요.")` 해당 `validation`으로 `null` 값이 들어올 수 없을 것 같아 `Long`이 아닌 `long` 으로 대체 가능할 것 같습니다!

2024-08-05 09:32 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +    @DisplayName("사용자가 잘못된 방식으로 정보를 입력하면, 방문 기록을 생성할 수 없다.")
`@DisplayName("사용자가 잘못된 방식으로 정보를 입력하면, 방문 기록을 생성할 수 없다.")`
잘못된 방식이라는 말이 살짝 모호한 것 같아 `사용자가 잘못된 요청 형식으로 정보를 입력하면 ` 은 어떨까요!

2024-08-05 09:32 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +                .andExpect(jsonPath("$.status").value("400 BAD_REQUEST"))
앞선 코멘트와 같이 `HttpStatus.BAD_REQUEST.toString()`을 활용할 수 있을 것 같아요!

2024-08-05 09:32 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
> +                .build();
꼭 해당 메서드 부분을 분리하자는 의도는 아니며, 단순 객체 생성은 테스트 코드에서 검증해야 할 부분과는 거리가 있는 것 같아 `Fixture`로 분리하는것은 어떻게 생각하실까요!

2024-08-05 10:56 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/service/VisitService.java
> +        if (visitImagesUrl == null) {
빙티에게 물어보니 null이 아닌 빈 리스트가 오는게 맞나봐요. 시나리오상 null이 올 가능성은 없을텐데, 안드쪽에서 실수로 빈 리스트가 아닌 null을 보내개 되면 NPE가 터진다는 점에서 찜찜한 부분은 있는 것 같아요. 좀 더 논의해봐도 좋겠네요!

2024-08-05 11:21 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/visit/controller/docs/MultipartJackson2HttpMessageConverter.java
> +
코드 컨벤션 (클래스 시작 첫줄 개행 없습니다!)

2024-08-05 12:03 UTC, linirini commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +                .andExpect(header().string("Location", "/visits/1"))
`.string(HttpHeaders.LOCATION, "/visits/1")` -> 상수 활용:)

2024-08-05 13:05 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/controller/docs/VisitControllerDocs.java
> +            @ApiResponse(description = "삭제할 권한이 없는 경우", responseCode = "403")
그러네요! 반영했습니다 :)

2024-08-05 13:06 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/service/VisitService.java
> +        visitImageRepository.saveAll(visitImages);
호티의 코드를 보니 언급해주신 방향으로 구현해주신 것 같은데, 호티 코드를 먼저 머지시키면 반영할 수 있겠네요!

2024-08-05 13:23 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/service/dto/request/VisitRequest.java
> +        @Schema(example = "[\"http://example.com/image1.jpg\"]")
처음 보는 어노테이션이네요! 아마 `example`에 여러 개의 파일을 나열하려고 쓰는 것 같은데, 아래와 같이 작성해도 swagger의 try it out이 잘 작동하더라구요!
```java
@Schema(example = "[\"http://example.com/image1.jpg\", \"http://example.com/image2.jpg\"]")
```

Swagger 상에서 두 코드의 차이를 아직 모르겠는데, 체감이 되면 적용해보도록 하겠습니다!!

2024-08-06 01:04 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/service/dto/request/VisitRequest.java
> +        Long travelId
오 놓치고 있었네요! 반영하였습니다 👍

다만 위 과정에서 아래와 같이 맨 뒤에 travelId를 null로 넣었을 때 예외 메시지가 잘 나오는지 테스트하고 있었는데 이 코드는 사용 불가능해졌어요 🥲 travelId 필드가 비어있는 테스트용 DTO를 만들수도 있겠지만, 중요한 테스트 사항은 아닌 것 같아서 일단 넘겼습니다!
```java
Arguments.of(
        new VisitRequest("placeName", "address", BigDecimal.ONE, BigDecimal.ONE, List.of("https://example1.com.jpg"), LocalDate.of(2023, 7, 1), null),
        "여행 상세를 선택해주세요."
),
```

2024-08-06 01:23 UTC, devhoya97 commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +    @DisplayName("사용자가 잘못된 방식으로 정보를 입력하면, 방문 기록을 생성할 수 없다.")
다시 읽어보니 그렇네요! 메시지까지 명확하게 제안해주셔서 감사합니다 :) 
반영했어요!

2024-08-06 01:25 UTC, devhoya97 commented on backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
> +                .build();
사실 `Fixture`에 대해 별 생각이 없었는데, 호티의 코드를 보니 있으면 굉장히 편리한 것 같아요! 제가 레벨2 때 사용한 `Fixture`는 저장할 엔티티들을 모두 상수로 만들어서 사용했는데, static 메서드를 하나 만들어놓는 방식이 아주 유용해보이더라구요.

호티 코드가 머지되면 이를 바탕으로 `Fixture` 적용해보겠습니다 :)

2024-08-06 09:02 UTC, Ho-Tea approved these changes
고생하셨습니다 카고!

2024-08-06 09:02 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/travel/service/TravelServiceTest.java
> +        TravelMember travelMember = travelMemberRepository.findAllByMemberIdOrderByTravelStartAtDesc(member.getId())
습관적 자동정렬로 인한 개행 발생!

2024-08-06 09:02 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
> +                Travel.builder().title("Sample Travel").startAt(LocalDate.now()).endAt(LocalDate.now().plusDays(1))
여기도 습관적 자동정렬로 인한 개행 발생!

2024-08-06 11:13 UTC, linirini approved these changes

2024-08-06 11:13 UTC, merged