refactor: 방문기록 조회/수정 도메인 변경으로 인한 수정 #121
woowacourse-teams/2024-staccato pull request #131
Opened 2024-08-04 19:15 UTC by Ho-Tea

## ⭐️ Issue Number
- #121 
## 🚩 Summary
- `List<VisitImage>` 로 이루어져있던 필드 일급컬렉션화( = `VisitImages`)
- 연관관계 편의 메서드 `VisitImage -> VisitImages`로 위치 변경
- `Visit -> VisitImages Cascade` 설정 변경

## 🛠️ Technical Concerns
- `List<VisitImage>` 로 이루어져있던 필드 일급컬렉션화( = `VisitImages`)
  - [참고할 만한 블로그](https://wbluke.tistory.com/23)
  - 수정되어지는 이미지와 기존에 존재하는 이미지의 총 갯수가 5장을 초과하면 안되는 비즈니스로직으로 인하여 `VisitImages`라는 일급컬렉션 객체를 생성하고 해당 객체에게 검증의 책임을 부여했습니다. 
  - 그로 인해 기존에 존재하던 코드의 수정이 불가피하게 일어났는데, 일급컬렉션을 적용하는 것에서는 토의가 필요해 보입니다.

- 연관관계 편의 메서드 `VisitImage -> VisitImages`로 위치 변경, `Visit -> VisitImages Cascade` 설정 변경
  - `VisitImage`는 `Visit`이 없으면 존재할 수 없어서 `Visit`이 `VisitImage`의 모든 생명주기를 관리하는 것이 적합해 보였습니다. 
  - 그렇다면 일일이 `VisitImage`를 `save`하는 과정없이 모든 생명주기 관리를 부모가 하게하면 되지 않을까? 라는 생각으로 출발하여 `PERSIST` 전이를 이용하여 `Visit`이 생성될 때 `VisitImage` 까지 모두 생성되게끔 변경하였습니다. 
  - 이 과정에서 일전에 토의했었던 `CascadeType.REMOVE`의 경우 자식 엔티티 삭제가 전파되지 않고, `CascadeType.PERSIST`의 경우 자식 엔티티 삭제가 전파되는 문제 또한 발견하였고, 현재 부모 엔티티 컬렉션에서 자식 엔티티를 삭제 시 자식 엔티티까지 삭제가 전파되는 것 테스트 완료 하였습니다.

## 🙂 To Reviwer
- 일급컬렉션을 적용해 보았는데, 의도치 않게 다른 부분에 코드의 변경이 있었습니다. 우선은 오류만 안나게 설정해놓은거라 **조회**와 **수정** 로직 위주로만 리뷰해주시면 될 것 같습니다.
- `Multipart`와 관련된 부분은 현재 더 토의가 필요해 보여 간단하게만 구성하였습니다. 익일 얘기나눈 후 리팩토링 할 것 같습니다.

## 📋 To Do
- `Multipart` 요청 구체화
- `Authorization` 추가로 인한 인증 인가 구현
- `TravelFixture` 등 `Test Fixture` 고려
- `Entity`에 `Equlas&HashCode` 적용 고려
  - [참고할 만한 공식 문서](https://docs.jboss.org/hibernate/stable/core.old/reference/en/html/persistent-classes-equalshashcode.html)

2024-08-05 01:56 UTC, linirini requested changes
호티, 수고많으셨어요!!
일급 컬렉션 적용은 좋은 시도인 것 같아요👍👍
잘 구현해주셔서 궁금한 부분과 몇가지 소소한 리뷰 남겼는데요,
리뷰 반영하고 재요청해주세요!

2024-08-05 01:56 UTC, linirini commented on backend/src/test/java/com/staccato/visit/fixture/VisitRequestFixture.java
> +        return new VisitRequest("placeName", "address", VisitFixture.latitude, VisitFixture.longitude, List.of("https://example1.com.jpg"), visitedAt, travelId);
상수 값을 확인하려면, 다른 클래스를 열어봐야겠네요!
의미없는 값이기 때문에 상수를 재사용하려는 의도였던 것은 알겠으나, 의도하지 않은 사용을 방지하기 위해서 재사용 보다는 private으로 닫는 것이 어떨까요?

2024-08-05 01:56 UTC, linirini commented on backend/src/test/java/com/staccato/visit/service/VisitServiceTest.java
> +        assertThat(visitService.readVisitById(visit.getId())).isEqualTo(new VisitDetailResponse(visit));
검증하고자 하는 부분이 `visitService.readVisitById(visit.getId())`인 것 같은데요,
`// when` 절을 분리해주면 가독성이 더 좋을 것 같다는 생각이 드네요!
호티 생각은 어떠신가요?

2024-08-05 01:56 UTC, linirini commented on backend/src/main/java/com/staccato/visit/domain/VisitImages.java
> +@NoArgsConstructor(access = AccessLevel.PUBLIC)
`PROTECTED`가 아닌 `PUBLIC`으로 설정한 이유가 있나요?

2024-08-05 01:56 UTC, linirini commented on backend/src/main/java/com/staccato/visit/domain/VisitImages.java
> +                    image.setVisit(visit);
`setVisit` 자체를 사용하기보다, 메세지를 담은 메서드를 만들면 어떨까요?
가령 `image.belongsTo(visit)`같은 방식으로요!

2024-08-05 01:56 UTC, linirini commented on backend/src/main/java/com/staccato/visit/domain/VisitImages.java
> +    private void addAllWithoutExist(VisitImages visitImages, Visit visit) {
필수 리팩터링 사항은 아니고, 메서드 네이밍 제안입니다!
`addNewImages`는 어떨까요?

2024-08-05 01:56 UTC, linirini commented on backend/src/main/java/com/staccato/visit/domain/VisitImages.java
> +        copyVisitImages.stream()
이 부분에서 하고자 하는 것이 한 눈에 들어오지 않는데요, 제가 이해한 바가 맞다면, 변경사항에서 삭제된 이미지들을 제거하는 과정이 맞을까요?
복사본과, 아닌 것을 함께 보려니 헷갈리는 것 같은데, 메서드를 분리해주면 좋을 것 같아요!

2024-08-05 01:56 UTC, linirini commented on backend/src/test/java/com/staccato/visit/domain/VisitImagesTest.java
> +        assertThatThrownBy(() -> new VisitImages(List.of("picture1", "picture2", "picture3", "picture4"), List.of( "picture5", "picture6")))
앞서 말했듯 어떤 것이 원본이고, 새로운 것인지 잘 보이지 않아서 빌더를 사용하면 좋을 것 같아요 ㅎㅎ

2024-08-05 01:56 UTC, linirini commented on backend/src/test/java/com/staccato/visit/domain/VisitImagesTest.java
> +                () -> assertThat(existingImages.getImages().get(0).getImageUrl()).isEqualTo("picture1"),
인덱스 순서에 테스트가 영향 받을 수도 있을 것 같아요!
containsAll()과 같은 검증 메서드를 활용해보면 어떨까요?

2024-08-05 01:56 UTC, linirini commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +    void failUpdateVisitByImagesSize() throws Exception {
이 부분은 저번주에 제가 호티에게 질문했던 부분일 것 같은데요, DTO에서 검증하는 부분이 아닌 서비스 계층에서 검증하는 부분인 것 같은데요
호티가 이 부분에 대한 테스트를 컨트롤러에서도 한 이유가 궁금합니다!
혹시 DTO에서 검증하는 부분이라 작성한 테스트인데, 제가 놓친거라면 말해주세요😅

2024-08-05 11:05 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/visit/fixture/VisitRequestFixture.java
> +        return new VisitRequest("placeName", "address", VisitFixture.latitude, VisitFixture.longitude, List.of("https://example1.com.jpg"), visitedAt, travelId);
> 상수 값을 확인하려면, 다른 클래스를 열어봐야겠네요

해당 코멘트에 공감이 되었습니다. 반영할게요!

2024-08-05 12:00 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/visit/domain/VisitImages.java
> +    public VisitImages(List<String> existingImages, List<String> addedImages) {
확실히 Builder로 표현하였을 때 더 가독성있는 것 같아요!
반영했어요 😊

``` java
VisitImages visitImages = new VisitImages(visitUpdateRequest.visitImagesUrl(), addedImages);


VisitImages visitImages = VisitImages.builder()
        .existingImages(visitUpdateRequest.visitImagesUrl())
        .addedImages(addedImages)
        .build();
```

2024-08-05 12:13 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/visit/domain/VisitImages.java
> +    private void addAllWithoutExist(VisitImages visitImages, Visit visit) {
인자로 넘어오는 `visitImages`에 기존에 존재하는 이미지도 포함되어있어서 
`newImage`가 아닌 기존에 있는 것을 제외하고 추가한다는 의미를 부여했어요.
`addNewImages`의 경우 오해의 소지가 있을 것 같다고 판단되는데 리니는 어떻게 생각하실까요!

2024-08-05 12:26 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/visit/domain/VisitImagesTest.java
> +                () -> assertThat(existingImages.getImages().get(0).getImageUrl()).isEqualTo("picture1"),
현재 검증 부분은 순서가 중요하지 않아 인덱스 순서에 따라 검증하는 것보다 말씀처럼 containsAll()로 처리하는 것이 합리적으로 보이네요! 반영했어요 😊

2024-08-05 12:36 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/visit/service/VisitService.java
> +        visit.update(visitUpdateRequest.placeName(), visitImages);
도메인에게 `update`에 대한 책임이 주어진 만큼, `Visit` 도메인을 전달하는 것 괜찮은 것 같아요! 반영했어요 😊

2024-08-05 12:38 UTC, devhoya97 reviewed
update 로직이 현재까지의 우리 비즈니스 로직 중 가장 복잡한 로직인 것 같은데, 멋지게 구현해주셨네요 :) 간단한 코멘트 몇개 남겨두었는데 확인 부탁드려요. 다시 리뷰요청 주시면 approve 드리겠습니다!

2024-08-05 12:38 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/domain/VisitImages.java
> +                .anyMatch(visitImage -> visitImage.getImageUrl().equals(image.getImageUrl()));
visitImage로부터 getter로 Image를 꺼낸 뒤 비교하기보다, VisitImage에 `isSameUrl(String imageUrl)`와 같은 메서드를 만들어서 메시지를 던지는건 어떨까요?!

2024-08-05 12:44 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +    void failUpdateVisitByImagesSize() throws Exception {
기존 이미지 Url 과 새롭게 추가된 이미지 파일을 받는데 `fast fail`을 위해서 새롭게 추가된 이미지 파일들의 갯수가 5개 이상인 경우 서비스 로직까지 내려가지 않아도 되게끔 검증하는 로직을 추가하였습니다! 
해당 부분은 새롭게 추가된 이미지 파일들만을 검증하는 것이고, 내부적으로 기존 이미지 Url과 새롭게 추가된 이미지 파일들의 갯수가 총 5개인지 확인하는 서비스 로직은 따로 구성하였습니다!

2024-08-05 13:50 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/visit/domain/VisitImages.java
> +                .anyMatch(visitImage -> visitImage.getImageUrl().equals(image.getImageUrl()));
더 가독성 있이 구성될 것 같네요 반영했어요 😊

2024-08-06 06:17 UTC, devhoya97 approved these changes

2024-08-06 06:23 UTC, linirini approved these changes

2024-08-06 06:41 UTC, merged