feat: 여행 상세 목록 조회, 특정 여행 상세 조회, 특정 여행 상세 삭제 API 수정
woowacourse-teams/2024-staccato pull request #149
Opened 2024-08-05 15:57 UTC by linirini

## ⭐️ Issue Number
- #148
## 🚩 Summary

- API 명세서 문서화
![image](https://github.com/user-attachments/assets/94642569-325c-4586-af1d-64d7de472810)
-> Error Response에 Schema 예시를 만들었더니, 예제 json 형태가 아쉬운 것 같아요! 이 부분에 대해서 어떻게 생각하는지 궁금합니다:)
- 특정 여행 상세 조회, 특정 여행 상세 삭제에 대한 인가 예외 처리
- 컨트롤러 단위 테스트 작성

## 🛠️ Technical Concerns

## 🙂 To Reviwer

## 📋 To Do

2024-08-06 08:39 UTC, BurningFalls commented on backend/src/main/java/com/staccato/member/service/dto/response/MemberResponse.java
> +        @JsonInclude(JsonInclude.Include.NON_NULL)
`JsonInclude.Include.NON_NULL` -> 필드 값이 `null`이 아닌 경우에만 Json에 포함한다.

개념 리마인드로 기록해 놓습니다!

2024-08-06 08:40 UTC, BurningFalls commented on backend/src/main/java/com/staccato/member/service/dto/response/MemberResponse.java
> +        @JsonInclude(JsonInclude.Include.NON_NULL)
`JsonInclude.Include.NON_NULL` -> 필드 값이 `null`이 아닌 경우에만 Json에 포함한다.

개념 리마인드로 기록해 놓습니다!

2024-08-06 08:49 UTC, Ho-Tea requested changes
많은 API를 구성하셨음에도 불구하고 꼼꼼히 너무 잘 만들어주신 것 같아요! 👍👍 
고생하셨습니다 리니!!
의견 나눌 부분과 사소한 부분 코멘트 남겨드렸습니다.
확인 부탁드릴게요!! 🙇‍♂️

>Error Response에 Schema 예시를 만들었더니, 예제 json 형태가 아쉬운 것 같아요! 이 부분에 대해서 어떻게 생각하는지 궁금합니다:)
- 모든 에러들이 같은 에러형식을 사용하고 있기에 특정 에러의 경우 응답상태와 바디를 커스텀하기가 swagger상에서 어려움이 있어 보입니다. 에러가 발생하는 상황에대해 정의하였고 상태코드 또한 swagger상에서 확인 가능하니 말씀하신 것처럼 구성하지 않고 아래로만 유지해도 큰 어려움은 없을 것 같아요!
``` java
{
  "status": "string",
  "message": "string"
}
```

2024-08-06 08:49 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/travel/controller/TravelController.java
> +            @PathVariable @Min(value = 1L, message = "여행 식별자는 양수로 이루어져야 합니다.") long travelId) {
👍

2024-08-06 08:49 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/travel/domain/Travel.java
> +                .noneMatch(travelMember -> travelMember.getMember().getId() == member.getId());
`Wrapper` 형태이므로 동일성 비교보다는 동등성 비교를 해야 할 것 같아요

2024-08-06 08:49 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/travel/service/TravelService.java
> +        }
참조 무결성으로 발생하는 에러 대신에 저희가 구성한 에러를 던지기 위해 구성하신걸까요?
에러가 클라이언트 친화적으로 변한 것 같아 좋은 것 같아요 😊

2024-08-06 08:49 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/travel/controller/TravelControllerTest.java
> +    }
`given`으로 `travelId`를 특정해 놓은 다음 아래와 같이 구성하여 어떤 `PathVariable` 값으로 전달되는지 한눈에 알 수 있게 하는 것도 괜찮을 것 같네요!


``` java
    @DisplayName("사용자가 특정 여행 상세를 조회한다.")
    @Test
    void readTravel() throws Exception {
        // given
        long travelId = 1L;
        when(authService.extractFromToken(anyString())).thenReturn(Member.builder().nickname("staccato").build());
        TravelDetailResponse travelDetailResponse = new TravelDetailResponse(createTravel(), List.of());
        when(travelService.readTravelById(anyLong(), any(Member.class))).thenReturn(travelDetailResponse);

        // when & then
        mockMvc.perform(get("/travels/{travelId}", travelId)
                        .header(HttpHeaders.AUTHORIZATION, "token"))
                .andExpect(status().isOk())
                .andExpect(content().json(objectMapper.writeValueAsString(travelDetailResponse)));
    }
```

2024-08-06 08:49 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/travel/controller/TravelControllerTest.java
> +        mockMvc.perform(delete("/travels/1")
위와 같은 코멘트에요 😊

2024-08-06 08:49 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/travel/controller/TravelControllerTest.java
> +        mockMvc.perform(delete("/travels/" + invalidId)
`+`로 문자열을 더하지 않고 아래와 같이 가능하겠네요!
`mockMvc.perform(delete("/travels/{travelId}",  invalidId)`

2024-08-06 09:04 UTC, BurningFalls commented on backend/src/main/java/com/staccato/travel/service/TravelService.java
> +        validateVisitExistsByTravel(travel);
`validateVisitExistsByTravel` 메서드에는 `travelId`만 전달해도 충분할 것 같지만, `validateOwner`는 `travel`을 전달하지 않으면 애매하네요. 그래서 밑의 메서드에도 통일성을 갖도록 `travel`을 전달한 것일까요?

2024-08-06 10:49 UTC, BurningFalls approved these changes
수정해야하는 부분은 없네요. 고생하셨습니다!

2024-08-06 10:55 UTC, BurningFalls commented
> Entity Equals&hashCode id 기준 오버라이딩을 고려해보면 좋을 것 같아요! 메서드에서 동등성 비교할 때 아쉬운 부분이 있습니다.

`Member`에 member의 id를 기준으로 equals 및 hashCode를 재정의하면, 아래와 같이 코드가 바뀌겠네요. 좋다고 생각합니다!

```java
public boolean isNotOwnedBy(Member member) {
    return travelMembers.stream().noneMatch(travelMember -> travelMember.getMember().equals(member);
}
```

2024-08-06 11:02 UTC, devhoya97 requested changes
API 여러개 만드느라 고생하셨습니다 리니!! 리뷰 몇개 남겼는데 확인 부탁드려요 :)

2024-08-06 12:34 UTC, linirini commented on backend/src/main/java/com/staccato/travel/service/TravelService.java
> +        }
맞아요! 저희 서비스 예외처리 위해서 구현했습니다👍

2024-08-06 15:24 UTC, linirini commented on backend/src/test/java/com/staccato/travel/controller/TravelControllerTest.java
> +    }
저도 호티의 의견에 동의합니다! 좋은 제안 고마워요👍

2024-08-06 15:25 UTC, linirini commented on backend/src/main/java/com/staccato/travel/service/TravelService.java
>      public void updateTravel(TravelRequest travelRequest, Long travelId) {
update는 이번 pr 범위가 아니라서 구현하지 않았습니다! 다음에 해당 이슈 구현할 때 추가하겠습니다👍

2024-08-06 15:26 UTC, linirini commented on backend/src/main/java/com/staccato/travel/domain/Travel.java
> +                .noneMatch(travelMember -> travelMember.getMember().getId() == member.getId());
카고의 의견처럼 비슷하게 `isMember(member)`라는 메서드로 분리했어요. 다만, travel이 아니라 travelMember에서 던지는 메세지라서 이와 같이 메서드명을 지어봤습니다:)

2024-08-06 15:28 UTC, linirini commented on backend/src/main/java/com/staccato/travel/service/TravelService.java
>          visitRepository.deleteAllByTravelId(travelId);
사용자가 실수로 여행 상세를 삭제하는 것을 방지하기 위함이었어요!
기록의 소중함이라는 저희 서비스의 의의에도 방문 기록에 들어가서 삭제하는 것이 아니라면 함부로 삭제하지 못하게 하자는 이유도 있었습니다:)

2024-08-07 01:27 UTC, linirini commented on backend/src/main/java/com/staccato/travel/service/TravelService.java
> +        validateVisitExistsByTravel(travel);
'방문기록(visit)가 존재하는지 여행(Travel)을 기준으로 찾는다' 라는 메세지가 더 이해하기 쉽고, 객체지향적인 접근이라고 생각해서 이와 같이 했습니다.

2024-08-07 01:29 UTC, linirini commented on backend/src/main/java/com/staccato/travel/service/TravelService.java
> +        return visitImageRepository.findFirstByVisitId(visit.getId())
양방향 설정 이전의 코드였는데, 놓치고 있었습니다. 좋은 제안 고마워요👍
DTO에서 첫번째 사진을 고른다는 것은 DTO에서 비즈니스 로직을 수행하는 것 같네요,
예를 들어 2장을 주겠다는 것으로 정책이 바뀐다면 DTO를 열어봐야 하는것보다는 서비스에서 처리하는 것이 자연스러운 것 같아요!

2024-08-07 01:33 UTC, linirini commented on backend/src/main/java/com/staccato/travel/service/TravelService.java
> +        return visitImageRepository.findFirstByVisitId(visit.getId())
![image](https://github.com/user-attachments/assets/83f5a9f0-829e-49e6-8aa7-bf4a927d08fd)
visit에게 thumbnail용 이미지를 달라고 메세지를 던지는 방식으로 리팩터링 했습니다.
결국 찾고자 하는 첫번째 사진은 "썸네일용"이고, 어떻게 로직이 변경될지 모르기 때문에 "무엇을"하는지 메세지를 던지도록 했습니다.

2024-08-07 02:10 UTC, linirini commented on backend/src/main/java/com/staccato/visit/repository/VisitRepository.java
> +    boolean existsByTravel(Travel travel);
travel 정보를 들고 있어서, 좀 더 객체지향적인 메서드명을 사용해보고자 했습니다😅

2024-08-07 02:15 UTC, Ho-Tea approved these changes

2024-08-07 02:21 UTC, devhoya97 approved these changes

2024-08-07 02:23 UTC, merged