feat: 이미지가 필요한 API에 S3 적용
woowacourse-teams/2024-staccato pull request #168
Opened 2024-08-07 12:11 UTC by devhoya97

## ⭐️ Issue Number
- #166 
## 🚩 Summary
S3 적용이 필요한 API들 변경
- 여행 상세 생성 API
- 여행 상세 수정 API
- 방문 기록 생성 API
- 방문 기록 수정 API

## 🛠️ Technical Concerns

## 🙂 To Reviwer

## 📋 To Do
썸네일 삭제 또는 방문 기록 사진 삭제 시 DB에는 URL이 삭제되지만 S3 파일 자체는 삭제되지 않습니다. S3에서 제공하는 delete 메서드가 우리의 service 메서드의 트랜잭션 안에 포함될 수 없어서 적용하지 못했는데, 이 문제를 고민해보고 적용해보면 좋겠어요.

2024-08-07 13:47 UTC, Ho-Tea requested changes
고생하셨습니다 카고 폭포!!
Fake 를 너무 잘 구현해주셔서 딱히 피드백 드릴 부분은 없는 것 같아요!
사소한 코멘트 남겨드렸는데 확인 부탁드려요 👍

2024-08-07 13:47 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/travel/service/TravelService.java
> +        if (thumbnailFile == null) {
`Objects.isNull()`로 대체 가능하겠네요!

2024-08-07 13:47 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/travel/service/TravelService.java
> +        if (thumbnailFile == null) {
추가로 코드컨벤션에 맞게 `private` 도우미 메서드는 마지막 사용메서드 아래의 위치 시켜주세요! 😊

2024-08-07 13:47 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/TestConfig.java
> +    }
👍

2024-08-07 13:48 UTC, linirini approved these changes

2024-08-08 02:01 UTC, Ho-Tea approved these changes

2024-08-08 02:01 UTC, merged