feat: Entity 구성 #2
woowacourse-teams/2024-staccato pull request #17
Opened 2024-07-21 18:12 UTC by Ho-Tea

## ⭐️ Issue Number
- #2 

## 🚩 Summary

![image](https://github.com/user-attachments/assets/f721ccb7-c6e7-4454-9bc0-b7f7d5202405)
- 작성한 ERD를 기반으로 JPA Entity 구성

## 🛠️ Technical Concerns
- 작성된 `ERD`에서는 `created_at`이 `LocalDate`로 표현이 되었지만, `log`를 남기기 위한 목적임을 감안해 `LocalDateTime`으로 변경하는 것을 고려 중
- `h2` 는 `TinyInt`를 지원하지 않아 따로 `columnDefinition`으로 명시하지 않았습니다.

## 🙂 To Reviwer

## 📋 To Do
- API 기능 중심으로 역할 분담

2024-07-21 21:35 UTC, linirini requested changes

2024-07-21 21:35 UTC, linirini commented on backend/src/main/java/com/staccato/config/domain/BaseEntity.java
> +    public void delete() {
setter를 사용한 삭제가 아닌 `@SQLDelete`를 사용하는 방법도 있을 것 같네요!

참고: https://velog.io/@jsb100800/Spring-boot-JPA-Soft-Delete-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0

2024-07-21 21:35 UTC, linirini commented on backend/src/main/java/com/staccato/member/domain/Member.java
> +@Table(name = "member")
테이블명은 default로 entity의 이름을 사용함에도 `@Table`로 name을 지정해준 이유가 있나요?

2024-07-21 23:28 UTC, devhoya97 reviewed
모든 파일 다 봤는데 문제점은 발견하지 못했어요! 궁금한 점 하나 코멘트 남겨두었습니다. 고생했어요 호티👍 :)

2024-07-21 23:28 UTC, devhoya97 commented on backend/src/main/java/com/staccato/travel/domain/Travel.java
> +    @Column(columnDefinition = "TEXT")
안써봐서 잘 모르긴 하는데, 찾아보니까 `columnDefinition`은 특정 데이터베이스에 종속적이므로 `@Lob`을 사용하는 것을 추천하는 것 같은데 어떻게 생각하시나요?

2024-07-22 00:53 UTC, devhoya97 requested changes
.

2024-07-22 03:58 UTC, BurningFalls approved these changes
안녕하세요, 호티. 폭포입니다.

ERD와 코드를 비교하면서 점검해보았는데, 문제 없는 것 같습니다.
`@MappedSuperclass`와 `@EntityListeners`로 `BaseEntity`를 구성하는 방법은 제가 몰랐던 새로운 개념이라 추가로 공부해보려고 합니다.

고생하셨습니다!

2024-07-22 04:32 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/member/domain/Member.java
> +@Table(name = "member")
명시적으로 해당 테이블의 이름을 확인하기 위해 붙였습니다!

2024-07-22 05:43 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/travel/domain/Travel.java
> +    @Column(columnDefinition = "TEXT")
<img width="417" alt="image" src="https://github.com/user-attachments/assets/2e5c4ea6-7df6-441a-8d8c-5baca0919827">

h2에서는 `TEXT` 자료형이 사용되지 않는다고 알려져있는데 문제 없이 DDL이 생성되는 것을보고 현재는 `@Lob`을 사용하지 않았습니다!

2024-07-22 05:50 UTC, devhoya97 approved these changes

2024-07-22 05:52 UTC, linirini approved these changes
다 반영된 것 같아서 approve 하겠습니다👍

2024-07-22 05:53 UTC, merged