feat: 추억 목록 조회 API 수정 #215
woowacourse-teams/2024-staccato pull request #216
Opened 2024-08-15 08:28 UTC by linirini

## ⭐️ Issue Number
- #215 

## 🚩 Summary
- `추억 상세` 라는 표현을 모두 `추억`이라는 표현으로 대체했습니다.
- 응답 필드에서 `description`과 `mates`가 제거되었습니다.
- 목록 조회 시 정렬 기준이 추억이 생성된 날짜 기준 최신순으로 변경 되었습니다. -> `OrderByCreatedAtDesc`
- 누락되어있던 잘못된 형식의 년도에 대한 검증을 추가했습니다.
- swagger docs에도 변경 사항을 반영했습니다.
- 기간(startAt, endAt)에 값이 없을 경우 응답 필드에서 보여주지 않도록 처리했습니다.

## 🛠️ Technical Concerns

## 🙂 To Reviewer

## 📋 To Do

2024-08-15 09:56 UTC, devhoya97 approved these changes
간단한 의견 남겼습니다 👍

2024-08-15 09:56 UTC, devhoya97 commented on backend/src/main/java/com/staccato/StaccatoApplication.java
>  public class StaccatoApplication {
```java
@SpringBootApplication
@EnableJpaAuditing
public class StaccatoApplication {

    public static void main(String[] args) {
        SpringApplication.run(StaccatoApplication.class, args);
    }

}
```
PR에 남기신 테스트 코드를 똑같이 만들어서 돌려보니까 createdAt이 null로 저장되고 있었네요. GPT에게 물어봐서 위와 같이 `@EnableJpaAuditing` 옵션을 주니까 제시해주신 테스트 메서드가 통과합니다!

2024-08-15 09:56 UTC, devhoya97 commented on backend/src/test/java/com/staccato/memory/domain/MemoryTest.java
> +        assertThatCode(() -> MemoryFixture.create(LocalDate.MAX, LocalDate.MIN))
(반영하지 않아도 되는 의견)
경계 값은 아래와 같지 않을까요?!
1. 시작 날짜와 끝 날짜가 같을 때
2. 시작 날짜가 끝 날짜보다 하루 뒤 일때.

2024-08-15 12:34 UTC, Ho-Tea requested changes
고생하셨습니다 리니!! 
사소한 코멘트 남겨드렸는데 확인 부탁드려요 🙇‍♂️

2024-08-15 12:34 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/memory/service/MemoryServiceTest.java
> +                .hasMessage("해당 추억 상세에 순간 기록이 남아있어 삭제할 수 없습니다.");
해당 메세지를 출력하게끔 로직을 가져갈지 아니면, 삭제가 전파되게 구성할지 얘기가 필요해보입니다!

2024-08-15 12:34 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/memory/repository/MemoryMemberRepositoryTest.java
> -
코드를 그대로 가져와 Local에서 테스트 진행했을 때는 통과합니다..!

2024-08-15 12:37 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/memory/repository/MemoryMemberRepositoryTest.java
> -
``` java
    @DisplayName("사용자 식별자로 해당하는 추억 목록만 최근 생성된 순서대로 조회한다.")
    @Test
    void findAllByMemberIdAndMemoryStartAtYearWithoutDeleted() {
        // given
        Member member = memberRepository.save(Member.builder().nickname("staccato").build());
        Memory memory = memoryRepository.save(createMemory(LocalDate.of(2023, 12, 31), LocalDate.of(2024, 1, 10)));
        Memory memory2 = memoryRepository.save(createMemory(LocalDate.of(2023, 7, 1), LocalDate.of(2023, 7, 10)));
        memoryMemberRepository.save(new MemoryMember(member, memory));
        memoryMemberRepository.save(new MemoryMember(member, memory2));

        // when
        List<MemoryMember> result = memoryMemberRepository.findAllByMemberIdAndYearOrderByCreatedAtDesc(member.getId(), 2023);

        // then
        assertAll(
                () -> assertThat(result).hasSize(2),
                () -> assertThat(Objects.requireNonNull(result).stream().map(MemoryMember::getMemory).map(Memory::getStartAt).toList())
                        .containsExactly(LocalDate.of(2023, 12, 31), LocalDate.of(2023, 7, 1))
        );
    }
```

<img width="930" alt="image" src="https://github.com/user-attachments/assets/b9f31ef1-4295-4e15-9d78-63e846166419">

2024-08-15 13:22 UTC, linirini commented on backend/src/main/java/com/staccato/StaccatoApplication.java
>  public class StaccatoApplication {
😮😮😮😮😮😮😮😮😮😮😮😮
감사합니다....해당 애너테이션까지 추가해서 테스트 올려놓겠습니다.!

2024-08-15 13:31 UTC, linirini commented on backend/src/test/java/com/staccato/memory/service/MemoryServiceTest.java
> +                .hasMessage("해당 추억 상세에 순간 기록이 남아있어 삭제할 수 없습니다.");
이번 이슈에서 다룰 내용은 아니라서 일단 두었습니다! 삭제 API 수정 시 삭제 예정입니다:)

2024-08-15 13:35 UTC, linirini commented on backend/src/test/java/com/staccato/memory/domain/MemoryTest.java
> +        assertThatCode(() -> MemoryFixture.create(LocalDate.MAX, LocalDate.MIN))
디테일한 리뷰 감사합니다!

2024-08-15 14:08 UTC, linirini commented on backend/src/test/java/com/staccato/memory/repository/MemoryMemberRepositoryTest.java
> -
랜덤으로...성공하더라고요!
아직 해결 방안을 찾지 못해서 일단은 테스트를 제외하겠습니다!

2024-08-16 02:00 UTC, Ho-Tea approved these changes

2024-08-16 02:08 UTC, merged