feat: 추억 삭제 API 수정 #221
woowacourse-teams/2024-staccato pull request #222
Opened 2024-08-15 09:39 UTC by linirini

## ⭐️ Issue Number
- #221

## 🚩 Summary
- 순간이 존재하는 경우 추억을 삭제할 수 없었던 예외 제거
- docs에 변경 사항 반영

## 🛠️ Technical Concerns

## 🙂 To Reviewer

## 📋 To Do

2024-08-15 12:39 UTC, Ho-Tea requested changes
고생하셨습니다 리니!!
사소한 코멘트 남겨드렸는데 확인 부탁드려요 🙇‍♂️

2024-08-15 12:39 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/moment/service/MomentServiceTest.java
> +                .momentId();
해당 부분은 위의 줄과 합쳐도 될 것 같아요!

2024-08-15 12:39 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/memory/service/MemoryService.java
>          });
삭제가 전파되는 부분도 추가해야 할 것 같아요!

2024-08-15 13:20 UTC, linirini commented on backend/src/main/java/com/staccato/memory/service/MemoryService.java
>          });
완전 놓치고 있었네요! 반영했습니다:)

2024-08-16 00:29 UTC, devhoya97 approved these changes
추억 삭제시 순간들이 모두 삭제되어야 한다는 점을 호티가 잘 짚어주셨네요 👍
그 외에는 문제 없어보입니다. 수고하셨습니다 :)

2024-08-16 02:01 UTC, Ho-Tea approved these changes

2024-08-16 02:30 UTC, merged