feat: 댓글 생성, 조회 API 구현 #214
woowacourse-teams/2024-staccato pull request #225
Opened 2024-08-15 13:30 UTC by devhoya97

## ⭐️ Issue Number
- #214

## 🚩 Summary
생성과 조회 API의 우선순위가 더 높음으로 둘을 묶어서 구현하였습니다.
- 댓글 생성 API 구현
- 특정 순간 기록에 속한 모든 댓글을 생성 순으로 조회하는 API 구현 

## 🛠️ Technical Concerns

## 🙂 To Reviewer

## 📋 To Do
댓글 수정, 삭제 API 구현 예정입니다.

2024-08-15 14:42 UTC, linirini requested changes
카고, 수고 많으셨어요!
이번에 리뷰할 때 커밋을 따라가면서 했기 때문에, 이미 반영한 부분에 대해서 코멘트를 남긴 부분이 있을 수도 있는데요, 가볍게 곁눈질(?) 이모지만 남겨주고 넘어가도 될 것 같아요 ㅎㅎ

2024-08-15 14:42 UTC, linirini commented on backend/src/test/java/com/staccato/comment/service/CommentServiceTest.java
> +                .hasMessageContaining("요청하신 순간 기록을 찾을 수 없어요.");
`기록`이라는 말은 없는 것이 자연스러워보입니다:)

2024-08-15 14:42 UTC, linirini commented on backend/src/main/java/com/staccato/comment/service/CommentService.java
> +        return commentRepository.save(comment).getId();
Moment와 Memory는 반환 형태를 response로 분리했는데, 일관성 있게 Comment도 CommentIdResponse를 분리하면 어떨까요?

2024-08-15 14:42 UTC, linirini commented on backend/src/test/java/com/staccato/comment/CommentControllerTest.java
> +                        "댓글은 공백 포함 1자 이상 500자 이하로 입력해주세요."
댓글 입력 없이 확인 버튼만 누르면 요청이 날라오나요?
1자 이상이라는 조건이 있길래 궁금하네요,
만약 댓글 입력 안하고 확인 버튼 누른다고 해도 저장이 안되고 사용자에게는 에러 메세지가 보이지 않는게 자연스러운 것 같아서요!
이 부분은 안드로이드 크루들과 얘기해봅시다!

2024-08-15 14:42 UTC, linirini commented on backend/src/test/java/com/staccato/comment/CommentControllerTest.java
> +                        new CommentRequest(MIN_MOMENT_ID, " "),
공백도 사용자가 충분히 의도할 수 있지 않을까요?
예를 들어 카톡도 공백으로 보내는 건 가능하니까요!

2024-08-15 14:42 UTC, linirini commented on backend/src/test/java/com/staccato/comment/CommentControllerTest.java
> +                        "댓글은 공백 포함 1자 이상 500자 이하로 입력해주세요."
어쩌면 1자 미만으로 보내는 것 자체가 가능하지 않을수도 있겠다는 생각이 드는데요!
물론 안드로이드 쪽에서의 실수로 1자 미만이 올수는 있겠죠?(ex: 빈 문자열)
하지만, 만약 이 메세지가 사용자에게 메세지가 보여질 메세지라면 `1자 이상`이라는 말이 필요하지 않을 수도 있겠다는 생각이 드네요!

2024-08-15 14:42 UTC, linirini commented on backend/src/main/java/com/staccato/comment/controller/CommentController.java
> +
코드 관련은 아니지만, 커밋 단위에 대해서 제안드리고 싶은데요!
저는 변경 파일이 많다면 커밋을 따라가면서 리뷰합니다. 그래서 테스트와 구현이 한 커밋으로 올라온다면 리뷰하기에 더 편할 것 같아요!
구현할 때에는 테스트를 먼저 작성하고, 구현을 하고
리뷰할 때에는 구현한 것을 보고, 이에 대한 테스트를 확인할 수 있다면 좋을 것 같아요!
다만, 유의할 부분이라면 구현 단위를 작게 가져가야겠죠? 
(예를 들어서, 한번에 3,4개의 테스트와 이에 해당하는 분량의 구현을 한 커밋 단위로 올리면 오히려 리뷰하기 힘들겠죠 ㅎㅎ)

2024-08-15 14:42 UTC, linirini commented on backend/src/main/java/com/staccato/comment/domain/Comment.java
> +@Table(indexes = {
👍👍👍👍
어떤 이유에서 이와 같은 인덱스를 설정했는지 너무 궁금한데요!
캠퍼스에서 공유해주세요:)

2024-08-16 05:45 UTC, devhoya97 commented on backend/src/main/java/com/staccato/comment/service/CommentService.java
> +        return commentRepository.save(comment).getId();
좋은 지적입니다! 처음에는 그렇게 하려했는데요. 예를 들어 Moment의 경우 MomentIdResponse를 만들어서 반환했던 이유는 아래와 같은 response body를 만들기 위함이었습니다.
```
{
    "momentId" : 1
}
```

하지만 호두와 이야기해보니 Comment의 경우 생성 시 id값을 받을 필요가 없더라구요(Comment가 생성되면 id값으로 특정 Comment만 조회하는게 아니라 moment에 속한 모든 Comment를 조회하는 API를 사용해서!). 그래서 아래 Controller 코드를 보시면 Moment, Memory와는 다르게 Void를 반환합니다.
```java
    @PostMapping
    public ResponseEntity<Void> createComment(
            @LoginMember Member member,
            @Valid @RequestBody CommentRequest commentRequest
    ) {
        long commentId = commentService.createComment(commentRequest, member);
        return ResponseEntity.created(URI.create("/comments/" + commentId))
                .build();
    }
```

따라서 DTO가 필요 없다고 판단해서 만들지 않았어요!

2024-08-16 05:51 UTC, devhoya97 commented on backend/src/test/java/com/staccato/comment/CommentControllerTest.java
> +                        "댓글은 공백 포함 1자 이상 500자 이하로 입력해주세요."
> 댓글 입력 없이 확인 버튼만 누르면 요청이 날라오나요?
댓글을 입력하지 않거나 공백만 입력하면 확인 버튼이 활성화되지 않는 방향으로 호두와 이야기했습니다! 

>  만약 이 메세지가 사용자에게 메세지가 보여질 메세지라면 1자 이상이라는 말이 필요하지 않을 수도 있겠다는 생각이 드네요!
동의합니다! 생각해보니 안드 측에서 실수로 빈 문자열을 보낸다고 해도, `@NotBlank`를 적용해뒀기 때문에 `댓글 내용을 입력해주세요.`라는 메시지가 뜹니다!

결론 : `1자 이상`이라는 말을 제거했습니다 :)

2024-08-16 05:54 UTC, devhoya97 commented on backend/src/test/java/com/staccato/comment/CommentControllerTest.java
> +                        new CommentRequest(MIN_MOMENT_ID, " "),
그 부분도 호두와 이야기해보았는데요, 카톡을 확인해보니 공백만 넣었을 때는 보내기 버튼이 활성화되지 않더라구요! 그래서 공백만 보내는 것은 불가능하게 만들었습니다!

2024-08-16 06:00 UTC, devhoya97 commented on backend/src/main/java/com/staccato/comment/controller/CommentController.java
> +
오오 동의합니다! 사실 지금까지는 커밋을 따라가면서 리뷰를 해본 적이 없어서 커밋 단위를 막 했던 것 같아요. 이 코멘트를 보고 리니처럼 커밋을 따라서 리뷰해보니까 커밋 메시지에서 이번 커밋의 의도를 파악할 수 있어서 훨씬 편하더라구요. 앞으로 반영해볼게요 😄

2024-08-16 06:34 UTC, Ho-Tea approved these changes
깔끔합니다 카고 고생하셨어요! 👍

2024-08-16 06:34 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/comment/service/CommentService.java
> +    public long createComment(CommentRequest commentRequest, Member member) {
생성 부분이므로 `@Transactional` 애노테이션을 붙여야 할 것 같아요!

2024-08-16 06:50 UTC, BurningFalls approved these changes
리니가 충분히 해주셔서 approve 하겠습니다. 수고하셨습니다!

충돌 해결 파이팅... 😭

2024-08-16 06:57 UTC, devhoya97 commented on backend/src/main/java/com/staccato/comment/domain/Comment.java
> +@Table(indexes = {
간략하게 남겨볼게요! 
호두와 이야기해본 결과, comment 조회는 항상 `특정 moment에 속한 모든 comment 조회`로서 이루어집니다. 따라서 comment 조회를 위한 SQL의 where절에는 항상 momentId가 들어갑니다.

하나의 moment에는 여러 개의 comment가 속할 수 있으므로 comment table의 모든 row에 대해 momentId 값을 확인해봐야 할 텐데요. momentId에 보조 인덱스를 걸어준다면 보조 인덱스로 찾아낸 클러스터형 인덱스 값들만 찾아가면 되므로 이론상 DB 성능 최적화에 큰 도움이 될 것 같아서 보조 인덱스를 걸어봤어요. 또한 comment 테이블 전체의 비율로 따져봤을 때, momentId 컬럼의 중복률도 매우 낮을 것이므로 합리적인 인덱싱이라고 판단했습니다!

TODO: 
1. 물론 이와 같이 인덱스를 걸었을 때 이득을 볼만한 상황이 다른 테이블에도 많을 것 같아요. 이는 주말에 하나씩 보며 차차 걸어보겠습니다.
2. 이론상으로는 조회 시 인덱스가 짱이고 꼭 걸어야 한다는 걸 이해는 했는데, 인덱스를 걸었을 때와 걸지 않았을 때 성능 비교를 직접 해보면 좋을 것 같아요. 나중에 시간이 된다면 dev쪽 테이블에 데이터를 다량 집어넣고 비교해보는 것도 좋겠네요!

2024-08-16 07:14 UTC, linirini approved these changes
LVGTM!!

2024-08-16 07:14 UTC, merged