fix: 일부 EditText 개행 불가 처리 및 키보드 숨김 처리 #247
woowacourse-teams/2024-staccato pull request #249
Opened 2024-08-16 08:47 UTC by Junyoung-WON

## ⭐️ Issue Number
- #247 

## 🚩 Summary
- [x] 닉네임, 추억 제목 입력 EditText의 개행 불가 처리
- [x] 키보드 활성화 상태에서 빈 화면 터치 시 키보드 숨김 처리
- [x] 코드 컨벤션에 따라 `override` 메서드 순서 재정렬

## 📋 To Do
- ~~무리하지 않기~~
- 기능 구현 파이팅하기

2024-08-18 14:15 UTC, hxeyexn requested changes
꼼꼼한 키보드 숨김 처리 너무 좋네요 👍

`MemoryCreationActivity`, `MemoryUpdateActivity`, `MomentCreationActivity`, `VisitUpdateActivity`에서 키보드 숨김 처리가 동작되지 않는 이슈가 있습니다.

위에서 언급한 화면들은 키보드 숨김 처리를 `root`가 아닌 `ScrollView` 내부의 `ConstraintLayout`에 설정하면 동작하긴 하네요! 한 번 확인해보시고 수정 부탁드리겠습니다~ 

그리고 binidng과 키보드 숨김 처리 코드에 대해 간단히 리뷰 남겨놓았습니다~
시간 되실 때 한번 확인해주시면 감사하겠습니다~

중복되는 리뷰가 많아서 `LoginActivity`와 `MemoryCreationActivity`에만 리뷰 남겨두었으니 다른 파일에도 적용해주시면 좋을 것 같아요~

고생하셨습니다!

___

> @Junyoung-WON , @s6m1n
>
>  `root`에 설정 시 키보드 숨김 동작이 실행되지 않고, `ScrollView` 내부의 `ConstraintLayout`에 설정 시 실행되는 이유에 대해서 다같이 공부해보면 좋을 것 같아요!

2024-08-18 14:15 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/memorycreation/MemoryCreationActivity.kt
> +    }
위 코멘트와 동일한 의견입니다!

2024-08-18 14:15 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/memorycreation/MemoryCreationActivity.kt
> +    }
```suggestion
        private fun hideKeyboard() {
        if (currentFocus != null) {
            inputManager.hideSoftInputFromWindow(
                currentFocus?.windowToken,
                InputMethodManager.HIDE_NOT_ALWAYS,
            )
        }
    }
```
자바와 달리 kotlin은 `this`를 생략할 수 있다는 점이 큰 장점이라고 생각해요. `this`는 생략하는 게 좋을 것 같아용!

그리고 `InputMethodManager`의 초기화는 아래와 같이 `by lazy`를 활용하는 방법을 사용해도 괜찮을 것 같은데, 호두는 이에 대해 어떻게 생각하시는 지 궁금합니다!

```kotlin
    private val inputManager: InputMethodManager by lazy {
        getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager
    }
```

2024-08-18 17:18 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/login/LoginActivity.kt
>          }
위에 제안해주신 것처럼 바인딩을 적극 활용하는 방법이 좋겠네요!! 😃  코드도 조금 더 간결해지고 관리도 수월할 것 같습니다!

다만 지금은 오류를 해결하는 과정에서, 위와 같이 바인딩을 활용하지 않고 다른 방식으로 우회하는 방법을 사용했습니다.
아무래도 기존 방식처럼 바인딩을 적극 활용하는 것이 좋은데,,
View들 간의 클릭 이벤트의 우선순위가 어떻게 되는지를 잘 알아보고, 해결방안을 찾으면 좋겠네요 😢

2024-08-18 17:27 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/login/LoginActivity.kt
>          binding.root.setOnClickListener {
우선 처음 `BindingActivity`를 활용하지 않았던 이유는, 해당 Activity가 View가 구성되어있지 않고 Login 화면과 Main 화면으로의 라우팅만을 담당하는 Activity였기 때문입니다.
SplashScreen Api를 활용하면서 Splash 화면에 대한 View를 구성하지 않아도 되었고, 내부에 저장된 토큰의 유무에 따라 LoginActivity, MainActivity를 실행하는 동작만이 필요했습니다. 그래서 BindingActivity를 활용하지 않았어요.

구현을 하던 중에 LoginActivity 안에서 라우팅 로직을 수행하는 것으로 변경하였고, 그 과정에서 BindingActivity를 활용할 생각을 못하고 구현만 이어갔네요...😅ㅎㅎ
지금은 LoginActivity를 BindingActivity로 활용해볼 수 있을 것 같네요! 리팩터링 시도해보면 좋을 것 같아요 👍

2024-08-18 17:59 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/login/LoginActivity.kt
>          binding.root.setOnClickListener {
BindingActivity를 적용하는 과정에서 Theme 설정과 관련된 오류가 나타났습니다.

> You need to use a Theme.AppCompat theme (or descendant) with this activity.

AppCompat 테마를 적용하지 않아서 나타난 오류인데, 이 경우 `LoginActivity`의 테마를 AppCompat의 테마로 변경하여야 합니다. 아무래도 BindingActivity 사용 시, AppCompatActivity와 SplashScreen의 Theme.SplashScreen 이 내부적으로 충돌을 일으키는 것 같습니다.
기존에 적용되어 있던 `Theme.SplashScreen` 을 제거하여도 스플래시 스크린은 정상적으로 나타나긴 합니다만, 안드로이드 12 버전 이상의 휴대폰에서도 구 버전의 휴대폰에서 실행시킨 것처럼, 스플래시 스크린 Api에서 제공하는 애니메이션 및 설정이 적용되지 않게 됩니다.

별개의 스플래시 스크린 애니메이션이 없다면 아무래도 공식적으로 제공해주는 스플래시 스크린의 효과를 적용하는 것이 좋을 것 같아요. 또 안드로이드에서도 공식적으로 해당 SplashScreen Api 사용을 권장하고 있기 때문에, 기존의 스플래시 스크린의 방식을 적용하는 것이 좋다고 생각합니다!

따라서 코드의 통일성을 지키지 못해 아쉽지만, LoginActivity에서는 BindingActivity를 적용하지 않는 것이 좋을 것 같아요!

2024-08-18 18:07 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/woowacourse/staccato/presentation/memorycreation/MemoryCreationActivity.kt
> +    }
너무 좋네요...!! 처음 참고했던 코드가 자바 코드여서, 그대로 긁어오다보니 자바의 흔적이 여럿 남아있네요...

추가로 `InputMethodManager`에 대해 알아보니, 하나의 Application 마다 존재하며, 싱글톤처럼 어플리케이션 전역에서 위치하여 사용된다고 합니다. 따라서 호출 시 기존에 어플리케이션에 존재하는 인스턴스를 가져오게 됩니다.

하지만 이전 코드에서는 키보드 바깥의 터치가 이루어질 때 마다 매번 `InputMethodManager` 인스턴스를 가져와 변수로서 저장하는 동작을 하므로, 불필요한 변수 설정이 이루어지는 것 같습니다.

해나가 제시한 지연 초기화 방식이 코드 가독성과 동작의 측면에서 이점이 있겠네요! 적용하여 리팩터링 해보겠습니다 👍

2024-08-19 04:37 UTC, s6m1n approved these changes
해나가 리뷰를 잘 해주셔서 저는 크게 요청드릴 부분이 없네요!
코멘트 남긴 부분만 반영해주시면 머지해도 될 것 같습니다 ㅎㅎ

2024-08-19 04:37 UTC, s6m1n commented on android/Staccato_AN/app/src/main/res/layout/activity_login.xml
>                  android:id="@+id/et_login_user_nickname"
EditText에 아래 옵션을 추가해주시면 좋을 것 같아요!
`android:imeOptions="actionDone"`
키보드의 엔터 자리에 `완료`가 뜨게 되고, 클릭 시 키보드를 내려간 상태로 바꿔줍니다 !
(Creation, Update 화면의 xml에서도 마지막 editText에 적용해주시면 좋을 것 같아요 ㅎㅎ)

2024-08-19 05:27 UTC, hxeyexn approved these changes
리뷰 잘 반영해주셨네요~ 감사합니다!!
LGTM 😎

2024-08-19 06:52 UTC, merged