feat: 하나의 사진 업로드 API 생성 #256
woowacourse-teams/2024-staccato pull request #258
Opened 2024-08-16 23:08 UTC by BurningFalls

## ⭐️ Issue Number
- #256 

## 🚩 Summary
- notion 명세에 맞추어 `/images` API 구현 및 변경
- swagger 적용

## 🛠️ Technical Concerns

## 🙂 To Reviewer

## 📋 To Do

2024-08-17 11:51 UTC, linirini requested changes
폭포, image api 분리하시느라 수고 많았어요!
로직 관련해서는 딱히 리뷰 남길만한 부분은 보이지 않았습니다!
다만, 패키지 관련해서 리뷰 남겼는데 확인해보시고, 재리뷰요청 해주세요!

2024-08-17 11:51 UTC, linirini commented on backend/src/main/java/com/staccato/image/controller/docs/ImageControllerDocs.java
> +            @Parameter(description = "업로드할 이미지 파일 (PNG, JPG, JPEG, WEBP 형식 지원, 최대 20MB",
닫는 괄호가 누락된 것 같네요!

2024-08-17 11:51 UTC, linirini commented on backend/src/main/java/com/staccato/image/domain/S3ObjectClient.java
> +package com.staccato.image.domain;
외부와의 통신을 담당하는 계층이기 때문에 Infrastucture에 해당할 것 같네요!

2024-08-17 11:51 UTC, linirini commented on backend/src/main/java/com/staccato/image/service/ImageExtension.java
> +package com.staccato.image.service;
오히려 해당 클래스가 image라는 도메인이 아닐까요?
image라는 도메인이 extension이라는 상태를 가지고, 이에 대한 검증 로직을 가지고 있다고 보이네요!

2024-08-17 13:55 UTC, devhoya97 approved these changes
S3 참 어려운데 정말 고생하셨습니다 폭포!! 👍 S3는 트랜잭션으로 관리가 불가능하니, S3 업로드에 실패했을 때 업로드 프로세스를 재시도하는 방법도 (나~중에) 고려해볼 수 있겠네요 😄

2024-08-17 13:55 UTC, devhoya97 commented on backend/src/main/java/com/staccato/image/controller/ImageController.java
> +    public ResponseEntity<ImageUrlResponse> uploadImage(@RequestPart(value = "imageFile") MultipartFile image, @LoginMember Member member) {
가독성을 위해 아래와 같이 줄바꿈할 수도 있을 것 같아요! 사소한 제안이므로 폭포가 편한대로 결정하시면 됩니다 :)
```java
    public ResponseEntity<ImageUrlResponse> uploadImage(
            @RequestPart(value = "imageFile") MultipartFile image, 
            @LoginMember Member member
    ) {
```

2024-08-17 17:29 UTC, Ho-Tea approved these changes
고생하셨습니다 폭포!!
사소한 코멘트 남겨드렸는데 확인 부탁드려요!
로직에 문제가 없다고 판단하여 `approve` 드렸습니다!

+추가로 남겨주신 고민에 대해

>현재 GlobalExceptionHandler에 모든 메서드들이 log에 erorrMessage를 담고 있는데, 클라이언트에게 주는 메시지가 아니라 실제 서버에서 나는 에러를 출력해서 원인 분석을 하는 것이 목적이라고 생각하여 e.getMessage()를 담도록 했습니다. 같이 얘기해볼 부분이라, 제가 담당한 부분만 적용하고 나머지 메서드들은 변경하지 않았습니다.
``` java
    @ExceptionHandler(MultipartException.class)
    public ResponseEntity<ExceptionResponse> handleMultipartException(MultipartException e) {
        String errorMessage = "20MB 이하의 사진을 업로드해 주세요.";

        // 방식 1 - errorMessage(클라이언트에게 보여줄 메시지)
        ExceptionResponse exceptionResponse = new ExceptionResponse(HttpStatus.PAYLOAD_TOO_LARGE.toString(), errorMessage);
        // 방식 2 - e.getMessage()(서버에서 표출한 에러 메시지)
        ExceptionResponse exceptionResponse = new ExceptionResponse(HttpStatus.PAYLOAD_TOO_LARGE.toString(), e.getMessage());

        log.warn(LogForm.EXCEPTION_LOGGING_FORM, exceptionResponse);
        return ResponseEntity.badRequest().body(new ExceptionResponse(HttpStatus.PAYLOAD_TOO_LARGE.toString(), errorMessage));
    }
```

- 에러를 출력해서 원인 분석을 하는 것이 목적이라는 말씀에 백번 동의합니다.
  - 처음에 `stacktrace`를 포함해 모든 정보를 로그에 담으려고 했습니다. -> [참고 문서](https://netmarble.engineering/observability-logging-b/)
  - 다만 `e.getMessage()와 e.getStackTrace()`를 통해 출력되는 로그의 양이 생각보다 방대해서 커스텀한 에레메세지를 로깅하는 형식으로 진행해놓은 상태입니다.
- 따라서 아래처럼 `prod` 환경과 `dev` 환경을 구분해서 에러메세지를 로깅하는 방법이 있을 것 같아요! 
  - `prod`환경에서 로깅될 내용들은 정말 필요한 로깅만 짧고 굵게 남아야 된다고 생각해서,
  - 말씀처럼 클라이언트에게 보여줄 에러 메세지 + 비교적 크지않는 정보를 담고 있는 `e.getMessage()`-> `prod` 환경
  - 서버에서 표출한 에러 메시지(`e.getMessage() + e.getStackTrace()`) + 클라이언트에게 보여줄 에러 메세지(미정)-> `dev` 환경

해당 부분에 대해서는 팀원 모두와 토의가 필요할 것 같습니다!

2024-08-17 17:29 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/image/controller/ImageController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(imageUrlResponse);
[사소한 코멘트]
다른 도메인에서 `201` 상태코드를 반환할 때 `ResponseEntity.created()`를 사용하여 해당 부분과 통일 시켜도 좋을 것 같아요!

2024-08-18 08:04 UTC, BurningFalls commented on backend/src/main/java/com/staccato/image/controller/docs/ImageControllerDocs.java
> +            @Parameter(description = "업로드할 이미지 파일 (PNG, JPG, JPEG, WEBP 형식 지원, 최대 20MB",
아 `(PNG, JPG, JPEG, WEBP)`에서 마지막 괄호가 빠져 있었네요. 확실하게 틀린 부분에 대해서는 정확하게 어느 부분이 틀렸는지도 같이 써주시면 도움이 될 것 같아요! 생각보다 찾는데 꽤 오래걸렸습니다 😓

2024-08-18 08:09 UTC, BurningFalls commented on backend/src/main/java/com/staccato/image/service/ImageExtension.java
> +package com.staccato.image.service;
그렇네요! 후에 Image 도메인도 만들어서 service의 로직을 최대한 도메인 쪽으로 이동할 계획인데, domain안에 extension 상태가 있다면 이것과도 굉장히 어울릴 것 같습니다!

2024-08-18 08:09 UTC, BurningFalls commented on backend/src/main/java/com/staccato/image/domain/S3ObjectClient.java
> +package com.staccato.image.domain;
외부 API를 직접 사용하는 계층이므로 infra가 적당하겠네요! 수정했습니다.

2024-08-18 08:11 UTC, BurningFalls commented on backend/src/main/java/com/staccato/image/controller/ImageController.java
> +    public ResponseEntity<ImageUrlResponse> uploadImage(@RequestPart(value = "imageFile") MultipartFile image, @LoginMember Member member) {
컨벤션에 맞출 시, 카고가 추천해준 방식이 맞네요! 수정했습니다.

2024-08-18 08:17 UTC, linirini approved these changes

2024-08-18 08:18 UTC, BurningFalls commented on backend/src/main/java/com/staccato/image/controller/ImageController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(imageUrlResponse);
`ResponseEntity.created(???).body(imageUrlResponse)` 이렇게 통일하려면 ??? 안에 들어갈 내용이 필요한데, 여기서는 딱히 id를 반환받고 있지 않습니다. 따라서 적절한 넣을 내용이 없다고 판단해서 다음과 같이 구현했습니다.

통일하기 위해 넣을만한 적절한 내용이 있을까요?

2024-08-18 10:13 UTC, merged