feat: 스타카토 수정 시 날짜, 장소 변경 가능하도록 수정 #353
woowacourse-teams/2024-staccato pull request #362
Opened 2024-09-10 07:37 UTC by devhoya97

## ⭐️ Issue Number
- #353 

## 🚩 Summary
- 스타카토 생성 시 현위치 기반 주소 값이 들어오고, 현재 시간 기반 날짜가 들어오도록 고정시키는데, 이제 사용자가 원하는 값으로 변경할 수 있습니다.
  - 백엔드 입장에서 스타카토 생성 API는 위 기능을 위한 변경사항이 없습니다. 
- 현재 스타카토 수정은 placeName과 image만 수정 가능합니다. 아래 필드들도 수정 가능하도록 버저닝된 API를 추가로 구현했습니다.
  - address, latitude, longitude, visitedAt, memoryId
  - 스타카토 생성 시 사용하는 dto와 수정 시 사용하는 dto의 모습이 같이졌으므로 MomentUpdateRequest 클래스를 제거했습니다.
- 버저닝 API를 구현하면서, 스타카토 수정V2에 대한 컨트롤러 메서드와 서비스 메서드가 추가되었습니다.
  - 테스트 코드는 구현이 변경됐을 때 문제가 발생하면 잡아낼 수 있어야 합니다. 따라서 속칭 V1 메서드와 코드가 매우 유사하더라도 V1, V2를 함께 배포하려면 두 메서드에 대한 테스트코드가 각각 작성되어야 한다고 생각합니다.
  - 기존 V1 테스트 코드와 구분이 잘 안가서, 기존 V1 메서드 밑에 `@Nest`를 활용해 V2 메서드를 구분했습니다.
  - V2에 대한 컨트롤러 테스트 코드는 아직 미완성 상태입니다. 리니의 컨트롤러테스트 리팩토링이 끝나면 참고해서 완성한 뒤 머지시키도록 하겠습니다!

## 🛠️ Technical Concerns

## 🙂 To Reviewer

## 📋 To Do

2024-09-11 04:36 UTC, Ho-Tea approved these changes
고생하셨습니다 카고!
간단한 코멘트 확인 부탁드려요

2024-09-11 04:36 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/moment/service/MomentService.java
> +        validateOwner(memory, member);
잘 읽히지 않는 것 같아서 `76,77` 을 하나의 메서드로 `78,79`를 하나의 메서드로 묶어 메서드 명으로 무슨일을 하는지 명확히 표현하는것은 어떨까요!

2024-09-12 01:43 UTC, linirini approved these changes
수고하셨습니다, 카고! 몇가지 궁금했던 부분과 수정  제안을 코멘트로 달아놓았습니다.
크지 않은 건들이라 approve합니다! 반영 후 merge 해주세요!
추가로,
> 스타카토 생성 시 사용하는 dto와 수정 시 사용하는 dto의 모습이 같이졌으므로 MomentUpdateRequest 클래스를 제거했습니다.

제가 이해한 바에 의하면 기존 API도 제공하기 때문에 기존 API에서는 해당 dto를 사용하는 것으로 보이는데, V2 컨트롤러와 서비스에서 해당 dto를 사용하지 않는다는 것을 의미하는게 맞을까요?

2024-09-12 01:43 UTC, linirini commented on backend/src/test/java/com/staccato/moment/service/MomentServiceTest.java
> +                    () -> assertThat(momentImageRepository.findById(2L)).isEmpty(),
이건 MomentImage의 update가 호출되었을 때 삭제가 발생하므로, MomentImage가 테스트 책임을 가지지 않을까요?

2024-09-12 01:43 UTC, linirini commented on backend/src/test/java/com/staccato/moment/service/MomentServiceTest.java
> +                            .getImageUrl()).isEqualTo("https://existExample2.com.jpg"),
이 부분까지 이미지 관련 검증들은 중복되는, 혹은 서비스의 테스트 책임이 아닌 것들이 섞여 있는 것 같아요! (개인적으로 테스트 검증 값들을 읽는데에도 시간이 많이 드는 것 같아서요!)
물론 카고가 의도를 담고, 검증하고 있는데 제가 의도를 파악하고 있지 못한 것 같아서 질문드립니다!
268에서 279사이에서 확인하고자 하는 바가 무엇인가요? "잘 저장이 된다"라면 jpa가 해주는 부분을 검증하는 것은 아닐까요? 저장되는 순서를 검증하고자 한다면, for문을 검증하는 것은 아닐까요?

2024-09-12 01:45 UTC, linirini requested changes
RC로 변경합니다.

2024-09-15 07:54 UTC, devhoya97 commented on backend/src/main/java/com/staccato/moment/service/MomentService.java
> +        validateOwner(memory, member);
잘 읽히지 않는다는 것에 동의합니다!! 제안해주신대로 메서드 분리를 시도해봤는데요, `76, 77`, `78,79`를 각각 하나의 메서드로 묶기엔 검증과 함께 리턴값이 필요한데, `76, 77`은 Moment 타입을 리턴해야 하고, `78, 79`는 Memory 타입을 리턴해야 해서 생각했던 것보다 복잡해지는 것 같아요.

오히려 아래와 같이 기존 `validateOwner`라는 메서드명과 memory 변수명을 바꾸면 어느정도 잘 읽힌다고 생각하는데 어떻게 생각하시나요?!
```java
    @Transactional
    public void updateMomentByIdV2(
            long momentId,
            MomentRequest momentUpdateRequest,
            Member member
    ) {
        Moment moment = getMomentById(momentId);
        validateMemoryOwner(moment.getMemory(), member);
        
        Memory targetMemory = getMemoryById(momentUpdateRequest.memoryId());
        validateMemoryOwner(targetMemory, member);
        
        Moment updatedMoment = momentUpdateRequest.toMoment(targetMemory);
        moment.update(updatedMoment);
    }
```

2024-09-15 08:02 UTC, devhoya97 commented on backend/src/main/java/com/staccato/moment/service/MomentService.java
> +        Moment updatedMoment = momentUpdateRequest.toMoment(memory);
> 제가 이해한 바에 의하면 기존 API도 제공하기 때문에 기존 API에서는 해당 dto를 사용하는 것으로 보이는데, V2 컨트롤러와 서비스에서 해당 dto를 사용하지 않는다는 것을 의미하는게 맞을까요?

넵 맞습니다! MomentUpdateRequest는 V2에서 사용하지 않겠다는 얘기를 `제거했다`고 잘못 표현했네요😅

***

> 변수명은 타입명을 따라가는 것이 가독성이 더 좋을 것이라고 생각하는데, 카고는 어떻게 생각하시나요?

그렇네요. 버저닝이 없는 시점에서는 변수명에 의도를 담는 것도 괜찮다고 생각하는데, 현재와 같이 MomentUpdateRequest라는 DTO 클래스가 존재하는 상황에서는 리니의 말에 동의합니다! 반영했습니다 :)

2024-09-15 08:14 UTC, devhoya97 commented on backend/src/test/java/com/staccato/moment/controller/MomentControllerTest.java
> +                    + "}";
> dto 형식 관련 테스트는 성공 테스트에서 진행하는 식으로 리팩터링 하고 있어요!

리니 코드 보고 이해했습니다! 실패 테스트에서는 DTO 형식을 테스트할 필요가 없으므로 objectMapper를 사용하는 방식으로 변경했습니다 :)

2024-09-15 08:33 UTC, devhoya97 commented on backend/src/test/java/com/staccato/moment/service/MomentServiceTest.java
> +                    () -> assertThat(momentImageRepository.findById(2L)).isEmpty(),
메서드 호출 관계는 다음과 같은데요.
MomentService.updateMomentByIdV2() -> Moment.update() -> MomentImages.update()

MomentServiceTest 입장에서는 만약 MomentService.updateMomentByIdV2()가 변경돼서 Moment.update()를 호출하지 않으면 예외가 발생해야 하니까, Moment.update()를 정말 호출하는지도 테스트 관심 범위에 포함될 것 같아요.

그런데 말씀하신대로 Moment.update()가 MomentImages.update()를 호출하는지는 MomentTest의 관심영역이지 MomentServiceTest의 관심영역은 아닐 수 있겠네요. 

그럼 혹시 리니는 위 테스트 코드의 then 절에서 어떤 걸 테스트해야 한다고 생각하시나요?!

2024-09-15 08:51 UTC, devhoya97 commented on backend/src/test/java/com/staccato/moment/service/MomentServiceTest.java
> +                            .getImageUrl()).isEqualTo("https://existExample2.com.jpg"),
바로 직전 코멘트에서 나눈 얘기와 어느정도 관련이 있는데요, MomentServiceTest의 관심사가 어디까지 인지 결정하는게 생각보다 헷갈리네요. 

"여기서 테스트하는 기능은 old1, old2 이미지를 가진 Moment가 new1, new2를 갖도록 수정하면, old1, old2는 삭제되고 new1, new2가 저장된다" 인데요. 제 생각에는 MomentImagesTest에서 momentImages.update()로 발생할 수 있는 다양한 시나리오를 테스트한다면, 이를 활용하는 MomentServiceTest에서는 하나의 시나리오만 테스트하면 된다고 생각했어요. 만약 하나의 시나리오도 제대로 테스트 하지 않으면 MomentServiceTest가 MomentImages를 정말 잘 활용하고 있는지 검증할 수 없는 것 같기도 하구요.

직전 코멘트와 같은 질문을 드려야 할 것 같은데, 혹시 리니는 위 테스트 코드의 then 절에서 어떤 걸 테스트해야 한다고 생각하시나요?!

2024-09-15 19:52 UTC, linirini commented on backend/src/test/java/com/staccato/moment/service/MomentServiceTest.java
> +                    () -> assertThat(momentImageRepository.findById(2L)).isEmpty(),
MomentImages.update(): 기존의 이미지를 제거하고, 새로운 이미지를 추가하는 것의 검증 책임
    -> 266-274의 검증 책임이 여기에 있다고 생각해요! 그리고 `findAll()`과 같은 메서드로 해당 이미지 url들을 contains/doesNotContains 하는지를 검증할 것 같습니다! 잘 저장되었는지가 궁금한 것이라면 구체적인 ID로 찾아올 필요는 없을 것 같다고 생각했어요:)
Moment.update(): Image 포함 모든 필드의 값이 갱신 되었는지를 검증하는 책임
    -> 따라서, 이미지 없음 to 이미지 1장 추가와 같이 최대한 간단하게 `MomentImages.update()`의 호출 여부를 판단하려고 시도할 것 같아요!
MomentService.updateMomentByIdV2(): 발생하는 예외 + moment.update() 호출 여부를 검증하는 책임
    -> 마찬가지로, moment.update()의 호출 여부를 검증하는 것에 모든 필드가 수정될 필요는 없을 것 같아요! 따라서, 필드 하나 정도로도 moment.update()의 호출 여부를 판단하기에는 충분할 것이라고 생각합니다!

2024-09-15 19:54 UTC, linirini commented on backend/src/test/java/com/staccato/moment/service/MomentServiceTest.java
> +                            .getImageUrl()).isEqualTo("https://existExample2.com.jpg"),
위의 코멘트에서도 말씀드렸지만, MomentImages.update()에서 발생 가능한 시나리오를 모두 테스트했다면, momentImages.update()가 본인의 책임을 다했다고 믿어야 한다고 생각해요! MomentServiceTest에서 하나의 시나리오만 테스트를 한다는 것은 결국 잘 호출했는지를 보고 싶다는 것 같은데요, 잘 호출되었는지 여부를 판단하는데에 현 테스트에서처럼 복잡한 테스트 데이터를 사용하지 않아도 된다고 생각했습니다!

2024-09-15 19:57 UTC, linirini approved these changes
카고, 리뷰 반영하시느라 수고하셨습니다:)
코멘트 반영된 것은 확인하였고, 남겨주신 질문에 대해선 답변 남겨두었습니다!
저의 개인적인 의견이므로 무조건 반영하실 필요는 없습니다!
따라서, 이만 approve 남깁니다! 🙌

2024-09-16 12:27 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/moment/service/MomentService.java
> +        validateOwner(memory, member);
`targetMemory`로 명명하니까 훨씬 나은 것 같습니다!

2024-09-18 10:23 UTC, devhoya97 commented on backend/src/test/java/com/staccato/moment/service/MomentServiceTest.java
> +                            .getImageUrl()).isEqualTo("https://existExample2.com.jpg"),
리니의 답변을 보고 곰곰이 생각해봤는데, 리니의 의견이 맞는 것 같아요. 반영했습니다!
앞으로 테스트 코드를 짤 때는 `각 테스트 클래스에서 검증하고자 하는 바를 명확히하자`는 관점으로 접근해봐야겠습니다! 

항상 헷갈리는 부분이었는데, 리니의 의견을 자세하게 공유해줘서 고맙습니다😄

2024-09-18 10:25 UTC, merged