refactor: 테스트 리팩터링 #349
woowacourse-teams/2024-staccato pull request #370
Opened 2024-09-12 06:55 UTC by linirini

## ⭐️ Issue Number
- #349 

## 🚩 Summary
- 무의미한 모킹 제거
- 반복되는 요청에 대한 픽스처 분리
- 각 dto에 대해 성공 테스트에서 한 번씩 String 형태로 넘겨줘서 필드명이나 값 매핑의 휴먼 에러 검증

## 🛠️ Technical Concerns

## 🙂 To Reviewer

## 📋 To Do

2024-09-14 12:29 UTC, Ho-Tea requested changes
고생하셨습니다 리니👍!
`Fixture`로 분리하니 훨씬 가독성이 좋네요
코멘트 몇개 달아놓았으니 확인 부탁드려요! 🙇‍♂️

+) 질문 : 현재 `RequestPart`를 사용하여 이미지를 받는 부분에서 이미지 업로드 개수를 5개만 받게 하는 검증 로직은 안드로이드 측에서 처리하기에 현재 코드에서는 제외된 상태인거죠?

2024-09-14 12:29 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java
>          ExceptionResponse exceptionResponse = new ExceptionResponse(HttpStatus.BAD_REQUEST.toString(), "댓글 식별자는 양수로 이루어져야 합니다.");
정상응답값을 검증할 때는 `json`으로 검증하는 것과 다르게 예외응답값을 검증할 때에는 객체를 넣어 비교하는 이유가 있을까요?
아래와 같이 `Fixture` 객체를 이용할 수 있을 것 같아요!


``` java
String exception = ExceptionResponseFixture.create(HttpStatus.BAD_REQUEST, "스타카토 식별자는 양수로 이루어져야 합니다.");
```

2024-09-14 12:29 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/moment/controller/MomentControllerTest.java
> +                        .content(objectMapper.writeValueAsString(momentRequest)))
다른 테스트와 다르게 json 형식으로 표현하지 않은 이유가 있을까요?

2024-09-15 07:36 UTC, devhoya97 approved these changes
수정해야 하는 코드량이 상당했는데, 정말 수고하셨습니다 리니 👍
간단한 코멘트 남겼는데 확인 부탁드릴게요 😄

2024-09-15 07:36 UTC, devhoya97 commented on backend/src/test/java/com/staccato/memory/controller/MemoryControllerTest.java
> +                            "memoryId": null,
컨트롤러 테스트에서 우리가 검증하고자 하는 주요 포인트는 `필드명`이므로, memoryId 값을 억지로 셋팅하기보다 null로서 검사하는 방향이 유연하고 좋아보입니다 👍

2024-09-15 07:36 UTC, devhoya97 commented on backend/src/test/java/com/staccato/moment/controller/MomentControllerTest.java
> +    void createMomentWithValidRequest() throws Exception {
아래와 같이 MomentRequest 클래스에 사진은 5장까지만 가능하다는 검증이 있으므로, 생성 성공 테스트에서 사진 5장을 넣어보는 것도 좋아보이는데 어떻게 생각하시나요?!
```java
        @ArraySchema(
                arraySchema = @Schema(example = "[\"https://example.com/images/namsan_tower.jpg\", \"https://example.com/images/namsan_tower2.jpg\"]"))
        @Size(max = 5, message = "사진은 5장까지만 추가할 수 있어요.")
        List<String> momentImageUrls
```

2024-09-15 07:36 UTC, devhoya97 commented on backend/src/test/java/com/staccato/moment/controller/MomentControllerTest.java
> -    @DisplayName("사진이 5장을 초과하면 스타카토 생성에 실패한다.")
해당 테스트를 제거한 이유가 궁금합니다!

2024-09-15 18:48 UTC, linirini commented on backend/src/main/java/com/staccato/auth/service/dto/request/LoginRequest.java
> +        @NotNull(message = "닉네임을 입력해주세요.")
3번의 이유로 `@NotNull`로 바꿨다기보다는 `@NotBlank`와 `@Size` 사이의 우선 순위가 보장되지 않아서 클라이언트쪽에 같은 상황에 대해서 매번 다른 메세지가 전달될 가능성이 존재하기 때문에 `@NotNull`로 변경하였습니다.

추천해주신 방법의 경우 검증 로직이 분산된다는 점과 다른 dto와 일관되지 않은 방법으로 null 검증을 하게되므로, 혼돈을 줄 수 있을 것 같아 우선은 기존 방법대로 유지했습니다!

2024-09-15 18:51 UTC, linirini commented on backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java
>          ExceptionResponse exceptionResponse = new ExceptionResponse(HttpStatus.BAD_REQUEST.toString(), "댓글 식별자는 양수로 이루어져야 합니다.");
예외 같은 경우 전역적으로 사용되기 때문에 특정 컨트롤러 테스트에 종속되는 검증 책임이 아니라고 판단했습니다.
따라서 말씀하신 ErrorResponseFixture 같은 경우, 사용하는 곳이 없기 때문에 제거했습니다!

2024-09-15 18:54 UTC, linirini commented on backend/src/test/java/com/staccato/moment/controller/MomentControllerTest.java
> +    void createMomentWithValidRequest() throws Exception {
5장까지 추가 가능한지 검증하는 로직은 momentImages에 있습니다.
따라서, Controller의 테스트 책임이 아닌 momentImages 일급 컬렉션의 테스트 로직이라고 생각해서 말씀하신 부분은 해당 클래스의 테스트에 추가했습니다!

2024-09-15 19:00 UTC, linirini commented on backend/src/test/java/com/staccato/moment/controller/MomentControllerTest.java
> -    @DisplayName("사진이 5장을 초과하면 스타카토 생성에 실패한다.")
[여기](https://github.com/woowacourse-teams/2024-staccato/pull/370/files/54dc5ef2002a700be703f3d0f699a51d480c4ca8#r1760268192)에서 말씀드린 것 과 같은 이유입니다.
5장을 초과할 경우, 예외가 발생하는 책임은 `momentImages`에 있기 때문에, 컨트롤러 단위 테스트의 책임이 아니라고 판단하여 제거했습니다.

2024-09-15 19:02 UTC, linirini commented on backend/src/test/java/com/staccato/moment/controller/MomentControllerTest.java
> +                        .content(objectMapper.writeValueAsString(momentRequest)))
dto 형식에 대한 테스트는 각 dto가 사용되는 곳의 성공 테스트에서만 한 번 검증합니다.
지난 코어 타임에서 함께 논의했을 때 카고가 말했듯, 같은 dto를 여러번 검증하는 것은 불필요하다고 판단했습니다.
또한, dto 형식 오류로 테스트가 실패한다면 실패 지점이 너무 많아지며 실제로 테스트에서 검증하고자 하는 목적을 가릴 여지가 있다고 생각했습니다.

2024-09-16 06:56 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java
>          ExceptionResponse exceptionResponse = new ExceptionResponse(HttpStatus.BAD_REQUEST.toString(), "댓글 식별자는 양수로 이루어져야 합니다.");
특정 컨트롤러 테스트에 종속되는 검증의 경우에는 반환 객체로부터의 직렬화가 의도된 형식으로 수행되는지 확인하기 위해 `json`으로 구성,
전역적으로 사용되는 경우 `json`으로 직렬화가 이루어지는 부분에 대한 책임은 해당 컨트롤러가 수행하는것이 아니기 때문에 일반 객체로 구성이라고 이해했습니다!

+) 그렇다면 전역적으로 예외를 반환하는 `ControllerAdvice` 부분에 대해 직렬화가 정상적으로 이루어지는지 테스트해야하나? 라는 생각이 순간 들었지만, 필요에 의한 테스트가 아닌 테스트를 위한 테스트라고 생각되었습니다

2024-09-16 11:13 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/moment/controller/MomentControllerTest.java
> +                        .content(objectMapper.writeValueAsString(momentRequest)))
같은 `DTO`를 여러번 원하는 형태로 역직렬화가 잘 이루어지는 지 검증하는 것은 불필요하다고 이해했습니다.
한 클래스 내에서 어느 테스트는 `json` 형식, `DTO` 형식으로 테스트를 수행하는 것이 나중에 혼란을 유도할 수 있다고 생각됩니다.
아래 2가지 방안이 생각이 났는데 확인 부탁드려요!

> 꼭 2가지 방안 중 하나를 택하자는 의도는 아니였지만.. 제가 헷갈렸기에 말씀드리는 겁니다 하하 😅

- 테스트 메서드 설명에서 해당 테스트 메서드가 json 으로 검증하는 이유를 추가
- DTO가 역직렬화, 직렬화가 되는지 새로운 테스트 구성

2024-09-16 11:28 UTC, Ho-Tea approved these changes
고생하셨습니다 리니!!
변경사항들 확인했고, 코멘트도 확인 했습니다!
많은 양의 코드를 리팩토링하느라 정말 수고하셨습니다 👍👍👍

리니가 구성하면서 변경된 사항은 아니지만 테스트 쪽 코드여서 밑의 내용도 같이 반영해주시면 감사하겠습니다 🙇‍♂️
- `.content(objectMapper.writeValueAsString(memoryRequest).getBytes()))` 로 구성된 부분을 `.content(objectMapper.writeValueAsString(memoryRequest))` 로 변경
``` java

    @DisplayName("적합한 경로변수와 데이터를 통해 스타카토 수정에 성공한다.")
    @ParameterizedTest
    @MethodSource("memoryRequestProvider")
    void updateMemory(MemoryRequest memoryRequest) throws Exception {
        // given
        long memoryId = 1L;
        when(authService.extractFromToken(anyString())).thenReturn(MemberFixture.create());

        // when & then
        mockMvc.perform(put("/memories/{memoryId}", memoryId)
                        .header(HttpHeaders.AUTHORIZATION, "token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(memoryRequest))) // 해당 부분
                .andExpect(status().isOk());
    }

    @DisplayName("사용자가 잘못된 형식으로 정보를 입력하면, 추억을 수정할 수 없다.")
    @ParameterizedTest
    @MethodSource("invalidMemoryRequestProvider")
    void failUpdateMemory(MemoryRequest memoryRequest, String expectedMessage) throws Exception {
        // given
        long memoryId = 1L;
        when(authService.extractFromToken(anyString())).thenReturn(MemberFixture.create());
        ExceptionResponse exceptionResponse = new ExceptionResponse(HttpStatus.BAD_REQUEST.toString(), expectedMessage);

        // when & then
        mockMvc.perform(put("/memories/{memoryId}", memoryId)
                        .header(HttpHeaders.AUTHORIZATION, "token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(memoryRequest))) // 해당 부분
                .andExpect(status().isBadRequest())
                .andExpect(content().json(objectMapper.writeValueAsString(exceptionResponse)));
    }

    @DisplayName("적합하지 않은 경로변수의 경우 추억 수정에 실패한다.")
    @Test
    void failUpdateMemoryByInvalidPath() throws Exception {
        // given
        long memoryId = 0L;
        when(authService.extractFromToken(anyString())).thenReturn(MemberFixture.create());
        ExceptionResponse exceptionResponse = new ExceptionResponse(HttpStatus.BAD_REQUEST.toString(), "추억 식별자는 양수로 이루어져야 합니다.");
        MemoryRequest memoryRequest = MemoryRequestFixture.create(LocalDate.of(2023, 7, 1), LocalDate.of(2023, 7, 10));

        // when & then
        mockMvc.perform(put("/memories/{memoryId}", memoryId)
                        .header(HttpHeaders.AUTHORIZATION, "token")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(memoryRequest))) // 해당 부분
                .andExpect(status().isBadRequest())
                .andExpect(content().json(objectMapper.writeValueAsString(exceptionResponse)));
    }
```

2024-09-16 11:28 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java
현재 `commentUpdateRequest`에서는 `meomentId` 필드가 없는것으로 확인되어 삭제 부탁드려요!

2024-09-16 16:30 UTC, linirini commented on backend/src/test/java/com/staccato/moment/controller/MomentControllerTest.java
> +                        .content(objectMapper.writeValueAsString(momentRequest)))
테스트명을 분명하게 작성하는 방향으로 수정했습니다:)

2024-09-16 16:34 UTC, merged