feat: 이전 기록 불러오기 API 구현 #374
woowacourse-teams/2024-staccato pull request #379
Opened 2024-09-19 11:18 UTC by linirini

## ⭐️ Issue Number
- #374 

## 🚩 Summary
- 중복 닉네임 허용 코드 제거
- Member domain에 `code` 필드 추가
- Member를 처음 등록할 때 UUID 발급
- UUID로 Member 조회해서 토큰 발급하는 API 구현
- DB에 필드 추가

## 🛠️ Technical Concerns

## 🙂 To Reviewer

## 📋 To Do
- 고유 코드로 사용자 이전 정보 불러오기가 가능해지면, 더 이상 staccatoAdmin 관련 코드가 필요 없어진다. 후에 반영!

2024-09-20 02:15 UTC, BurningFalls requested changes
flyway까지 적용하느라 고생많으셨습니다, 리니!

몇 가지 제안 남겼으니 확인해주세요~

2024-09-20 02:15 UTC, BurningFalls commented on backend/src/main/java/com/staccato/member/domain/Member.java
> +                .build();
UUID가 중복될 가능성이 매우 낮지만 0은 아니므로, 아래와 같은 로직을 사용해서 5번 정도 시도해서 최대한 중복되지 않게 만드는 방법도 좋을 것 같아요!

```java
public class AuthService {
    private static final int MAX_ATTEMPTS = 5;

    private Member createMember(LoginRequest loginRequest) {
        String uuid = generateUniqueUuid();
        Member member = loginRequest.toMember(uuid);
        validateNickname(member.getNickname());
        return memberRepository.save(member);
    }

    private String generateUniqueUuid() {
        for (int attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
            String uuid = UUID.randomUUID().toString();
            if (!memberRepository.existsByCode(uuid)) {
                return uuid;
            }
        }

        throw new StaccatoException("회원 가입 시 문제가 발생했습니다. 잠시 후 다시 시도해 주세요.");
    }
}
```

```java
public interface MemberRepository extends JpaRepository<Member, Long> {
    boolean existsByCode(String code);
}
```

2024-09-20 02:15 UTC, BurningFalls commented on backend/src/main/resources/application-stage.yml
> +    baseline-on-migrate: true
### `baseline-on-migrate`

`baseline-on-migrate` 옵션은 데이터베이스가 이미 존재하지만 Flyway로 관리되지 않은 기존 데이터베이스에서 마이그레이션을 시작할 때 사용된다.

* 옵션 값: true
  - Flyway는 데이터베이스에 flyway_schema_history 테이블이 없거나, 초기 상태의 데이터베이스에서 마이그레이션을 시도할 때, 자동으로 baseline을 수행한다.
  - 지정된 baselineVersion (기본값은 1)을 기준으로 데이터베이스의 현재 상태를 초기화한다. 즉, 해당 버전을 기준으로 이후의 마이그레이션 파일들을 적용한다.
* 옵션 값: false
  - Flyway는 flyway_schema_history 테이블이 없는 데이터베이스에서 마이그레이션을 시도하면 에러가 발생한다. 데이터베이스가 초기화되어 있지 않다고 판단하기 때문이다.

2024-09-20 02:15 UTC, BurningFalls commented on backend/src/main/resources/db/migration/V4__add_member_code.sql
> +    MODIFY COLUMN code VARCHAR(36) NOT NULL UNIQUE;
제가 고친 부분인데 endline 추가를 깜빡했네요. 😓  혹시 한 번에 해주실 수 있나요?

2024-09-20 02:40 UTC, linirini commented on .github/workflows/backend-ci-cd-dev.yml
>      branches: [ "develop-be", "develop" ]
네, flyway 테스트 중이라서 우선은 트리거를 열어놓을 예정입니다.

2024-09-20 02:43 UTC, linirini commented on backend/src/main/java/com/staccato/auth/service/AuthService.java
> +        validateNickname(member.getNickname());
저희는 UUID가 아닌, 닉네임으로 사용자를 판별합니다.
UUID는 사용자가 이전 기록을 불러오기 위해 제공해주는 코드로 사용하고자 추가된 값이고, 사용자가 본인을 판단할 때 사용하는 것은 닉네임이라고 생각합니다.
그렇기 때문에, 사용자가 중복 닉네임을 사용할 수 없도록 하는 것이 좋다고 생각해요.
후에, 함께하는 사람 기능이 추가된다면, UUID로 사용자를 찾는 것이 더 불편할 것 같다고 생각합니다

2024-09-20 02:47 UTC, linirini commented on backend/src/main/java/com/staccato/member/domain/Member.java
> +                .build();
create()라는 정적 메서드는 멤버를 새로 생성한다는 의미에서 만든 메서드입니다.
code는 사용자가 처음 생성되는 순간에 발급될 코드입니다. 
따라서, 해당 코드가 어떻게 생성될지를 결정하는 주체는 `Member`라고 생각합니다. 
제가 느끼기에는 어떻게 코드를 발급할 것인지를 외부에서 결정하게 되면 코드가 분산되어있게 되고, 변경 지점이 많아진다고 생각하는데 폭포는 어떻게 생각하시나요?

2024-09-20 02:51 UTC, linirini commented on backend/src/main/java/com/staccato/member/domain/Member.java
> +                .build();
> 매 초 10억개의 uuid를 100년에 걸쳐서 생성할 때 단 하나의 uuid가 중복될 확률은 50%이다.

UUID가 중복될 가능성은 정말 희박한데요,
이 가능성을 고려하기 위해 User 테이블의 모든 레코드를 5번씩(최소 1번) 순회하는 것이 꼭 필요할까요?🤔

2024-09-20 04:34 UTC, BurningFalls commented on backend/src/main/java/com/staccato/member/domain/Member.java
> +                .build();
> UUID가 중복될 가능성은 정말 희박한데요,
이 가능성을 고려하기 위해 User 테이블의 모든 레코드를 5번씩(최소 1번) 순회하는 것이 꼭 필요할까요?🤔

생각해보니 매우 희박한 확률을 방지하기 위해 비용이 큰 쿼리를 매번 사용하는 것은 오버헤드가 너무 큰 것 같네요. 차라리 UUID를 만들 때 시스템 고유값을 섞어서 중복을 줄이는 방법이 훨씬 나은 것 같습니다.

```java
public String generateTimeBasedUUID(String name) {
    return UUID.nameUUIDFromBytes((name + System.currentTimeMillis()).getBytes()).toString();
}
```

2024-09-20 04:57 UTC, BurningFalls commented on backend/src/main/java/com/staccato/member/domain/Member.java
> +                .build();
> create()라는 정적 메서드는 멤버를 새로 생성한다는 의미에서 만든 메서드입니다. code는 사용자가 처음 생성되는 순간에 발급될 코드입니다. 따라서, 해당 코드가 어떻게 생성될지를 결정하는 주체는 `Member`라고 생각합니다. 제가 느끼기에는 어떻게 코드를 발급할 것인지를 외부에서 결정하게 되면 코드가 분산되어있게 되고, 변경 지점이 많아진다고 생각하는데 폭포는 어떻게 생각하시나요?

처음에 Member가 본인의 필드를 직접 생성해서 대입하고 있어 어색하게 느꼈습니다. 하지만 리니 의견을 듣고 다시 생각해서, 초기값을 설정해준다는 느낌으로 코드를 조금 바꿔보니 그렇게 어색하게 느껴지지 않게 되었습니다. 저도 평소에 아래와 같은 코드를 많이 쓰는 것 같구요. 

```java
public Member(String nickname, String imageUrl) {
    this.nickname = new Nickname(nickname);
    this.imageUrl = imageUrl;
    this.code = UUID.randomUUID().toString();
}
```

이렇게 관점을 바꿔 생각해보니, UUID 생성 로직이 변경되더라도 그냥 Member 객체가 해당 UUID 생성 메서드를 private으로 갖고 있으면 될 것 같다는 생각이 들었습니다. 좋은 의견 감사합니다.

2024-09-21 13:22 UTC, Ho-Tea approved these changes
수고하셨습니다 리니!
테스트 코드까지 깔끔하게 구성하셨네요 👍
사소한 코멘트 남겨드렸는데 확인 부탁드려요!

2024-09-21 13:22 UTC, Ho-Tea commented on backend/src/main/resources/logback-spring.xml
> +        </root>
`Dev` 환경에서 기록되는 로그들을 모니터링 도구를 통해 확인하는 것과는 별개로 
추가적으로 콘솔에도 로그가 남게하신 이유가 있을까요?

2024-09-24 01:42 UTC, BurningFalls approved these changes

2024-09-24 04:29 UTC, devhoya97 approved these changes
로직 검토해봤는데 문제 없을 것 같습니다! 수고하셨습니다👍

2024-09-24 04:29 UTC, devhoya97 commented on backend/src/main/resources/application-prod.yml
> +    enabled: false
prod환경은 false로 설정한 이유가 있나요?!

2024-09-24 15:29 UTC, linirini commented on backend/src/main/resources/application-prod.yml
> +    enabled: false
운영 서버에서 flyway를 사용하는 것은 아직 더 고민해볼 필요가 있는 것 같아서 우선은 비활성화했습니다. 같이 의논해보면 좋을 것 같아요🙌

2024-09-24 15:29 UTC, linirini commented on backend/src/main/java/com/staccato/auth/service/AuthService.java
> +                .orElseThrow(() -> new StaccatoException("유효하지 않은 코드입니다. 올바른 코드인지 확인해주세요."));
고민되네요🤔

2024-09-24 15:34 UTC, linirini commented on backend/src/main/java/com/staccato/member/domain/Member.java
> +                .build();
> 생각해보니 매우 희박한 확률을 방지하기 위해 비용이 큰 쿼리를 매번 사용하는 것은 오버헤드가 너무 큰 것 같네요. 차라리 UUID를 만들 때 시스템 고유값을 섞어서 중복을 줄이는 방법이 훨씬 나은 것 같습니다. 다만, 리니가 말씀해주신대로 중복 가능성이 정말 희박하기 때문에 굳이 아래처럼 고칠 필요는 없다고 생각합니다.

이 부분은 적용하려면 현재 DB 필드의 길이 제한을 수정해야될 것 같아요! 팀원들 다같이 한 번 의논해보고 적용해보죠!

2024-09-25 07:49 UTC, merged