feat: 사용자 프로필 사진 수정 API 구현 #376
woowacourse-teams/2024-staccato pull request #380
Opened 2024-09-20 02:28 UTC by linirini

## ⭐️ Issue Number
- #376

## 🚩 Summary
- 사용자의 프로필 사진을 수정하는 API 구현

## 🛠️ Technical Concerns

## 🙂 To Reviewer

## 📋 To Do

2024-09-24 02:41 UTC, BurningFalls requested changes
수고하셨습니다, 리니! 남긴 코멘트 한 번씩 확인 부탁드립니다.

2024-09-24 15:55 UTC, linirini commented on backend/src/main/java/com/staccato/member/controller/docs/MemberControllerDocs.java
> +    })
해당 컨트롤러에서 발생 가능한 예외는 ApiResponse로 추가해주지 않아도 자동으로 명세에는 표시가 됩니다. 
400처럼 특정 API에서 해당 에러가 발생하는 상황이 매번 다르다면 ControllerDocs 상에서 발생 가능한 상황을 명세해주고 있었죠!
하지만, 401과 같이 항상 같은 이유로 발생하는 예외의 경우, GlobalExceptionHandler에서 명세를 작성해주고 있었어요!
413도 401과 같이 고정된 이유(이미지 용량 초과)로 발생하는 예외이기 때문에, 명시하지 않았었어요!
이와 같이 처리한다면, 일관된 명세 설명을 제공할 수 있고 코드 상에서도 중복되는 코드를 줄일 수 있기 때문에 이점이 있다고 생각했어요.
다만, GlobalExceptionHandler 쪽에 명세가 작성되어 있지 않아서 
`@ApiResponse(description = "20MB 초과의 사진을 업로드 하려고 할 때", responseCode = "413")`를 해당 클래스에 추가했습니다. 
그래서 코드 일관성을 위해 ImageController 쪽에서도 제거 해줬습니다!
추가적으로, **같은 responseCode로 중복으로 ApiResponse를 작성하는 것은 불가능합니다!**
imageController 명세에서 400 Response를 여러번 선언하고 있는 것을 발견해서 해당 부분도 다른 docs와 동일한 방식으로 통일 시켰습니다.

2024-09-24 16:10 UTC, linirini commented on backend/src/main/java/com/staccato/member/controller/MemberController.java
> +    public ResponseEntity<MemberProfileResponse> changeProfileImage(
우선, PATCH는 멱등성을 보장하지 않기도 하고, 데이터의 일부분을 수정할 때 사용하는 메서드이기 때문에 적합하지 않다고 생각해요.
Post와 put 중 뭐가 좋을지는 고민이 되네요.
요청은 새로운 이미지 혹은 아무런 이미지도 없는 것으로 요청이 날라온다는 점에서 feeling API와 유사하다는 생각이 들어서 이와 같이 설정했는데요,,
feeling API와 함께 이 부분에 대해서 의논해보면 좋을 것 같습니다!

2024-09-25 02:05 UTC, devhoya97 requested changes
간단한 리뷰 남겼습니다! 확인 부탁드릴게요 :)

2024-09-25 02:05 UTC, devhoya97 commented on backend/src/main/java/com/staccato/member/service/MemberService.java
> +        validate(member, target);
위 코멘트에서 언급드린 내용처럼 memberId를 굳이 받지 않고 Member만 받아서 member.updateImage()를 호출하면 getMemberById()와 validate() 과정이 필요 없을 것 같습니다!

2024-09-25 02:55 UTC, Ho-Tea requested changes
고생하셨습니다 리니!
사소한 코멘트 남겨드렸는데 확인부탁드려요!!

2024-09-25 02:55 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/auth/controller/AuthController.java
> +
지난번에 공유드린 `StaccatoStyle.xml` 적용 시 해당 개행들은 사라질 것 같습니다!

2024-09-25 02:55 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/member/controller/MemberController.java
> +    @PostMapping(path = "/{memberId}/profiles/images", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
동의합니다.
`@LoginMember Member member`를 통해 사용자 정보가 전달되기에 경로의 계층을 두어 표현하지 않아도 될 것 같아요
`Post /members/profile` 로 가능할 것 같아요!

2024-09-25 02:55 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/member/controller/MemberController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(memberProfileResponse);
수정한다는 API 명세에 맞게 `OK`는 어떨까요?

2024-09-25 02:55 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/member/controller/MemberController.java
> +        MemberProfileResponse memberProfileResponse = memberService.changeProfileImage(member, memberId, imageUrlResponse.imageUrl());
컨트롤러 측에서 비즈니스 로직의 순서를 알게된다는 것이 어색하기는 합니다만,
하나의 서비스로 묶게되면 외부 API 호출 부분과 디비 커넥션 부분이 하나의 트랜잭션으로 묶이게 되어 꽤 오랜 시간 커넥션을 물고있을 수 있다는 문제로 인해 이렇게 구성된것이라 생각됩니다.
이미지 저장에는 성공했지만 `member`에 `url` 저장은 실패할 수 있는 경우를 나중에 고려해봐도 좋을 것 같아요

2024-09-25 02:55 UTC, Ho-Tea commented on backend/src/test/java/com/staccato/member/service/MemberServiceTest.java
> +    @DisplayName("사용자가 다른 사용자의 프로필을 변경할 수 없다.")
요청하신 사용자 정보를 찾을 수 없다는 식의 이름이 되어야 할 것 같아요!

2024-09-25 04:50 UTC, linirini commented on backend/src/main/java/com/staccato/member/controller/MemberController.java
> +        MemberProfileResponse memberProfileResponse = memberService.changeProfileImage(member, memberId, imageUrlResponse.imageUrl());
이 부분은 더 고민해봅시다!

2024-09-25 05:37 UTC, linirini commented on backend/src/main/java/com/staccato/member/controller/MemberController.java
> +    @PostMapping(path = "/{memberId}/profiles/images", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
트랜잭션 범위 문제로 인하여 ArgumentResolver에서 찾아온 Member를 Service에서 사용할 수 없었어요. Service에서 사용하는 영속성 컨텍스트에는 Member가 등록되어 있지 않기 때문에 변경 감지가 발생하지 않아요!
그래서 Member를 서비스에서 다시 찾는 작업이 필요했습니다.
그렇다면 pathVariable로 받을 필요가 있을까라는 생각이 드는데요.
제가 내린 결론은 다음과 같습니다.
LoginMember는 인증을 위해 찾아오는 Member입니다. 이 Member의 id로 Service에서 Member를 조회한 후, image를 수정할 수 있겠지만 LoginMember는 인증 책임 뿐만 아니라, 프로필 이미지를 변경하기 위한 객체라는 책임을 하나 더 가지게 된다고 생각했어요.
그래서 pathVaraible로 memberId를 받는 것이 그 책임 분리도 할 수 있고, 가독성 좋은 uri가 될 거라고 생각했어요!

물론 저도 아직한 아쉬움이 많이 남는 부분이라 후에 개선 방향을 더 고민해보겠습니다:)

2024-09-25 05:59 UTC, linirini commented on backend/src/main/java/com/staccato/member/service/MemberService.java
> +        validate(member, target);
저도 카고가 말한 부분에 매우 동의합니다.! 아까 회의에서는 우선 유지하는걸로 얘기했는데, 막상 코멘트를 작성하다보니 불필요한 pathVariable이라는 생각이 많이 드네요..ㅎㅎㅎ
제거했습니다!

2024-09-25 06:48 UTC, Ho-Tea approved these changes
변경사항 잘 적용해주셨네요 👍
다른 파일들에 아직 코드 컨벤션(`import` 개행)이 적용안된 부분이 있지만 앞으로 개발을 이어나가면서 적용될 것이라 판단하여 approve 드립니다!

2024-09-25 06:48 UTC, devhoya97 approved these changes
변경사항과 함께 리니의 생각 정리 내용까지 확인했습니다 👍 머지해도 될 것 같아요.

질문)
"members/profiles/images"로 url이 결정됐네요. 아까 회의에서 말한 restful하게 가려면 자원을 명확하게 지정해야 한다! 라는 관점에서는 어떤 결론이 난건지 궁금해요! url에 memberId가 빠지니 정확히 어떤 이미지를 변경할 것인지 url만으로는 표현하기 어려워 보여서요.

2024-09-25 06:49 UTC, devhoya97 commented on backend/src/main/java/com/staccato/member/controller/MemberController.java
> +    @PostMapping(path = "/profiles/images", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
"members/profiles/images"로 url이 결정됐네요. 아까 회의에서 말한 restful하게 가려면 자원을 명확하게 지정해야 한다! 라는 관점에서는 어떤 결론이 난건지 궁금해요! url에 memberId가 빠지니 정확히 어떤 이미지를 변경할 것인지 url만으로는 표현하기 어려워 보여서요.

2024-09-25 07:14 UTC, BurningFalls approved these changes

2024-09-25 07:22 UTC, linirini commented on backend/src/main/java/com/staccato/member/controller/MemberController.java
> +    @PostMapping(path = "/profiles/images", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
그 부분은 동감합니다! 하지만, 더 고민해보니 {memberId}를 명시하게 되면서 본인의 이미지 외 다른 사람의 이미지를 변경할 가능성이 생겨서 검증 로직이 추가되어야 하는 비용이 더 크게 다가왔습니다.
그렇다고 단순 명시를 위해 memberId를 pathVariable로 추가하는 건 불필요해보였고요.
아니면 `mypage/images`은 어떻게 생각하세요?

2024-09-25 07:54 UTC, merged