ui: 현위치 로드 시 로딩 애니메이션 보여주기 #418
woowacourse-teams/2024-staccato pull request #419
Opened 2024-10-02 03:20 UTC by s6m1n

## ⭐️ Issue Number
- #418

## 🚩 Summary

https://github.com/user-attachments/assets/7573ff7f-4312-4044-beb8-f5ebc0103a10

- [x] 로티 의존성 추가
- [x] 로티 애니메이션 파일(dot_loading.json) 추가
- [x] BindingAdapter에서 아래 동작 구현
    - [x] **로딩 중** : 로딩 애니메이션 표시, 클릭 비활성화 
    - [x] **로딩 완료** : 텍스트 & 아이콘 표시, 클릭 활성화

## 🛠️ Technical Concerns

BindingAdapter에서 텍스트와 아이콘을 동적으로 설정하려면 코틀린 코드 상에서 아래 속성들에 접근할 수 있어야 합니다.

```kotlin
        icon =
            getDrawable(context, R.drawable.icon_crosshair)?.apply {
                setBounds(0, 0, 70, 70)
                setTint(context.getColor(R.color.gray3))
            }
        compoundDrawablePadding = 20
        iconGravity = ICON_GRAVITY_TEXT_START
```

따라서 기존 현위치 로드 버튼을 Button에서 MaterialButton에서 수정했습니다.

### Button과 MaterialButton의 차이

**1. Button**
- 기본 버튼: Android의 기본 UI 컴포넌트 중 하나로, Material Design이 적용되지 않은 단순한 버튼입니다.
- 스타일: 기본적인 스타일을 가지며, 버튼의 배경, 텍스트 색상 등을 직접 설정해야 합니다.
- 제한된 기능: 기본적인 클릭 동작만 지원하며, 커스터마이징에 제약이 있습니다.

**2. MaterialButton**
- Material Design: Google의 Material Design 가이드라인을 기반으로 하여 디자인된 버튼입니다. 모양, 애니메이션, 그림자 등 다양한 시각적 요소가 적용되어 있습니다.
- 다양한 속성: 배경, 텍스트 색상, 아이콘, 모서리 반경 등의 속성을 더 유연하게 조정할 수 있습니다.
- 확장성: 여러 가지 모드(예: 텍스트 버튼, 아이콘 버튼, 아웃라인 버튼 등)를 지원하여 다양한 사용 사례에 맞게 사용할 수 있습니다.
- 테마 지원: Material Components 라이브러리를 통해 다크 모드와 같은 테마를 지원하며, 쉽게 커스터마이즈할 수 있습니다.

2024-10-02 06:12 UTC, hxeyexn requested changes
빙티! 로딩 애니메이션 구현하시느라 너무 고생많으셨습니다~ 🥹 👍
너무 예쁘네요!! 몇가지 코멘트 남겨두었으니 확인 부탁드리겠습니다!

2024-10-02 06:12 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/visitupdate/VisitUpdateActivity.kt
> +            viewModel.setCurrentLocationLoading(true)
현위치를 불러오는 시간이 길 때는 ui가 너무 깔끔한데, 짧을 때는 스켈레톤 ui가 깜박거리는 것처럼 보여서 오히려 사용자 경험이 안좋은 것 같네요..! ㅠㅠ 
현 위치를 불러오는 시간이 1~2초 이상 걸릴 때만 스켈레톤 ui를 보여주는 것도 괜찮을 것 같은데, 이 방법은 조금 어려울 수도 있을 것 같네요.. 차라리 1초 정도의 딜레이를 주는 건 어떻게 생각하시나요? 

같이 이야기 나눠보면 좋을 것 같습니다!
이와 관련된 글 몇개 링크 걸어두겠습니다! 

[무조건 스켈레톤 화면을 보여주는게 사용자 경험에 도움이 될까요?](https://tech.kakaopay.com/post/skeleton-ui-idea/)
[스켈레톤 로딩, 언제 사용해야 할까? — 헤이딜러 UX 스터디](https://medium.com/prnd/%EC%8A%A4%EC%BC%88%EB%A0%88%ED%86%A4-%EB%A1%9C%EB%94%A9-%EC%96%B8%EC%A0%9C-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%95%BC-%ED%95%A0%EA%B9%8C-%ED%97%A4%EC%9D%B4%EB%94%9C%EB%9F%AC-ux-%EC%8A%A4%ED%84%B0%EB%94%94-00d2cc323b17)
[Progress Indicators Make a Slow System Less Insufferable](https://www.nngroup.com/articles/progress-indicators/)

2024-10-02 07:13 UTC, s6m1n commented on android/Staccato_AN/app/src/main/res/layout/activity_visit_creation.xml
> +                    />
허거거거걱 이게 왜 돌아갔지..😅 수정했습니다!

2024-10-02 07:13 UTC, s6m1n commented on android/Staccato_AN/app/src/main/res/layout/activity_visit_creation.xml
> +                    android:id="@+id/constraint_current_location"
지금 올라온 PR들 다 머지 되면 대청소 싹싹 해버리겠습니다~

2024-10-02 07:59 UTC, Junyoung-WON reviewed
로딩 구현 너무 잘해주셨습니다! 👍 👍
예쁜 로딩 UI로 앱을 더 보기 좋게 만들어주셨네요!! 😊

수정이 필요한 부분들은 해나가 앞서 언급해주어서, 간단한 코멘트만 몇 개 작성해보았으니 확인 부탁드립니다~

2024-10-02 07:59 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/res/layout/activity_visit_creation.xml
> +                    <com.google.android.material.button.MaterialButton
`app:icon` 속성 대신 `android:drawableLeft` 속성도 고려해보셨을까요?

`android:drawableStart="@drawable/icon_start"`
`android:drawableEnd="@drawable/icon_end"`
`android:drawablePadding="10dp"`

2024-10-02 07:59 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/res/layout/activity_visit_creation.xml
> +                        android:id="@+id/btn_current_location"
이 부분도 id 컨벤션에 맞지 않은 것 같아요!
`android:id="@+id/btn_staccato_creation_current_location"`

파일 이름 변경을 고려하신 것 같기도 하네요!

2024-10-02 07:59 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/res/layout/activity_visit_update.xml
> +                        android:focusable="false"
clickable과 focusable 속성을 false로 지정한 이유가 무엇인가요??

2024-10-02 07:59 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/momentcreation/viewmodel/MomentCreationViewModel.kt
> +
작은 의견입니다!

`isCurrentLocationLoading` 이라는 상태 값을 `SharedViewModel`에 두는 것도 괜찮을 것 같아요!
그렇게되면 스타카토 생성, 수정 뷰모델에 동일한 로직이 사라지고, MainActivity에서도 활용이 가능해질 것 같습니다.

2024-10-03 08:39 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/momentcreation/viewmodel/MomentCreationViewModel.kt
> +
물론 아주아주 후순위로 미루어도 되는 사소한 작업입니다!
리팩터링 관점에서 이러면 어떨까 하는 생각에 작은 의견 남겨보았어요

2024-10-07 08:54 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/BindingAdapters.kt
> +        iconGravity = ICON_GRAVITY_TEXT_START
반영 완료했습니다!

2024-10-07 08:54 UTC, s6m1n commented on android/Staccato_AN/app/src/main/res/layout/activity_visit_creation.xml
> +                        bind:setCurrentLocationButtonLoading="@{viewModel.isCurrentLocationLoading}" />
반영 완료했습니다!

2024-10-07 08:54 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/visitupdate/VisitUpdateActivity.kt
> +            viewModel.setCurrentLocationLoading(true)
반영 완료했습니다!

2024-10-07 08:55 UTC, s6m1n commented on android/Staccato_AN/app/src/main/res/layout/activity_visit_creation.xml
> +                    <com.google.android.material.button.MaterialButton
`drawableLeft`는 텍스트와의 간격을 조정하기 어려워서 `app:icon` 속성으로 대체하였습니다..!

2024-10-07 08:56 UTC, s6m1n commented on android/Staccato_AN/app/src/main/res/layout/activity_visit_creation.xml
> +                        android:id="@+id/btn_current_location"
맞아요! 해당 부분도 이후 xml 컨벤션 정리 시 반영하도록 하겠습니다 👍

2024-10-07 08:58 UTC, s6m1n commented on android/Staccato_AN/app/src/main/res/layout/activity_visit_update.xml
> +                        android:focusable="false"
로딩 중에는 버튼 클릭을 막기 위해 clickable 속성을 지정해주었는데요, focusable은 확실히 불필요한 설정인 것 같아 삭제해주었습니다!
리팩터링 이후에는 android:clickable="true" 속성을 styles로 분리해주고, bindingAdapter에서 로딩중일 때만 false로 바꿔주었습니다.

2024-10-07 08:59 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/momentcreation/viewmodel/MomentCreationViewModel.kt
> +
isCurrentLocationLoading는 MainActivity에서 사용할 일이 없어 전역적으로 공유하는 SharedViewModel로 옮기는 건 좀 더 생각이 필요할 것 같네요! 그치만 확실히 스타카토 생성, 수정 뷰모델에 중복되는 로직이 많아 어떻게 개선할 수 있을지 고민 중입니다..ㅎㅎ

2024-10-07 10:57 UTC, hxeyexn approved these changes
리뷰 반영 잘 해주셨네요! 수고하셨습니다~~
빙빙 쵝오 👍

2024-10-07 10:57 UTC, merged