feat: 특정 방문 기록 삭제 API 구현 #26
woowacourse-teams/2024-staccato pull request #42
Opened 2024-07-22 14:56 UTC by devhoya97

## ⭐️ Issue Number
- #26 
## 🚩 Summary

- 특정 방문 기록 삭제 API 구현
- 양수가 아닌 id 값으로 특정 방문 기록 삭제를 시도하면 Bad Request를 반환하는 기능 구현

## 🛠️ Technical Concerns

## 🙂 To Reviwer
현재 테스트는 실제로 삭제가 이루어지고 있는지 확인하고 있지 않습니다. 예를 들어 아래와 같은 시나리오 테스트가 필요해보입니다.
1. `id=1` 인 `visit`이 저장되어 있음을 확인
2. delete 수행
3. `id=1`인 `visit`이 논리적으로 삭제되었음을 확인

그리고 이를 위해선 test용 data fixture 구성이 필요해보입니다.

## 📋 To Do

2024-07-22 15:38 UTC, Ho-Tea requested changes
수고하셨습니다 카고 🫡
몇가지 코멘트 남겼는데, 확인 부탁드릴게요!
그리고 PR에 작성해주신 부분에 대해 제 생각을 적자면
> 현재 API 명세서에 보면 삭제 성공시 200 OK를 전달하기로 되어 있습니다. 그런데 다시 생각해보니 204 No Content를 반환하는게 더 적절해보이는데 어떤가요?

- 정답이 없는 문제라 생각되어서, 이 부분은 안드로이드 측과 협의가 필요해 보입니다..ㅎ

>방문 기록이 삭제되면 해당 방문 기록에 남겨진 로그까지 삭제하는게 자연스러운 것 같아요. VisitLogRepository 파일을 보면 soft delete를 하기 위한 메서드를 GPT의 도움을 받아 작성했는데, @SQLDelete를 VisitLog에 명시해놓았음에도 불구하고 Update 쿼리를 날려야 한다는 점이 부자연스러운 것 같아요. 더 좋은 방법이 있을까요?

- 방문 기록이 삭제되면 해당 방문 기록에 남겨진 로그까지 논리적 삭제가 아닌 실제로 삭제가 이루어지는게 합리적일 것 같다라고 이해했는데 맞을까요?

2024-07-22 15:38 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/exception/InvalidIdException.java
> +}
저는 보통 기본으로 제공되어지는 예외(ex:`IllegalArgumentException`)를 우선적으로 사용한 후 기본으로 제공되어지는 예외로 커버가 불가능한 예외를 커스텀하는 편이라 해당 `InvalidException`이 일어나는 부분은 `IllgealArgumentException`으로 충분히 대체 가능하다고 생각되는데 카고의 생각은 어떠신가요!

2024-07-22 15:38 UTC, Ho-Tea commented on backend/src/main/java/com/staccato/visit/controller/VisitController.java
> +        }
``` java
@DeleteMapping("{visitId}")
public ResponseEntity<Void> deleteById(@PathVariable @Min(value = 1L, message = "방문 기록 식별자는 양수로 이루어져야 합니다.") Long visitId) {
```
로 대체할 수 있을 것 같아요!

2024-07-22 16:02 UTC, linirini requested changes
카고, API 구현하시느라 수고 많으셨습니다!
pr content에 남겨주신 내용들은 리뷰하면서 comment에 반영해놓았습니다.
리뷰 반영 후, 재요청 부탁드립니다!

2024-07-22 16:02 UTC, linirini commented on backend/src/main/java/com/staccato/visit/service/VisitService.java
> +        visitRepository.deleteById(visitId);
참조 무결성을 위반하지 않도록 삭제 순서도 잘 고려하면 좋을 것 같아요!
서비스 슬라이스 테스트를 추가해주면 좋을 것 같습니다:)

2024-07-22 22:50 UTC, BurningFalls commented on backend/build.gradle
> +	testImplementation 'io.rest-assured:rest-assured:5.3.1'
API 테스트를 위해서 `RestAssured` 라이브러리를 추가하셨네요! 동일하게 수정이 필요한 `build.gradle`의 변경 사항이라서, 코드를 합칠 때 모두가 신경써야 할 부분이라고 생각합니다.

2024-07-23 00:02 UTC, BurningFalls commented on backend/src/main/java/com/staccato/exception/GlobalExceptionHandler.java
> +                .body(new ExceptionResponse(HttpStatus.BAD_REQUEST.toString(), e.getMessage()));
`HttpStatus.BAD_REQUEST`를 어떻게 하면 저희 요구사항인 `"400 BAD_REQUEST"`에 맞게 변경할지 고민하고 있었는데, `toString()` 메서드를 사용하면 원하는 형태로 정확히 변경할 수 있네요! 좋은 사실 하나 알아갑니다. 😄

2024-07-23 00:15 UTC, BurningFalls commented on backend/src/main/java/com/staccato/exception/InvalidIdException.java
> +}
저도 기본으로 제공되는 예외로 충분히 처리 가능한 상황이라면, 따로 커스텀 예외를 만들지 않는다는 호티의 의견에 동의합니다!

하지만 예외가 발생할 때 상태 코드와 메시지를 커스텀해야 하는 상황이었고, 아래와 같은 코드를 피하기 위해서 커스텀 예외를 생성한 것으로 추측되네요.

```java
public ResponseEntity<Void> deleteById(@PathVariable Long visitId) {
    if (visitId < MIN_ID) {
        return ResponseEntity.badRequest().body(new ExceptionResponse(HttpStatus.BAD_REQUEST.toString(), "방문 기록 식별자는 양수로 이루어져야 합니다."));
    }
}
```

혹시 커스텀 예외를 만드는 방법 이외에도 해당 예외 케이스에 대한 상태코드와 메시지를 깔끔하게 처리할 수 있는 제가 모르는 다른 방법이 있다면 공유부탁드립니다!

2024-07-23 00:21 UTC, BurningFalls commented on backend/src/main/java/com/staccato/exception/InvalidIdException.java
> +}
향후에 비슷한 종류의 에러이면서 동일한 상태 코드를 반환하는 에러들이 더 생긴다면, 하나의 큰 에러로 묶어서 처리할 수 있을 것 같습니다.

```java
public class RoomescapeException extends RuntimeException {
    public RoomescapeException(String message) {
        super(message);
    }
}

public class DuplicateReservationException extends RoomescapeException {
    public DuplicateReservationException(String message) {
        super(message);
    }
}

public class InvalidSearchDateException extends RoomescapeException {
    public InvalidSearchDateException(String message) {
        super(message);
    }
}
```

```java
    @ExceptionHandler(RoomescapeException.class)
    public ResponseEntity<ErrorResponse> handleRoomescapeException(RoomescapeException e) {
        return ResponseEntity.badRequest()
                .body(new ErrorResponse(e.getMessage()));
    }
```

2024-07-23 00:31 UTC, BurningFalls commented on backend/src/main/java/com/staccato/visit/controller/VisitController.java
> +        }
위의 제 질문에 대한 답이 여기 있었네요!

조사해보니 위와 같이 코드를 작성하게 되면, `MethodArgumentNotValidException`을 반환한다고 되어 있습니다. `ControllerAdvice`에서 이 예외를 잡아 `BAD_REQUEST`를 던져주면 되겠네요.

```java
@ExceptionHandler(MethodArgumentNotValidException.class)
public ResponseEntity<ExceptionResponse> handleMethodArgumentNotValidException(MethodArgumentNotValidException e) {
    return ResponseEntity.badRequest()
            .body(new ExceptionResponse(HttpStatus.BAD_REQUEST.toString(), e.getMessage()));
}
```

2024-07-23 00:46 UTC, BurningFalls commented on backend/src/main/java/com/staccato/visit/repository/VisitLogRepository.java
> +    @Modifying
처음 보는 annotation이라 검색을 해보았는데, `@Modifying` annotation을 사용할 때 몇 가지 조심해야 할 점이 있어서 사용한다면 주의해서 사용해야 할 것 같습니다.

* `@Modifying` 메서드는 트랜잭션 내에서 실행되어야 한다. 따라서 `@Transactional` annotation과 함께 사용하여 트랜잭션 경계를 명확히 해야 한다.
* `@Modifying` 메서드는 보통 int 또는 void 반환 타입을 가진다. int는 영향을 받은 행(row)의 수를 반환하며, void는 결과에 대해 신경 쓰지 않는다. 반환 타입을 명확히 정의하지 않으면 예외가 발생할 수 있다.
* `@Modifying` 메서드가 호출되면 영속성 컨텍스트가 플러시되어 변경된 상태가 데이터베이스에 반영된다. 이로 인해 예상치 못한 결과가 발생할 수 있으므로, 영속성 컨텍스트의 상태를 주의 깊게 관리해야 합니다.

분석이 부족한 것 같아서 더 조사 중에 있습니다.

2024-07-23 00:52 UTC, BurningFalls commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
저도 리니가 말한 것에 대해서 알고 싶네요! 같이 소개해주세요.

2024-07-23 00:56 UTC, BurningFalls requested changes
안녕하세요 카고, 폭포입니다!

깔끔하게 잘 구현해주셨네요. 카고가 API를 구현하면서 든 의문들은 다같이 만나서 얘기해보고, 방법을 하나로 통일하면 좋을 것 같아요!

2024-07-23 03:56 UTC, devhoya97 commented on backend/src/main/java/com/staccato/exception/InvalidIdException.java
> +}
양수가 아닌 `visitId` 값이 들어왔을 때. `IllgealArgumentException`을 던지게 된다면 `GlobalExceptionHandler`에서 `IllegalArgumentException`을 잡아 처리해야 할텐데요. 이 때 서버 내부적으로 발생한 `IllegalArgumentException`과 구분하여 처리하기가 힘들지 않을까 해서 커스텀 예외를 만들었어요. 

폭포가 말씀해주신대로 우리가 발생시킨 예외와 시스템이 발생시킨 예외를 구분하기 위해 하나의 큰 에러를 만드는 것도 좋겠네요! 이따 회의 때 얘기해봅시다!

2024-07-23 04:06 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/controller/VisitController.java
> +        }
위 두 내용 참고하여 커스텀예외 제거하는 방향으로 반영하였습니다!

2024-07-23 04:07 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/controller/VisitController.java
> +    @DeleteMapping("{visitId}")
그러네요. 반영했습니다!

2024-07-23 04:07 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/controller/VisitController.java
> +        if (visitId < MIN_ID) {
위 호티의 의견과 같네요! 반영했습니다!

2024-07-23 04:39 UTC, linirini commented on backend/src/main/java/com/staccato/visit/repository/VisitLogRepository.java
> +    @Modifying
참고자료: https://github.com/2024-woowacourse-study/level-interview/discussions/202

2024-07-24 03:57 UTC, BurningFalls approved these changes

2024-07-24 04:55 UTC, devhoya97 commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +                .header("Authorization", "1")
반영했습니다~

2024-07-24 06:24 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/service/VisitService.java
> +        visitRepository.deleteById(visitId);
좋은 포인트네요. VisitLog를 먼저 삭제하도록 순서를 변경하고, 삭제가 잘 되는지 확인할 수 있는 서비스 슬라이스 테스트코드 추가하였습니다!

2024-07-24 06:24 UTC, devhoya97 commented on backend/build.gradle
> +	testImplementation 'io.rest-assured:rest-assured:5.3.1'
고려하여 merge하겠습니다 :)

2024-07-24 07:15 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/repository/VisitLogRepository.java
> +    @Modifying
여러 개의 `VisitLog`는 하나의 `Visit`에 포함될 수 있으므로 하나의 `Visit`이 삭제될 때 `Visit`에 포함된 모든 `VisitLog`가 함께 삭제되는 것이 자연스럽습니다. cascade 옵션을 사용하는 것이 일반적이지만, 우리와 같이 논리적 삭제를 선택한 경우에는 아래 두 방법 중 하나를 선택해야 하는데요.

1. `VisitLog`를 하나씩 삭제하기 위한 N개의 쿼리를 사용한다.
2. `VisitLog`를 벌크 연산으로 하나의 쿼리로 삭제한다.

2번 선택지를 사용하기 위해 `@Modifying`을 사용했습니다. 추가로 리니가 첨부해준 자료를 보니 `@Modifying`을 사용했을 때 영속성 컨텍스트 관련 문제가 발생할 수 있어서 `@Modifying(clearAutomatically = true)` 옵션을 추가해줬습니다.

실제로 위 옵션을 빼고 `VisitLogRepositoryTest.deleteByVisitId()` 테스트 코드를 수행해보면 논리적 삭제가 되지 않은 상태의 엔티티를 영속성컨텍스트로부터 가져와서 fail나네요!

2024-07-24 08:24 UTC, linirini approved these changes
큰 수정사항 아니라서 approve 남깁니다. 수고했어요 카고!

2024-07-24 08:24 UTC, linirini commented on backend/src/main/java/com/staccato/visit/domain/VisitLog.java
> +    public VisitLog(String content, @NotNull Visit visit, @NonNull Member member) {
2차 스프린트 개발 범위는 아니지만, content도 필수값이 될 것 같습니다. NotNull 어노테이션을 추가하면 좋을 것 같네요!

2024-07-24 08:27 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/controller/VisitController.java
> +        return ResponseEntity.noContent().build();
어제 회의 내용처럼 200으로 변경했습니다 ㅎ;

2024-07-24 08:28 UTC, BurningFalls approved these changes

2024-07-24 08:44 UTC, Ho-Tea approved these changes

2024-07-24 08:49 UTC, devhoya97 commented on backend/src/test/java/com/staccato/visit/controller/VisitControllerTest.java
> +                .statusCode(204);
오오 반영완료했습니다!!

2024-07-24 08:50 UTC, devhoya97 commented on backend/src/main/java/com/staccato/visit/domain/VisitLog.java
> +    public VisitLog(String content, @NotNull Visit visit, @NonNull Member member) {
간단한 내용이라 반영 했습니다 :)

2024-07-24 08:52 UTC, merged