feat & fix: 사진 코루틴 취소 버그 수정 / ACTION_PICK_IMAGES 적용 #536
woowacourse-teams/2024-staccato pull request #537
Opened 2024-10-30 06:07 UTC by s6m1n

## ⭐️ Issue Number
- # 536

## 🚩 Summary

- [x] 카메라와 사진 권한 메시지 분리
- [x] API 33 이상에서 `MediaStore.ACTION_PICK_IMAGES` 적용
- [x] `MediaStore.ACTION_PICK_IMAGES`사용 중 사진을 여러 장 선택하는 경우 앨범에서 최대 선택 가능 수 제한
- [x] `imageRepository.convertImageFileToUrl`에서 예외 반환 시 isActive로 취소 예외 무시

## 🛠️ Technical Concerns

### 작업 1 (feat) : 안드로이드 API 33 이상에서 `MediaStore.ACTION_PICK_IMAGES` 적용

티라미수 이상 버전에서는 권한이 없어도 `MediaStore.ACTION_PICK_IMAGES`로 기기의 사진 파일에 접근 가능합니다.
해당 작업으로 얻을 수 있는 이점은 다음과 같습니다.
1. **권한이 없어도 사진**을 불러올 수 있음. (권한이 있다면 그대로 앨범으로 접근)
2. `MediaStore.ACTION_PICK_IMAGES`에서 **선택 가능한 사진 장 수 제한 가능**

### 작업 2 (fix) : 스타카토 생성/수정 화면 사진 삭제 시 코루틴 취소 예외 처리
코루틴 Job은 취소 시 내부의 중단 가능 지점(suspend fun)에서 `JobCancellationException`를 발생시킵니다.
직전의 네트워크 에러 핸들링 작업에서 모든 예외를 '네트워크 불안정 스낵바'로 처리하였습니다.
따라서 무시되고 있던 해당 예외가 잘못 핸들링 되며 나타난 버그로 보여집니다.

```kotlin
    if (this.isActive) handleException(e, message)
```

따라서, 예외 핸들링 지점에서 `isActive`를 검사해 코루틴 취소 예외는 무시되도록 수정했습니다.

## 🙂 To Reviewer

## 📋 To Do

2024-10-30 07:32 UTC, hxeyexn approved these changes
빙티의 ACTION_PICK_IMAGES 적용 덕분에 API 33 버전 이상의 사용자는 권한 없이도 사진을 업로드할 수 있게 되었군요!! 😎
정말 고생 많으셨습니다~ 코멘트 남겨두었으니 확인 부탁드려요!

2024-10-30 07:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/PhotoAttachFragment.kt
> +        }
```kotlin
private var availableImageCount: Int? = null
```

availableImageCount의 초기값을 null보다는 0으로 설정하는 건 어떠신가요? 0으로 설정하면 null 체크를 할 필요가 없어서 depth를 줄일 수 있을 것 같아요!

```suggestion
        if (!multipleAbleOption && SdkExtensions.getExtensionVersion(Build.VERSION_CODES.R) < 2) return this
        if (MIN_COUNT_FOR_PICK_IMAGES_MAX < availableImageCount) {
            putExtra(MediaStore.EXTRA_PICK_IMAGES_MAX, availableImageCount)
        }
```

2024-10-30 07:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/PhotoAttachFragment.kt
> +        if (!multipleAbleOption && SdkExtensions.getExtensionVersion(Build.VERSION_CODES.R) < 2) return this
매직넘버는 상수화하면 좋을 것 같아요!

2024-10-30 07:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/StaccatoCreationActivity.kt
>                  listOf(AttachedPhotoUiModel.addPhotoButton).plus(photos.attachedPhotos),
```suggestion
                listOf(AttachedPhotoUiModel.addPhotoButton, *photos.attachedPhotos.toTypedArray()),
```

두 개의 list를 합치기 보다는 가변인자를 함수의 인자로 넘길 수 있는 listOf의 특성과 스프레드 연산자를 활용하는 건 어떠신가요?

2024-10-30 07:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatoupdate/StaccatoUpdateActivity.kt
>                  listOf(AttachedPhotoUiModel.addPhotoButton).plus(photos.attachedPhotos),
> 두 개의 list를 합치기 보다는 가변인자를 함수의 인자로 넘길 수 있는 listOf의 특성과 스프레드 연산자를 활용하는 건 어떠신가요?

동일한 의견입니다~

2024-10-30 07:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/PhotoAttachFragment.kt
> +                    .setDataAndType(MediaStore.Images.Media.EXTERNAL_CONTENT_URI, "image/*")
`image/*`를 상수화하면 좋을 것 같아요~

2024-10-30 07:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/PhotoAttachFragment.kt
> +                Intent(MediaStore.ACTION_PICK_IMAGES)
권한이 없어도 기기의 사진 파일에 접근 가능하다니 너무 좋네요~ 🥹👍💯

2024-10-30 08:14 UTC, Junyoung-WON requested changes
빙티! 오류 핸들링을 빠르게 잘 처리해주셨네요...!! 😃
`MediaStore.ACTION_PICK_IMAGES` 활용과 그에 따른 버전 분기, 그리고 코루틴 취소에 대한 처리도 잘 해주신 것 같습니다!
너무 고생하셨어요~

`MediaStore.ACTION_PICK_IMAGES` 사용에 따른 버전 확인 코드와,
이미지 전송 코루틴 작업의 취소 시 `isActive`를 체크하는 부분에 대해서 의견 남겨보았어요.
확인해주시면 감사하겠습니다!

2024-10-30 08:14 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatoupdate/viewmodel/StaccatoUpdateViewModel.kt
> +                if (this.isActive) handleUpdatePhotoException(e, message)
찾아보니 다른 블로그에서도 `isActive`를 확인하여 코루틴 작업의 활성화 상태를 판단하고 원하는 작업을 수행하도록 구현하고 있었어요. 저는 괜찮은 처리 방식이라고 생각합니다!

그러다 `ensureActive()`라는 메서드를 알게 되었습니다! 이 메서드를 활용해봐도 좋을 것 같아요.
아래와 같이 `Job`의 확장함수로 구현되어 제공해주고 있습니다.
```kotlin
fun Job.ensureActive(): Unit {
    if (!isActive) {
         throw getCancellationException()
    }
}
```

내부적으로 `isActive`를 확인하여 활성화 상태가 아닌 경우 `JobCancellationException`을 `throw` 하도록 동작합니다. 그래서 `Job` 취소로 인한 `JobCancellationException` 예외가 `coroutineExceptionHandler`에서 잡힐 것으로 예상합니다...!
아래와 같이 활용할 수 있을 것 같습니다!
```suggestion
                ensureActive()
                handleUpdatePhotoException(e, message)
```

아래 레퍼런스를 참고해보시면 좋을 것 같아요!
[https://android-devpia.tistory.com/11](https://android-devpia.tistory.com/11)

2024-10-30 08:36 UTC, hxeyexn commented
> 예외 핸들링 지점에서 isActive를 검사해 코루틴 취소 예외는 무시되도록 수정했습니다.
> 적절한 방법일지에 대해 의논해 보면 좋을 것 같아요~

취소로 인해 예외가 발생하는 것이 아니라 `CancellationException` 에 코루틴이 의해서 취소되기 때문에 isActive를 검사해 코루틴 취소 예외를 무시하는 건 큰 문제가 없어보여요!

delay 함수 내부 구현 중에서도 `CancellableContinuationImpl`를 확인해보면 isActive를 검사하는 로직이 있네요! 

<img width="763" alt="image" src="https://github.com/user-attachments/assets/650de943-cfa5-414b-99ea-fef47c4909e6">

<img width="475" alt="image" src="https://github.com/user-attachments/assets/906e1058-707b-470e-91cb-0b3b97425996">

2024-10-30 09:20 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/PhotoAttachFragment.kt
> +        if (!multipleAbleOption && SdkExtensions.getExtensionVersion(Build.VERSION_CODES.R) < 2) return this
아래와 같이 버전을 확인할 수 있을 것 같네요!
Photo Picker 는 기본적으로 티라미수 버전(API Level 33) 이상인 경우 지원을 하지만, API 레벨이 32 인 버전의 일부 확장 버전도 지원을 해줍니다.
```kotlin
private fun isPhotoPickerAvailable(): Boolean {
    return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
        true
    } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
        getExtensionVersion(Build.VERSION_CODES.R) >= 2
    } else {
        false
    }
}
```

참고 레퍼런스: [공식문서 - SDK Extensions](https://developer.android.com/guide/sdk-extensions#api-versioning), [공식문서 - Build.VERSION_CODES](https://developer.android.com/reference/android/os/Build.VERSION_CODES#R)

2024-10-30 10:01 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/PhotoAttachFragment.kt
> +        if (!multipleAbleOption && SdkExtensions.getExtensionVersion(Build.VERSION_CODES.R) < 2) return this
`isPhotoPickerAvailable()` 함수 내부의 `isSystemPickerAvailable()`에는 아래와 같이 구현되어있네요!

<img width="640" alt="image" src="https://github.com/user-attachments/assets/56f453a5-d324-483a-bad1-86ee1f4f6eed">

2024-10-30 11:08 UTC, s6m1n commented on android/Staccato_AN/app/src/main/res/values/strings.xml
> +    <string name="photo_require_photo_album_permission">사진 접근 권한을 허용해 주세요.</string>
화면이 작은 경우 스낵바 메시지가 모두 표시되지 않고 ellipsize 되어 ...로 표시되길래,
사용자가 혼란을 느낄 수 있어 우선 간결하게 바꿨습니다..
지금은 우선 유지하고, Rationale UI를 적용할 때 스낵바의 문구도 함께 상세하게 변경하는 게 좋을 것 같아요!

2024-10-30 11:33 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/PhotoAttachFragment.kt
> +        if (!multipleAbleOption && SdkExtensions.getExtensionVersion(Build.VERSION_CODES.R) < 2) return this
좋은 지적이네요! 덕분에 확장 버전이 뭔지 짚고 넘어갈 수 있었습니다.
무의미한 검사를 하고 있었군요 ㅋㅋ 호두의 코멘트 반영했어요!
별개로, 조건이 2개를 넘어가는 경우에는 if보다 when이 가독성이 좋다고 생각해 아래처럼 수정했습니다~
```kotlin
        when {
            (Build.VERSION_CODES.TIRAMISU <= VERSION.SDK_INT) -> true
            (Build.VERSION_CODES.R <= VERSION.SDK_INT) -> MINIMUM_EXTENSION_VERSION <= getExtensionVersion(Build.VERSION_CODES.R)
            else -> false
```

2024-10-30 11:44 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/PhotoAttachFragment.kt
> +        if (!multipleAbleOption && SdkExtensions.getExtensionVersion(Build.VERSION_CODES.R) < 2) return this
매개변수가 없는 `isPhotoPickerAvailable()`는 deprecated 되었고,  context를 매개변수로 받는 `isPhotoPickerAvailable()`은 deprecated 되지 않았네요..!

[isPhotoPickerAvailable()](https://developer.android.com/reference/kotlin/androidx/activity/result/contract/ActivityResultContracts.PickVisualMedia#isPhotoPickerAvailable())

2024-10-30 11:45 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/PhotoAttachFragment.kt
> +        if (!multipleAbleOption && SdkExtensions.getExtensionVersion(Build.VERSION_CODES.R) < 2) return this
좋은 지적이네요! 무의미한 검사를 하고 있었군요 ㅋㅋ
덕분에 확장 버전이 뭔지 짚고 넘어갈 수 있었습니다!

현재 isPhotoPickerAvailable()는 deprecated 되어서, context를 매개변수로 받는 아래 함수로 확인해줬습니다!
<img width="689" alt="image" src="https://github.com/user-attachments/assets/7bf03f1c-235d-425b-bfd0-4a29182576b6">

2024-10-30 13:55 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/PhotoAttachFragment.kt
> +        if (!multipleAbleOption && SdkExtensions.getExtensionVersion(Build.VERSION_CODES.R) < 2) return this
위 함수를 적용하니 컴파일러가 버전 체크 했다는 걸 감지하지 못하고 계속 경고를 띄우네요 ㅠㅠ
어쩔 수 없이 아래처럼 못생겼지만? 명시적인? 코드를 사용하도록 수정했습니다.
드디어 경고가 안 뜨네요...

```kotlin
    private fun isPhotoPickerAvailable() =
        (Build.VERSION_CODES.TIRAMISU <= VERSION.SDK_INT) || ((Build.VERSION_CODES.R <= VERSION.SDK_INT) &&
                (MIN_EXTENSION_VERSION <= SdkExtensions.getExtensionVersion(Build.VERSION_CODES.R)))
```

2024-10-31 04:37 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatoupdate/viewmodel/StaccatoUpdateViewModel.kt
> +                if (this.isActive) handleUpdatePhotoException(e, message)
`JobCancellationException`은 코루틴을 취소하기 위해 사용되는 특별한 예외로, 전파되지 않는다는 특징을 갖고 있다네요!
현재 방식은 isActive를 체크하여 `CancellationException`를 무시하고 있는데 호두가 제안해주신 코드는 이를 무시하지 않고 `handleUpdatePhotoException`에서 한번 더 처리하게 됩니다.
저는 `CancellationException`에 별도의 핸들링이 필요하지 않아 지금 코드로도 충분하다고 생각하는데 호두는 어떻게 생각하시나요?

2024-10-31 04:41 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/PhotoAttachFragment.kt
> +        }
**초기값**이면서도 **유효하지 않은 값**임이 더 명확하게 드러나도록 -1로 설정해주었습니다!

2024-10-31 05:48 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatoupdate/viewmodel/StaccatoUpdateViewModel.kt
> +                if (this.isActive) handleUpdatePhotoException(e, message)
`CancellationException` 이 코루틴에 전파되지 않는다는 사실을 몰랐네요!
저는 `ensureActive()` 내에서 예외를 던지는 `throw getCancellationException()` 으로 인해 코루틴 스코프가 `handleUpdatePhotoException()` 보다 더 먼저 예외를 잡으면서, 네트워크 에러 메시지가 나타나지 않을 것으로 생각했습니다. 😅

> 호두가 제안해주신 코드는 이를 무시하지 않고 handleUpdatePhotoException에서 한번 더 처리하게 됩니다.

그렇다면 지금의 코드가 제일 좋은 구현인 것 같습니다!

2024-10-31 05:49 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/res/values/strings.xml
> +    <string name="photo_require_photo_album_permission">사진 접근 권한을 허용해 주세요.</string>
교육용 UI가 추가한 후 문구를 상세하게 변경하면 좋을 것 같아요~

2024-10-31 05:54 UTC, Junyoung-WON approved these changes
Photo Picker 도입과 버전 처리, 코루틴 작업 취소 시 에러 핸들링 처리 모두 고생하셨습니다!!
갓티~~ 💯

2024-10-31 05:54 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/common/PhotoAttachFragment.kt
> +    private var attachableImageCount: Int = -1
nullable 에서 -1 이라는 기본 값으로 변경하셨군요!
불필요한 null 체크가 사라져서 깔끔해진 것 같아 좋습니다~
상수화 처리만 부탁드립니다! 😄

2024-10-31 05:59 UTC, merged