fix: 추억 생성 및 수정 썸네일 사진 업로드 오류 수정 #535
woowacourse-teams/2024-staccato pull request #542
Opened 2024-11-07 08:47 UTC by hxeyexn

## ⭐️ Issue Number
- #535

<br>

## 🎥 시연 영상
| 수정 전 | 수정 후 |
|:---:|:---:|
|<video src="https://github.com/user-attachments/assets/c52bf5eb-9863-483d-baf4-9c938b0abff0">|<video src="https://github.com/user-attachments/assets/cb6d6a03-d7d5-430b-8d69-04feda5a91a4">|

<br>

## 🚩 Summary
- A 사진을 업로드 중에 B 사진을 업로드 했을 때 네트워크 불안정 스낵바가 보여지는 현상 해결

<br>

## 🛠️ Technical Concerns
### 문제 상황
![okhttp](https://github.com/user-attachments/assets/65bb8db4-1735-422c-9c31-54f936e3af1c)

- A 사진을 업로드하는 중에 B 사진을 업로드 했을 때 `ProtocolException` 예외가 발생했고 `ApiResponseHandler`에서 잡혀 네트워크 불안정 스낵바가 노출되었습니다.
  - [`ProtocolException`](https://learn.microsoft.com/en-us/dotnet/api/system.servicemodel.protocolexception?view=dotnet-uwp-10.0)이란?
  
      - 데이터 전송 프로토콜이 일치하지 않아 서버와의 통신이 불가능할 때 발생하는 예외입니다.

<br>

- `Nginx access.log`를 확인해보니 `499` 에러가 발생하고 있었습니다.

   <img width="998" alt="access_log" src="https://github.com/user-attachments/assets/f66e27a3-0b03-4006-a2c5-362025f1430f">
  
  - **access.log**란?
      - 서버에 대한 모든 요청과 관련한 응답이 기록되는 로그 파일입니다.
      - 방문자가 웹 페이지를 요청하거나 API 호출을 하면 이 로그 파일에 기록됩니다.
     
  - **499(Client closed the connection)란?**
      - 서버가 응답을 완료하기 전에 `Application Gateway`로 전송되는 클라이언트 요청이 닫힌 경우를 뜻합니다.
      - [`Application Gateway`](https://learn.microsoft.com/en-us/azure/application-gateway/http-response-codes#499--client-closed-the-connection)란?
    
          - 웹사이트나 애플리케이션에 접속하는 사용자(클라이언트)와 실제 데이터를 처리하는 서버 사이에서 데이터를 효율적으로 전달하고 관리해 주는 서비스입니다.

### 발생 원인
- `ViewModel`에서 사진 업로드 `job`을 하나의 변수로 관리하며, `job`이 변경될 때 해당 변수의 값을 갱신했지만, 이전 코루틴 `job`은 취소하지 않고 있었습니다.
- 따라서 클라이언트가 새로운 요청을 보낼 때, `Application Gateway`는 기존의 완료되지 않은 요청을 처리하고 있었습니다.
    - 스타카토 서비스는 `Nginx`를 `Application Gateway`의 역할로 사용하고 있습니다.
- 서버가 응답을 완료하기 전에 클라이언트가 다른 요청을 보냈기에 `Application Gateway` 측에서 프로토콜 상태가 프로토콜 위반으로 간주됩니다.
- 이로 인해 `ProtocolException`이 발생해 `ApiResponseHandler`에서 잡혀 네트워크 불안정 스낵바가 보여졌습니다.

### 해결 방법
- `uri`를 키 값으로 가진 사진 업로드 `job`들을 `map`으로 관리하는 방식으로 변경했습니다.
- `invokeOnCompletion` 메서드를 활용해 `job` 이 `Completed` 나 `Cancelled` 와 같은 마지막 상태에 도달했을 때 자원을 해제하도록 구현했습니다.
- 사용자가 업로드 하려는 사진의 `uri`가 이전과 동일하지 않다면 `cancel` 메서드를 활용해 코루틴을 취소하도록 변경했습니다.

### 결론
이전 코루틴을 취소하도록 로직을 변경해 동시에 여러 요청이 발생하는 문제를 해결하고, 중복 요청에 따른 프로토콜 위반 문제를 해결했습니다.

2024-11-08 12:38 UTC, Junyoung-WON approved these changes
해나!! 리팩터링과 트러블 슈팅도 하시느라 너무 고생많으셨습니다!!

추억 썸네일 이미지 업로드 중 작업 취소에 대한 처리도 꼼꼼하게 잘 해주셨고, `ProtocolException`의 발생 원인을 정말 자세하게 공부하셨네요! 역시 해나도 한 딥다이브 한다니까요...!! 😆
앞서 코루틴 작업 취소에 대해서 트러블 슈팅을 해준 빙티 덕분에 빠르게 에러를 잡을 수 있었네요~ 외쳐 갓티! 갓나!
많은 지식 얻어갑니다! 🙇‍♂️

수정하면 좋을 부분들을 몇 가지 코멘트로 남겨보았어요. 천천히 확인해주시면 감사하겠습니다.
기능적으로 크게 고쳐야 할 부분은 없는 것 같아, 우선 Approve 드리겠습니다!

2024-11-09 02:49 UTC, s6m1n requested changes
버그 해결하느라 고생하셨습니다 해나! 코루틴과 싸워 이기셨군요 ㅎㅎ
추가로 궁금한 점이 있어 질문 드립니다~

새로운 사진을 불러왔을 때 Job.cancel을 수행하고 새로운 Job을 만들어 실행하고 있는데요
invokeOnCompletion를 통해 기존 **Job이 완전히 취소된 것을 확인**한 후 새로운 Job을 만드는 방식이 아니어도
연속 요청으로 인한 ProtocolException 499를 완전히 방지할 수 있을까요?

(그럴 일은 없겠지만) 만약 cancel 작업이 3분이 걸린다고 가정하면 현재 코드에서는 마찬가지로 ProtocolException 499 에러가 발생할까요?🤔

2024-11-09 02:49 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +        }
저도 호두의 의견에 동의합니다~
> 새로운 Thumbnail로 바꾼다는 setThumbnail 라는 네이밍은 어떤가요?

조금 더 구체적으로, Uri만 바꿔준다는 의미까지 포함해 `fun setThumbnailUri()`도 괜찮을 것 같아요!

2024-11-09 02:49 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +                _thumbnail.value = ThumbnailUiModel(uri = uri, url = url)
덧붙여서, `private fun createThumbnail()`의 url 매개 변수는 항상 null이 되겠네요.

```kotlin
        fun createThumbnailUrl(
            context: Context,
            uri: Uri,
        ) {
            _isPhotoPosting.value = true
            createThumbnail(uri) // uri만 넣어주고 있음. url은 항상 default인 null
            registerThumbnailJob(context, uri)
        }
```

그렇다면 url 매개변수를 제거하고 아래처럼 null을 직접 넣어주는 것이 더 명시적일 것 같아요~!

```suggestion
                _thumbnail.value = ThumbnailUiModel(uri = uri, url = null)
```

2024-11-09 02:49 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +        private fun fetchThumbnail(
호두가 제안해주신 이름은 "`fetching thumbnail`를 수행하는 job을 생성한다"라는 의미를 더 명확하게 전달한다는 점에서 저도 동의합니다!

더해서, 함수 명의 구조를 동사 + 목적어 형태로 하기 위해 `createFetchingThumbnailJob`도 좋을 것 같아요~

2024-11-09 02:49 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +        fun deleteThumbnail() {
추가로, 사진의 X 버튼이 눌렸을 때에도 리소스 관리를 위해 Job.cancel을 수행해야 한다는 생각이 드네요!
`thumbnailJobs[_thumbnail.value?.uri]?.cancel()` 로직을 deleteThumbnail() 내부로 옮기는 건 어떨까요?

2024-11-09 02:49 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memoryupdate/viewmodel/MemoryUpdateViewModel.kt
> +
`thumbnailJobs[_thumbnail.value?.uri]?.cancel()` 로직을 deleteThumbnail() 내부로 옮기면 아래처럼 재사용 가능할 것 같네요!
```suggestion
            if (isEqualUri == false) {
                deleteThumbnail()
            }
            _thumbnail.value = ThumbnailUiModel(uri = uri)
```

2024-11-09 02:58 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +                thumbnailJobs[_thumbnail.value?.uri]?.cancel()
아래 두 경우, Job.cancel()을 호출해도 코루틴이 이를 수신할 수 없어 즉시 취소되지 않습니다!

- 코루틴에 suspend 포인트가 없는 경우
- isActive를 확인하지 않는 경우

이렇게 내부적으로 취소될 수 없는 상태인 경우를 고려해 저는 Job.cancel()을 호출하기 전에 isActive로 수동으로 상태를 확인해주곤 하는데요!

```kotlin
            if (photoJobs[deletedPhoto.uri.toString()]?.isActive == true) {
                photoJobs[deletedPhoto.uri.toString()]?.cancel()
            }
```

Retrofit2 interface에서 지원하는 코루틴은 취소될 수 있는 코루틴일 것 같아 이 과정이 불필요한가? 싶기도 하네요 🤔
시간 되면 같이 '얕게 다이브' 해봐도 좋을 것 같아요!

2024-11-12 07:25 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +private typealias URI = Uri
`Map` 자료형을 사용할 때 key와 value가 의미하는 것을 명시적으로 나타내기 위해 typealias를 자주 활용하는 편입니다.
`mutableMapOf<String, String>()`과 같이 선언하면 key와 value의 값이 의미하는 것을 추측하기 힘들어요.

위 코드도 그런 이유로 `typealias`를 지정해두었는데 네이밍을 고민하다가 마땅한 네이밍이 떠오르지 않아서 임시로 적어두고 나중에 바꾼다는 걸 까먹었네요..! `ThumbnailUri`라는 이름으로 변경했습니다!

2024-11-12 10:20 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +
`ThumbnailUiModel` 구현 후 이를 적용하는 과정에서 매개변수의 타입 변경을 놓쳤었는데, ImageResponse를 nullable로 둔 이유를 호두가 저에게 질문해 줘서 해당 부분을 짚고 넘어갈 수 있었습니다. 감사합니다!

`반영 커밋` : [499b185](https://github.com/woowacourse-teams/2024-staccato/pull/542/commits/499b1856abe46702f88489e654c12773a9716b1f)

2024-11-12 10:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +        }
> 조금 더 구체적으로, Uri만 바꿔준다는 의미까지 포함해 fun setThumbnailUri()도 괜찮을 것 같아요!

해당 메서드는 `Uri`만 변경해주는 역할이라 빙티가 제안해주신 `setThumbnailUri`가 가장 명시적으로 다가오네요! 
반영해두었습니다!

`반영 커밋` : [863b9be](https://github.com/woowacourse-teams/2024-staccato/pull/542/commits/863b9be670b33cdf5d7903fa17a2f980917ec2fc)

2024-11-12 11:39 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +        }
> 추가로 기존 Uri와 다른 Uri인지 확인하는 코드를 아래처럼 메서드로 분리하면 코드가 좀 더 깔끔해질 것 같아요!

변수로 분리하는 것보다 메서드로 분리하는 게 더 깔끔하겠네요!
```kotlin
    private fun setThumbnailUri(
        uri: Uri?,
        url: String? = null,
    ) {
        if (isNewUri(uri)) {
          ...
        }
    }
    
    private fun isNewUri(uri: Uri?): Boolean = _thumbnail.value?.isEqualUri(uri) == false
```

매개변수로 들어온 Uri가 새로운 Uri일 때 uri를 설정한다는 것을 명시적으로 나타내기 위해 `isNewUri`라는 메서드명으로 분리했습니다!

`반영 커밋` :  [7a1bebc](https://github.com/woowacourse-teams/2024-staccato/pull/542/commits/7a1bebc1a778781fed748973c7bf89e4fa778655)

2024-11-12 12:03 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +        fun deleteThumbnail() {
추억 생성 및 수정 화면에서는 사진이 업로드 중일 때 X 버튼이 보여지지 않도록 구현되어 있습니다!
서버에 사진을 업로드하고 해당 사진의 URL을 서버에서 클라이언트로 전송하는 작업이 완료되어야 사용자가 X 버튼을 사용할 수 있습니다.

따라서 X 버튼이 사용자에게 보여진 시점에는 job이 마지막 상태인 `Completed`에 도달해 `invokeOnCompletion`에 의해 자원이 이미 해제된 상태이기 때문에 추가적으로 Job.cancel을 수행할 필요가 없다고 생각했습니다! 😊

2024-11-13 02:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/ThumbnailUiModel.kt
> +    fun delete() = this.copy(uri = null, url = null)
`delete` 보다 `clear`라는 네이밍이 더 적합하겠네요! `clear`로 변경했습니다!

`반영 커밋` : [27ecb45](https://github.com/woowacourse-teams/2024-staccato/pull/542/commits/27ecb45913eef7c0a33463de50a0dae19b971a4f)

2024-11-13 02:39 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +        fun deleteThumbnail() {
반영했습니다!

`반영 커밋` : [c0f5458](https://github.com/woowacourse-teams/2024-staccato/pull/542/commits/c0f5458204989bdb1936af4684ea8e533636b74e)

2024-11-13 02:48 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +                _thumbnail.value = ThumbnailUiModel(uri = uri, url = url)
헉 그렇네요! 수정했습니다~

`반영 커밋` : [382d063](https://github.com/woowacourse-teams/2024-staccato/pull/542/commits/382d06376d8844a1d078fc93ea8986541bce9276)

2024-11-13 05:15 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +        private fun fetchThumbnail(
서버에서 데이터를 불러올 때 fetchXXX 형식을 사용하기로 해서 `fetchThumbnail`로 네이밍 했었습니다.
지금은 썸네일 사진 업로드 Job 객체를 반환하는 역할도 포함하고 있기 때문에, 단순히 데이터를 불러오는 작업만 수행한다고 볼 수 없겠네요! 

`createFetchingThumbnailJob`로 변경했습니다!  

`반영 커밋` : [9e028d2](https://github.com/woowacourse-teams/2024-staccato/pull/542/commits/9e028d21d8b24160cd444a6c6c27d9214f02b442)

2024-11-13 05:51 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memoryupdate/viewmodel/MemoryUpdateViewModel.kt
> +
https://github.com/woowacourse-teams/2024-staccato/pull/542#discussion_r1837987150 와 동일한 의견입니다.

2024-11-19 08:33 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +                thumbnailJobs[_thumbnail.value?.uri]?.cancel()
헉 이 부분을 놓쳤네요!! 감사합니다~ 빙빙 짱!
`isActive`를 수동으로 상태를 확인하는 방법으로 변경했습니다!

`반영 커밋` : [fa613e6](https://github.com/woowacourse-teams/2024-staccato/pull/542/commits/fa613e68035e7e8113b2f428b9a40c25556529fd)

2024-11-19 11:51 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +        fun deleteThumbnail() {
아하ㅋㅋ 제가 스타카토 생성 화면이랑 헷갈렸네요! 좋습니다~

2024-11-20 07:56 UTC, s6m1n approved these changes

2024-11-20 15:51 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/memorycreation/viewmodel/MemoryCreationViewModel.kt
> +                thumbnailJobs[_thumbnail.value?.uri]?.cancel()
> Retrofit2 interface에서 지원하는 코루틴은 취소될 수 있는 코루틴일 것 같아 이 과정이 불필요한가? 싶기도 하네요 🤔

이와 관련해서 Retrofit2의 내부 구현을 찾아 봤는 데 아직 이해가 잘 안되네요 ㅠㅠ
빙티와 호두의 면접이 끝나고 난 후에 같이 '얕게 다이브' 해보면 좋겠네요!!

2024-11-20 15:52 UTC, merged