refactor: comments api uri 수정
woowacourse-teams/2024-staccato pull request #549
Opened 2024-11-10 12:17 UTC by linirini

## ⭐️ Issue Number
- #544 

## 🚩 Summary
- `PUT/DELETE /v2/comments/{commentId}`형태의 API로 버저닝하였습니다.
- comments를 필터링하는 것이 아닌 특정 식별자를 가진 자원을 접근하는 것이므로 path varaible 형태를 사용하도록 구현하였습니다.

## 🛠️ Technical Concerns

## 🙂 To Reviewer

## 📋 To Do
- 안드로이드 반영

2024-11-10 12:18 UTC, linirini commented on backend/src/main/java/com/staccato/comment/controller/CommentController.java
> +    @PostMapping("/comments")
버저닝을 위해서 클래스 레벨의 `RequestMapping`을 제거하고, 메서드 레벨로 이동하였습니다. 추후 안드로이드 반영 이후 버저닝 제거 시 클래스 레벨로 다시 변경 예정입니다.

2024-11-10 12:20 UTC, linirini commented on backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java
> +        mockMvc.perform(put("/v2/comments/{commentId}", 1)
테스트 역시 후에 버저닝이 제거될 것을 고려한다면, 기존에 존재하는 테스트 내에서 검증부를 추가하는 것이 가독성, 유지보수 측면에서 유리하다고 판단했습니다.
기능 측면에서는 변경된 것이 없기 때문에 성공 테스트에 대해서만 우선 새로 추가된 URI 검증을 추가했습니다.

2024-11-11 06:27 UTC, BurningFalls commented on backend/src/main/java/com/staccato/comment/controller/CommentController.java
> +    @PostMapping("/comments")
이렇게 매번 변경하면 번거로울 것 같으니, 차라리 api url의 `v2`를 도메인명 뒤에 다는 것은 어떨까요? `/comments/v2/{commentId}` 이렇게 하면 `RequestMapping` 구조를 그대로 유지 가능하면서 새로 추가되는 api 코드만 건드릴 수 있을 것 같습니다.

물론, 도메인명 뒤에 v2가 붙는 것이 맨 앞에 v2가 붙는 것보다 상대적으로 읽히는 것이 어색하긴 하지만, 어차피 일시적으로 유지할 api이기 때문에 잠깐의 Rest함의 장점보다는 구조 전체를 매번 바꿔야하는 코스트의 단점이 더 크게 느껴집니다.

2024-11-11 06:40 UTC, BurningFalls commented on backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java
> +        mockMvc.perform(put("/v2/comments/{commentId}", 1)
본능적으로는 또 다른 테스트를 만들어야 할 것 같다는 느낌이 들지만, 막상 코드를 보았을 때 테스트 간의 종속성 문제도 크게 신경쓸만한 부분이 없어서 이대로 구현해도 괜찮다고 생각합니다. 유지보수 측면에서 훨씬 간편하고 좋네요!

2024-11-11 06:41 UTC, BurningFalls requested changes
Rest한 API URL을 위해 update와 delete에서 id를 명시하는 점이 좋네요! 버저닝을 함에 따라서 달라지는 코드의 양과 관련하여 코멘트 남겨두었으니 확인 부탁드립니다.

2024-11-11 14:11 UTC, Ho-Tea requested changes
제가 이슈확인이 늦어 리뷰를 늦게달았네요 죄송합니다 🙇‍♂️
기존에 존재하던 쿼리파라미터 형태에서 PathVariable형태로 변경함에 따라 버저닝을 도입하시게 된 것 같은데 그로 인하여 불필요한 변경이 일어난 것 같습니다.
버저닝을 사용하지 않고 단순하게 아래와 같이 구성할 수 있을 것 같은데 리니의 의견이 궁금합니다.

``` java
    @GetMapping
    public ResponseEntity<CommentResponses> readCommentsByMomentId(
            @LoginMember Member member,
            @RequestParam @Min(value = 1L, message = "스타카토 식별자는 양수로 이루어져야 합니다.") long momentId
    ) {
        CommentResponses commentResponses = commentService.readAllCommentsByMomentId(member, momentId);
        return ResponseEntity.ok().body(commentResponses);
    }

    @GetMapping(path = "/{momentId}")
    public ResponseEntity<CommentResponses> readCommentsByMomentIdPathVariable(
            @LoginMember Member member,
            @PathVariable @Min(value = 1L, message = "스타카토 식별자는 양수로 이루어져야 합니다.") long momentId) {
        CommentResponses commentResponses = commentService.readAllCommentsByMomentId(member, momentId);
        return ResponseEntity.ok().body(commentResponses);
    }

```

2024-11-12 11:44 UTC, linirini commented on backend/src/main/java/com/staccato/comment/controller/CommentController.java
> +    @PostMapping("/comments")
동의합니다! 반영하도록 하겠습니다👍

2024-11-12 11:46 UTC, linirini commented
> 제가 이슈확인이 늦어 리뷰를 늦게달았네요 죄송합니다 🙇‍♂️ 기존에 존재하던 쿼리파라미터 형태에서 PathVariable형태로 변경함에 따라 버저닝을 도입하시게 된 것 같은데 그로 인하여 불필요한 변경이 일어난 것 같습니다. 버저닝을 사용하지 않고 단순하게 아래와 같이 구성할 수 있을 것 같은데 리니의 의견이 궁금합니다.
> 
> ```java
>     @GetMapping
>     public ResponseEntity<CommentResponses> readCommentsByMomentId(
>             @LoginMember Member member,
>             @RequestParam @Min(value = 1L, message = "스타카토 식별자는 양수로 이루어져야 합니다.") long momentId
>     ) {
>         CommentResponses commentResponses = commentService.readAllCommentsByMomentId(member, momentId);
>         return ResponseEntity.ok().body(commentResponses);
>     }
> 
>     @GetMapping(path = "/{momentId}")
>     public ResponseEntity<CommentResponses> readCommentsByMomentIdPathVariable(
>             @LoginMember Member member,
>             @PathVariable @Min(value = 1L, message = "스타카토 식별자는 양수로 이루어져야 합니다.") long momentId) {
>         CommentResponses commentResponses = commentService.readAllCommentsByMomentId(member, momentId);
>         return ResponseEntity.ok().body(commentResponses);
>     }
> ```

이 부분에 대해서는 폭포가 말씀해주신 방식을 적용하여 불필요한 코드 변경을 제거하였습니다. 한 번 확인 부탁드립니다👍

2024-11-12 11:50 UTC, linirini commented on backend/src/test/java/com/staccato/comment/controller/CommentControllerTest.java
> +        mockMvc.perform(put("/v2/comments/{commentId}", 1)
검증하고자 하는 바(테스트의 목적)이 같기 때문에 하나의 테스트에서 검증만 추가해도 될 것 같다고 판단했습니다😊

2024-11-12 12:29 UTC, BurningFalls approved these changes
추가 커밋 확인했습니다. 수고하셨습니다, 리니!

2024-11-13 09:39 UTC, Ho-Tea approved these changes
변경사항 확인했습니다 👍
고생하셨습니다 리니!

2024-11-13 10:01 UTC, merged