refactor: 카테고리, 일시 선택 순서 변경 및 리팩터링 (스타카토 생성/수정) #564
woowacourse-teams/2024-staccato pull request #567
Opened 2024-12-08 12:48 UTC by s6m1n

## ⭐️ Issue Number
- #564 

## 🚩 Summary
스타카토 생성/수정 화면의 카테고리, 일시 관련 로직에 아래의 작업들을 수행했습니다.
- [x] 카테고리, 일시 선택 순서 변경
- [x] 카테고리, 일시 선택 코드 리팩터링
- [x] 카테고리, 일시 선택 로직 테스트 추가

### 리팩터링 내용 정리
#### 생성 화면

1. `fetchMemoryCandidates()`로 사용자의 모든 추억을 불러와 `_memoryCandidates`를 업데이트 합니다.
2. 이 때 `_memoryCandidates`는 최초 한 번 업데이트된 후엔 변하지 않습니다.
3. `memoryCandidates.observe` 람다에서 `initMemoryAndVisitedAt()`를 수행하여 일시, 추억의 초기값을 세팅합니다.
    1. 메인 화면에서 생성 (memoryId == 0L)
        - **일시** 먼저 초기화 → `LocalDateTime.now()` (선택 가능한 일시 범위는 selectedVisitedAt ±10년)
        - 일시를 기준으로 **추억**을 초기화 → `updateMemoryCandidateAndVisitedAt()`
        - 일시가 바뀌면 추억을 다시 세팅
    2. 추억 화면에서 생성 (memoryId를 알고 있는 경우)
        - **추억** 먼저 초기화 → memoryId가 일치하는 추억으로 고정
        - 추억을 기준으로 **일시**를 초기화 → 추억 기간 안에서 'LocalDate.now()'와 가장 인접한 날짜 선택 (`MemoryCandidate`의 `getClosestDateTime()` 참고)
        - 선택 가능한 일시 범위는 추억 기간으로 세팅

#### 수정 화면
1. 사용자의 모든 추억을 불러옵니다. (`fetchMemoryCandidates()`)
2. 수정 대상인 스타카토의 정보를 불러옵니다. (`fetchStaccatoBy()`)
3. 불러온 스타카토 정보로 추억, 일시를 초기화 합니다.
4. 일시가 바뀌면 추억을 다시 세팅합니다.

## 🛠️ Technical Concerns

### 스타카토 생성/수정 ViewModel 테스트

MVVM 구조의 뷰모델 내부 LiveData 값을 테스트하기 위해 아래 Rule을 설정하고 getOrAwaitValue를 추가했습니다.

```kotlin
    @get:Rule
    var instantTaskExecutorRule = InstantTaskExecutorRule()

    @get:Rule
    val mainDispatcherRule = MainDispatcherRule()
```

또한 mockK의 coEvery와 coroutines.test의 runTest를 사용했습니다.

## 🙂 To Reviewer

2024-12-13 11:18 UTC, hxeyexn commented
@s6m1n 
ktlintcheck 확인 한번 부탁드려요!

2024-12-15 10:32 UTC, hxeyexn requested changes
빙티!! 리팩터링과 테스트 작성하느라 너무 고생 많으셨습니다..!
리뷰가 너무 늦었네요 ㅠㅠ 죄송합니다...! 🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️🙇‍♂️

리뷰를 남기다보니 양이 조금 많아졌는 데 보시다가 이해 안되는 부분 있으시면 언제든 편하게 말씀해주세용! 아직 ViewModelTest는 깊게 보지 못해서 좀 더 보다가 코멘트 남길 부분 있으면 더 남겨두겠습니다~

정말정말 고생 많으셨습니다!! 👍 💯 
외쳐 갓티!!!!!!!!!❤️‍🔥

2024-12-15 10:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/test/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModelTest.kt
> +class StaccatoCreationViewModelTest {
코루틴 환경에서 테스트를 위해 `@ExperimentalCoroutinesApi`를 추가해줘야할 것 같아요!

2024-12-15 10:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/test/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModelTest.kt
> +class StaccatoCreationViewModelTest {
코루틴 환경에서 테스트를 위해 `@ExperimentalCoroutinesApi`를 추가해줘야할 것 같아요!
```suggestion
@RunWith(JUnit4::class)
@ExperimentalCoroutinesApi
class StaccatoCreationViewModelTest {
```

2024-12-15 10:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/test/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModelTest.kt
> +    @OptIn(ExperimentalCoroutinesApi::class)
> 코루틴 환경에서 테스트를 위해 @ExperimentalCoroutinesApi를 추가해줘야할 것 같아요!

위 코멘트대로 class에 어노테이션을 달면 메서드에는 어노테이션을 제거해도 되겠네요~

2024-12-15 10:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/test/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModelTest.kt
> +            viewModel.fetchMemoryCandidates()
이 부분은 `StaccaoCreationViewModelTest` 내부의 모든 메서드가 가지고 있는데 `setUp()` 메서드에서 해주거나 메서드로 분리하는 건 어떨까요?

2024-12-15 10:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/test/java/com/on/staccato/presentation/staccatoupdate/viewmodel/StaccatoUpdateViewModelTest.kt
> +            Assert.assertEquals(targetStaccato.placeName, actualPlaceName)
Assert는 제거하는 게 어떨까요!

```suggestion
            assertEquals(targetStaccato.placeName, actualPlaceName)
```

2024-12-15 10:32 UTC, hxeyexn commented on android/Staccato_AN/app/src/test/java/com/on/staccato/presentation/staccatoupdate/viewmodel/StaccatoUpdateViewModelTest.kt
> +            viewModel.fetchTargetData(staccatoId = TARGET_STACCATO_ID)
이 부분도 `StaccaoUpdateViewModelTest` 내부의 모든 메서드가 가지고 있는데 `setUp()` 메서드에서 해주거나 메서드로 분리해 중복을 제거하는 게 어떨까용?

2024-12-16 13:40 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/StaccatoCreationActivity.kt
> observeViewModelData() 메서드를 분리해보는 건 어떨까요? 메서드가 한 가지 일만 하도록이요!

좋은 의견 감사합니다 해나👍
라이브 데이터마다 메서드를 분리하면 Activity의 메서드의 수가 과하게 많아지고, 데이터 간 의존성 파악이 어려울 것 같다는 생각이 들었어요.
그래서 아래처럼 관련 있는 데이터들끼리 묶어서 그룹화 하여 분리해보았습니다!
```kotlin
        observePhotoData() // 사진 첨부 관련 데이터
        observePlaceData() // 장소 선택 관련 데이터
        observeVisitedAtData() // 일시 선택 관련 데이터
        observeMemoryData() // 카테고리 선택 관련 데이터
        observeCreatedStaccatoId() // 생성 완료 여부 데이터
```

2024-12-16 15:19 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/StaccatoCreationActivity.kt
> +        )
중복 호출이 두 번 밖에 없어서, 개인적으로는 따로 변수로 저장하지 않고 처리하는 게 더 직관적으로 읽히는 것 같습니다
또 `toLocalDate()`가 무거운 로직이 아니어서 성능에 크게 무리가 없을 거라고 생각했어요😅

그치만... 제안해주신 코드가 유지보수 측면에서는 더 유리해보이네요!!! 👍
반영 완료했습니다!

2024-12-16 15:24 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/domain/model/MemoryCandidate.kt
> +    }
세상에나 확장함수로 분리하니 훨씬 깔끔하네요🥹 적용 완료!

2024-12-16 15:54 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModel.kt
> +        private fun setCurrentDateTimeAsVisitedAt(visitedAt: LocalDateTime) {
훨씬 깔끔하게 읽히네요 👍
메서드명에서 매개변수명 중복을 제거하고 단순화 했습니다!

2024-12-16 16:42 UTC, s6m1n commented on android/Staccato_AN/app/src/test/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModelTest.kt
> +    private lateinit var imageRepository: ImageDefaultRepository
테스트에서 사용되지 않더라도 해당 `Repository`들은 `MockK`로 초기화해야 합니다.
`@InjectMockKs`로 `StaccatoCreationViewModel`을 초기화할 때 모든 의존성을 자동으로 주입하기 때문인데요!
뷰모델의 생성자에 `staccatoRepository`, `imageRepository`도 포함되므로 위 코드가 없다면 아래와 같은 예외가 발생합니다..🥲
<img width="1014" alt="image" src="https://github.com/user-attachments/assets/c284bbee-ad0e-4dcc-8f47-5f773eb08dea" />

2024-12-16 19:25 UTC, Junyoung-WON requested changes
빙티!! 깃헙에서 보는건 오랜만이에요! 🙋
리뷰가 너무너무너무 늦어진 점 정말 깊이 사죄드립니다...
제가 게으른 탓이니 용서하지 말아요 🥲

수정사항 반영과 리팩터링, 테스트 작성까지 정말, 무지 고생하셨어요!! 변경 사항에 맞춰 잘 구현해주신 것 같아요.
그리고 드디어 우리 프로젝트의 안드로이드에도 테스트가 생겼네요! 야호~ 🥳
코드 양을 보니 시간이 꽤 걸렸을텐데 빠르게 잘 구현해주셨어요! 👍

해나가 이미 많은 부분을 꼼꼼히 잘 짚어준 터라, 변경된 양에 비해서 제가 리뷰드릴 부분이 많지는 않았어요! ~~그래도 왜 20개나 되나요...~~
지각한 주제에 조금이라도 도움을 드리고자, 머리를 쥐어짜내서 단 코멘트가 대부분이라...!
너무 부담가지지 않고 시간날 때 천천히 읽어주셨으면 좋겠습니당

2024-12-17 03:18 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/domain/model/MemoryCandidates.kt
> +}
정확합니다👍 진입 화면에 따라 선택 가능한 카테고리를 필터링하는 기준이 달라서 오버로딩하도록 구현했어요!

2024-12-17 04:22 UTC, s6m1n commented on android/Staccato_AN/app/src/test/java/com/on/staccato/domain/model/MemoryCandidateTest.kt
> +    fun `특정 날짜가 startAt과 endAt 사이에 포함되면 true 반환`() {
코드에서 접하는 실질적인 컴포넌트나 함수 이름이 더 명시적일 거라고 생각했는데,
제시해주신 예시에 따르면 후자가 훨씬 직관적이고 의미를 파악하기 쉽네요👍
`MemoryCandidate`의 **기능**에 초점을 맞춰 수정 완료했습니다!

2024-12-17 04:23 UTC, s6m1n commented on android/Staccato_AN/app/src/test/java/com/on/staccato/domain/model/MemoryCandidateTest.kt
> +    }
이유는... 없습니다!! 적용 완료했습니다😅

2024-12-17 04:24 UTC, s6m1n commented on android/Staccato_AN/app/src/test/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModelTest.kt
> +    @OptIn(ExperimentalCoroutinesApi::class)
@ExperimentalCoroutinesApi 적용 범위를 class 단위로 옮겼습니다~!

2024-12-17 04:37 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/domain/model/MemoryCandidate.kt
> +    fun getClosestDateTime(date: LocalDateTime): LocalDateTime {
> 항상 현재 날짜가 파라미터로 들어가게 됩니다.

지금의 로직에서는 호두가 말씀하신 경우만 존재하는 게 맞습니다!
다만 저는 `getClosestDateTime()`메서드가 그저 전달된 날짜와 가장 가까운 날짜를 반환하는 책임만 가질 뿐,
**파라미터로 전달되는 날짜가 현재 날짜인지**는 관심사가 아니라고 생각했습니다.
또한, 추후 '현재 날짜'가 아닌 파라미터가 들어오지 않는다는 보장도 없기에, **재사용성과 확장성**을 고려하여
파라미터에 '현재 날짜'라는 의미를 담지 않으려고 했습니다.

호두의 의견대로라면 해당 메서드가 어떤 맥락에서 사용되는지, 파라미터 명으로 파악하기 좀 더 수월할 것 같다는 장점이 있는 것 같아요!
어떤 게 더 나을까요? 해나의 의견도 궁금합니다! @hxeyexn

2024-12-18 06:35 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/domain/model/MemoryCandidates.kt
> +    fun filterCandidatesBy(memoryId: Long): List<MemoryCandidate> = memoryCandidate.filter { it.memoryId == memoryId }
수정 완료했습니다👍
filterCandidatesBy의 결과를 selectableMemory에 바로 적용하고자 `List<MemoryCandidate>`로 반환형을 통일했는데,
호두의 말대로 ID로 하나의 `MemoryCandidate`를 찾는 로직이므로 List를 반환하는 것은 어색해 보이네요!

2024-12-18 06:36 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/StaccatoCreationActivity.kt
> +        viewModel.selectedMemory.observe(this) { it ->
오잉 이녀석이 왜 있을까요 ㅋㅋ 제거 완!

2024-12-18 07:14 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModel.kt
> +        fun setMemoryCandidateByVisitedAt(visitedAt: LocalDateTime) {
뷰모델에 `selectableMemories`와 `selectedMemorie`라는 이름의 LiveData 변수가 모두 존재하기 때문에
`setSelectableMemoriesByVisitedAt`는 자칫하면 `selectableMemories`만 다루는 메서드로 받아들여질 수 있단 우려가 드네요!

@hxeyexn 의 의견도 궁금합니다... 좋은 아이디어 있으신지요... 이름 짓기 힘들다~

2024-12-18 07:17 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatoupdate/StaccatoUpdateActivity.kt
해당 코멘트 내용 반영하며 함께 수정 완료했습니다!🫡

2024-12-18 08:03 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatoupdate/viewmodel/StaccatoUpdateViewModel.kt
> +                )
StaccatoResponse와 동일한 구조로 Staccato를 만들다 보니 어색한 구조가 된 것 같아요!
저도 스타카토가 카테고리의 id와 title을 직접 들고 있는 것 보다는, 카테고리를 객체로 갖고 있는 게 더 자연스럽다고 생각합니다~

2024-12-18 08:06 UTC, s6m1n commented on android/Staccato_AN/app/src/test/java/com/on/staccato/domain/model/MemoryCandidateFixture.kt
> +internal val yearStart2025 = LocalDate.of(2025, 1, 1)
훨씬 명료하네요! 반영했습니다~

2024-12-18 08:22 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatoupdate/viewmodel/StaccatoUpdateViewModel.kt
> +        fun fetchTargetData(staccatoId: Long) {
```kotlin
        fun fetchStaccato(staccatoId: Long) {
            fetchMemoryCandidates()
            fetchStaccatoBy(staccatoId)
        }
```
위 처럼 fetchTargetData메서드 내부에서는
스타카토와 상관 없이 **`사용자의 모든 카테고리`** 를 불러오는 `fetchMemoryCandidates()`와
**`수정 대상이 되는 스타카토`** 를 불러오는 `fetchStaccatoBy()`를 수행합니다.
따라서 제안하신 것처럼 스타카토를 특정하는 함수명보단, 두 함수를 포함하는 네이밍이 좋을 것 같단 생각이 들어요!

`fetchStaccatoAndMemories`는 어떠신가요?

2024-12-18 09:19 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/domain/model/MemoryCandidate.kt
> +    fun getClosestDateTime(date: LocalDateTime): LocalDateTime {
@s6m1n

호두의 의견도 좋지만 빙티의 의견에 조금 더 공감합니다!
`MemoryCandidate` 는 `getClosestDateTime`에 넘어오는 인자가 현재 날짜인지 알 필요가 없다고 생각합니다.
`getClosestDateTime` 메서드를 다른 파일에서 사용할 때에만 명시적으로 넘겨주는 편이 좋다고 생각해요!


`Lv1 강의 자료 자동차 피드백`

<img width="388" alt="image" src="https://github.com/user-attachments/assets/3f400a5d-6340-4cf0-b7d8-b952fc41215e" />

2024-12-18 10:34 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatoupdate/viewmodel/StaccatoUpdateViewModel.kt
> +                )
빙티 의견에 동의합니다! 😄
이제 도메인 친구들이 조금씩 로직이 생기고 역할을 받게 되었으니, 다함께 천천히 고민해보면 좋을 것 같아요!

2024-12-18 10:43 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatoupdate/viewmodel/StaccatoUpdateViewModel.kt
> +        fun fetchTargetData(staccatoId: Long) {
그렇군요! 😲
두 가지 다른 데이터를 불러오기 때문에 조금은 추상적인 이름을 갖게 되었군요...!

> 따라서 제안하신 것처럼 스타카토를 특정하는 함수명보단, 두 함수를 포함하는 네이밍이 좋을 것 같단 생각이 들어요!

좋은 생각입니다! 👍
`fetchTargetData` 보다 더 명시적이고 적절한 이름이라고 생각합니다!

2024-12-18 10:51 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModel.kt
> +        fun setMemoryCandidateByVisitedAt(visitedAt: LocalDateTime) {
> setSelectableMemoriesByVisitedAt는 자칫하면 selectableMemories만 다루는 메서드로 받아들여질 수 있단 우려가 드네요!

호두 의견도 너무 좋지만 저는 빙티 의견에 좀 더 동의합니다~
`visitedAt`에 따라 선택 가능한 추억 목록을 갱신하고, 이에 따라 선택된 추억도 변경해주는 로직임을 메서드명에서 명시적으로 나타내는 것이 좋을 것 같아서요!

스타카토 생성 및 수정 화면에서 추억 선택이라고 명시하고 있으니 **추억 선택**이라는 단어를 활용해보는 건 어떨까요?
도메인 모델명과 ViewModel의 변수명을 그대로 메서드명에 사용하려다 보니 생긴 문제인 것 같아서 화면을 중심으로 메서드명을 고민해봤습니다!

<img width="345" alt="image" src="https://github.com/user-attachments/assets/660aed31-954e-4426-b2df-1320bae46bf8" />

```suggestion
        fun updateMemorySelectionBy(visitedAt: LocalDateTime) {
```

2024-12-18 10:55 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModel.kt
> +        fun setMemoryCandidateByVisitedAt(visitedAt: LocalDateTime) {
해나가 제시한 이름이 적절한 것 같아요! 👍
간결하면서도 메서드의 동작이 잘 나타나네요!

2024-12-18 11:07 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/on/staccato/domain/model/MemoryCandidate.kt
> +    fun getClosestDateTime(date: LocalDateTime): LocalDateTime {
그렇군요!!
객체 지향적인 관점에서는 `MemoryCandidate` 는 자신이 받은 날짜가 현재 날짜인지는 중요하지 않겠네요~
빙티와 해나의 의견에 동의합니다 👍

2024-12-19 03:52 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModel.kt
> +        fun setMemoryCandidateByVisitedAt(visitedAt: LocalDateTime) {
너무 좋네요!! 작명소 차립시다 해나 ㅋㅅㅋ

2024-12-19 03:59 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModel.kt
> +        }
> 현재 선택된 카테고리가 있다면 해당 카테고리를 그대로 선택하고, 없다면 필터링된 카테고리의 첫 번째로 설정하는 로직

위 로직은 카테고리 후보를 갖고있는 일급 컬렉션 `MemoryCandidates` 의 책임으로 두어도 좋다는 생각이 들었어요.
따라서 아래처럼 `MemoryCandidates` 클래스의 내부로 해당 로직을 이동했습니다!

```kotlin
data class MemoryCandidates(val memoryCandidate: List<MemoryCandidate>) {

    fun findByIdOrFirst(targetId: Long?): MemoryCandidate? =
        memoryCandidate.find { it.memoryId == targetId }
            ?: memoryCandidate.firstOrNull()
}
```

이에 따라 뷰모델의 `selectableMemories` 타입이
`LiveData<List<MemoryCandidate>>`에서 `LiveData<MemoryCandidates>`로 변경되었습니다.

2024-12-19 06:21 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/on/staccato/domain/model/MemoryCandidates.kt
> +    fun filterBy(date: LocalDate): MemoryCandidates = copy(memoryCandidate = memoryCandidate.filter { it.isDateWithinPeriod(date) })
copy의 적절한 활용 너무 좋아요!
갓티~~

2024-12-19 06:21 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/viewmodel/StaccatoCreationViewModel.kt
> +        val selectableMemories: LiveData<MemoryCandidates> get() = _selectableMemories
`selectableMemories` 도 도메인인 `MemoryCandidates`로 변경하면서 일급 컬렉션을 더 잘 활용하게 되었네요! 😃

2025-01-07 06:20 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/domain/model/MemoryCandidate.kt
>      companion object {
저도 MemoryCandidate 동반객체가 해당 로직을 갖고 있는 것이 어색하다는 의견에 동의합니다.
따라서 날짜 범위를 관리하는 도메인 모델 객체 `YearCalendar`, `MonthCalendar`, `DateCalendar` 를 새로 만들어 주어 해당 로직을 책임지도록 분리했습니다.
또한 각 클래스에 대한 단위 테스트도 함께 구현해보았습니다!

2025-01-07 06:23 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/domain/model/MemoryCandidate.kt
>      companion object {
해당 로직이 DateCalendar의 calculateDateRangeIn 메서드 내부로 이동함에 따라 아래처럼 개선되었습니다.

```kotlin
        private fun calculateDateRangeIn(
            year: Int,
            month: Int,
            lastDateOfMonth: Int,
            periodStart: LocalDate,
            periodEnd: LocalDate,
        ): List<Int> =
            when {
                isInSameMonth(year, month, periodStart, periodEnd,) -> createDatesBetween(periodStart.dayOfMonth, periodEnd.dayOfMonth)
                isStartMonth(year, month, periodStart) -> createDatesBetween(periodStart.dayOfMonth, lastDateOfMonth,)
                isEndMonth(year, month, periodEnd) -> createDatesBetween(1, periodEnd.dayOfMonth)
                else -> createDatesBetween(1, lastDateOfMonth)
            }
```

2025-01-07 06:26 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/dialog/VisitedAtSelectionFragment.kt
> +    private var selectedHour by Delegates.notNull<Int>()
by Delegates.notNull()을 사용할 때는 주의가 필요하겠군요..🤔 좋은 정보 감사합니다 해나!
`selectedXXX` 변수를 `YearCalendar` 객체 내부로 이동함에 따라 지연 초기화가 필요하지 않아 해당 코드는 삭제했습니다.

2025-01-07 06:27 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/domain/model/MemoryCandidate.kt
>      companion object {
이 부분도 `XXXCalendar` 도메인 객체들을 만들어주어 개선했습니다!

2025-01-07 06:31 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/dialog/VisitedAtSelectionFragment.kt
`selectedXXX` 변수를 `YearCalendar` 객체 내부로 이동시킴에 따라 `VisitedAtSelectionFragment`에서는 yearCalendar 하나만 갖고 있도록 줄일 수 있었습니다!  관리하는 값이 하나라서 ViewModel까지는 필요하지 않을 것 같아요~!

2025-01-07 06:36 UTC, s6m1n commented on android/Staccato_AN/app/src/main/java/com/on/staccato/presentation/staccatocreation/dialog/VisitedAtSelectionFragment.kt
해당 부분 반영 완료했습니다!

- [feat: 일시 선택을 위한 Calendar 도메인 모델과 팩토리 메서드 추가](https://github.com/woowacourse-teams/2024-staccato/pull/567/commits/aa0b4b051c5419fe178271254a79ca6ffadef0f2)

- [feat: DateCalendar 클래스 public 함수 및 유효성 검사 추가](https://github.com/woowacourse-teams/2024-staccato/pull/567/commits/53d84c7ef299f6427fdd0c57dd7fd775e175dc64)
테스트 : dfb05d46d99c151fe6f39e9a715a9b349919956a

- [feat: MonthCalendar 클래스 public 함수 및 유효성 검사 추가](https://github.com/woowacourse-teams/2024-staccato/pull/567/commits/ee0df20ec9809adb4a4f6018263aa4934106ebb1)
테스트 : dfb05d46d99c151fe6f39e9a715a9b349919956a

- [feat: YearCalendar 클래스 public 함수 및 유효성 검사 추가](https://github.com/woowacourse-teams/2024-staccato/pull/567/commits/4d7dea89e41b8cc91c5c7674ef9ca601936bb9c1)
[feat: YearCalendar 날짜 선택을 위한 프로퍼티와 메서드 추가](https://github.com/woowacourse-teams/2024-staccato/pull/567/commits/f3214d7e577b93b9b0cd4817bfffc22899373e70)
테스트 : e16945e888795119cf1943b3e978d5bc8273b4b6

2025-01-11 04:02 UTC, hxeyexn commented on android/Staccato_AN/app/src/main/java/com/on/staccato/domain/model/MemoryCandidate.kt
>      companion object {
날짜 범위를 관리하는 도메인 모델 객체들이 생기면서 코드의 가독성이 훨씬 좋아졌네요!! 💯 👍

2025-01-11 04:42 UTC, hxeyexn approved these changes
정말정말정말정말 고생 많으셨습니다!!!🥹👏  빙티 쵝오 🫶❤️‍🔥😘
도메인 테스트를 정말 꼼꼼히 작성해주셨네요!! 💯 

사소한 코멘트 몇개 남겨뒀습니당~ 정말 사소한 내용이니 시간 되실 때 편하게 읽어주세요!
크게 수정해야할 부분은 더 이상 보지 않아서 이만 Approve하도록 하겠습니다!

너무 고생하셨습니다!!!!!!!!!!!!!!!

![Group 48096807](https://github.com/user-attachments/assets/601bcf28-81ac-4014-8ba7-517d6b1f7257)

2025-01-11 04:42 UTC, hxeyexn commented on android/Staccato_AN/app/src/test/java/com/on/staccato/domain/model/YearCalendarTest.kt
테스트 작성을 정말 꼼꼼하게 해주셨네요! 👍

2025-01-11 04:42 UTC, hxeyexn commented on android/Staccato_AN/app/src/test/java/com/on/staccato/domain/model/DateCalendarTest.kt
> +        assertEquals(expected, actual)
CallAdapter가 머지된 후에 JUnit5로 마이그레이션해보는 것도 좋을 것 같네용!

2025-01-11 04:42 UTC, hxeyexn commented on android/Staccato_AN/app/src/test/java/com/on/staccato/domain/model/MonthCalendarTest.kt
> +    fun `범위보다 크면 가장 마지막 월을 반환한다`(targetMonth: Int) {
어떤 범위인지 좀 더 구체적이면 테스트하고자하는 바가 확실히 전달될 것 같아요!

2025-01-11 04:52 UTC, Junyoung-WON approved these changes
진짜 혼또니 완전 너무나 엄청나게 어메이징 고생 많았습니다...!! 😭
정말 모든 리뷰를 다 반영해주셨네요.... 리뷰 양도 많았고 우테코 미션보다도 규모가 더 커서 리뷰 반영이 많이 힘드셨을텐데, 정말 고생많았고 또 감사합니다!!! 🙇‍♂️🙇‍♂️🙇‍♂️

더이상 피드백드릴게 없을 것 같아요! 드디어 Approve를.. 머지를 해보자구요!

이제는 리뷰 일정과 분량을 생각해서 효율적으로 리뷰를 해봅시다ㅎㅎ🥲
그저 갓티!!!!

2025-01-11 05:15 UTC, Junyoung-WON commented on android/Staccato_AN/app/src/test/java/com/on/staccato/domain/model/DateCalendarTest.kt
> +    @Test(expected = IllegalArgumentException::class)
어노테이션의 파라미터로 예외 발생을 테스트할 수 있군요...? 😮 👍

2025-01-11 14:34 UTC, merged

2025-01-12 03:05 UTC, linirini reviewed
제 눈에는 좋아 보여요~
고생 많았슴당 빙티!!

2025-01-12 03:06 UTC, Ho-Tea reviewed
확실히 코드가 더 개선된 것 같네요 👍
고생하셨습니다 빙티 🙇‍♂️

2025-01-12 03:06 UTC, BurningFalls reviewed
고생 많으셨습니다 빙티!! 😄